### PR TITLE
GoPay Icon

### PR DESCRIPTION
**Pull request by KhaiCo**
* [**Icon addition**](?expand=1&template=icon_addition.md&labels=needs+review,icon+change)
GoPay = com.gojek.gopay

### CODE REVIEW

**Review by x9136 — CHANGES_REQUESTED** [review]
@KhaiCo Hi! Thank you for contributing. The icon is not the right size and style. If you want to redesign it, I suggest taking 5-10 minutes for [the guideline](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#artboard--grid). Feel free to ask if anything is unclear.

Screenshot 2023-10-28 at 14 48 15
The final result could be something like this.

**Comment by KhaiCo** [comment]
@x9136 
Thanks for your review but I have a question is the stroke not the right size or the overall vector? And is the simplified design a requirement or a suggestion? I'm trying to make it as close as possible to the original. Here is the original picture for reference:
IMG_20231023_164312
And if the stroke is the only problem is this acceptable:
Untitled (1)
Sorry I wanted to put it in the guide but my editor bugged it out for some reason

**Comment by x9136** [comment]
> is the stroke not the right size or the overall vector?

Screenshot 2023-10-28 at 15 20 02
As I can see, you used a 8px stroke. Technically that's ok, but the base thickness of the stroke is 12px, and 8px is used when 12px degrades the quality of the icon. In your case you can get by with 12px, and if you use 8px, the icon will be too different from the rest.

Screenshot 2023-10-28 at 15 10 25
In terms of size, you got the icon and the canvas to be the same size. The canvas should be 192×192px and one side of the icon should be 160px.

> And is the simplified design a requirement or a suggestion? I'm trying to make it as close as possible to the original.

It's all about achieving two goals: 1. To make the icon fit the style of Lawnicons (taking into account the guideline and the way the other icons are made). 2. So that a person can recognize the application by the icon.

So the goal is not to keep the original completely, but to make the most recognizable icon in the Lawnicons style. My simplified version is one of the options that will fit the requirements and look appropriate on the phone screen among other icons.

**Comment by x9136** [comment]
> the icon will be too different from the rest.
<details><summary>Test</summary></details>

**Comment by KhaiCo** [comment]
I've changed the size according to your requirement, does the design need to change?

**Comment by KhaiCo** [comment]
I've downloaded the debug build and the strokes kinda collide with each other and looks weird, how can I fix this?
Screenshot_2023-10-28-19-47-44-857-edit_app lawnchair

**Comment by x9136** [comment]
> the strokes kinda collide with each other and looks weird, how can I fix this?

To avoid this, you need to avoid small distances between lines. For example, instead of two lines, you can make one line or reduce the circle until there is no emptiness inside. Or, on the contrary, make the distances significantly larger so that they don't shrink on the phone screen.

One of the ways is shown in the beginning.
Screenshot 2023-10-28 at 15 55 29

**Comment by x9136** [comment]
Could you make an icon without using groups? I can't actually make sure if the size is correct right now.

**Comment by KhaiCo** [comment]
> Could you make the icon without using groups? I can't actually make sure if the size is correct right now.

Here is the icon Ungrouped (I think)
Ungrouped
Sorry I can't really do the changes I want to do as I don't have access to my computer and I'm really unfamiliar with the editor that I'm using on my phone.

**Comment by x9136** [comment]
> Here is the icon Ungrouped (I think)

Yes, that'll do. 

Screenshot 2023-10-28 at 19 55 13

As you can see, the icon is much larger than it needs to be.

> Sorry I can't really do the changes I want to do as I don't have access to my computer and I'm really unfamiliar with the editor that I'm using on my phone.

No problem. This PR will be open for over a month, and if it closes, you can create a new one. The icon doesn't fit at the moment due to incorrect size. It could also be significantly improved by working on the small line spacing.

**Comment by KhaiCo** [comment]
> As you can see, the icon is much larger than it needs to be.
>
Huh that's weird I set it to 160 px

**Comment by KTibow** [comment]
Let me bed
160 (stroke) + 6 (stroke on the left) + 6 (stroke on the right) = 172

**Comment by KhaiCo** [comment]
Does this look fine? 
Screenshot_2023-10-29-00-33-55-752-edit_app lawnchair

**Comment by KhaiCo** [comment]
> Let me bet 160 (stroke) + 6 (stroke on the left) + 6 (stroke on the right) = 172

Oh yeah that kinda make sense

**Comment by KTibow** [comment]
Your SVG is missing a width and height

**Comment by KhaiCo** [comment]
> Your SVG is missing a width and height

Uh what does that mean? Can you elaborate?

**Comment by KTibow** [comment]
image

**Comment by KhaiCo** [comment]
> image

Huh, I thought SVGs works fine without a view port value, what's the value supposed to be? 160 or 192?

**Comment by KTibow** [comment]
this is an image of your current svg
your current svg is missing the `width="192" height="192"`

**Comment by KhaiCo** [comment]
> this is an image of your current svg your current svg is missing the `width="192" height="192"`
How about this one?
gopay

**Comment by x9136** [comment]
> current svg is missing the width="192" height="192"

Apparently that's why GitHub shows its own canvas size in the preview.

> How about this one?

Screenshot 2023-10-28 at 20 58 46
We can spend a lot of time on testing different variants, so I suggest to find an editor where it is possible to make the size as it should be without checks — canvas 192×192, icon 160×160. Or look for tutorials for the current editor.

**Comment by KhaiCo** [comment]
>We can spend a lot of time on testing different variants, so I suggest to find an editor where it is possible to make the size as it should be without checks — canvas 192×192, icon 160×160. Or look for tutorials for the current editor.
>
This **should** work (hopefully)
Untitled (10)

**Comment by KhaiCo** [comment]
On the guide:
Screenshot_2023-10-29-01-37-00-341_com app vectorink
In my homescreen dock:
Screenshot_2023-10-29-01-45-40-581-edit_app lawnchair

**Comment by KTibow** [comment]
as 9136 did in their concept
image
i would make the keyhole with fill, not stroke

**Comment by x9136** [comment]
> On the guide:

As you can see, it's noticeably smaller than it needs to be (154.8×154.8).

> i would make the keyhole with fill, not stroke

Screenshot 2023-10-28 at 22 26 02
To be fair it's a stroke.

**Comment by KhaiCo** [comment]
>As you can see, it's noticeably smaller than it needs to be (154.8×154.8).
>
Um, do I need to fix it or is it fine?

**Comment by x9136** [comment]
> Um, do I need to fix it or is it fine?

That's too big a difference. It is normal if the error is not more than 1px.

Let's try it this way. I give you my svg, you evaluate how the sizes are made there to see how to make it for you. Maybe this will help.
Try

**Comment by KhaiCo** [comment]
Screenshot_2023-10-29-02-40-28-671_com app vectorink
Fits like a glove (the height is intentional)

**Comment by KTibow** [comment]
You added an extra file instead of updating your current one

**Comment by KhaiCo** [comment]
Oh I'm really sorry it's 3 am in my place

**Review by x9136 — APPROVED** [review]
Screenshot 2023-10-28 at 22 57 35
The size is still smaller than it needs to be and you decided to use fill, which is bad when you can do the same thing with a stroke.

It's ok for the first time. If you want to improve the quality of the icon in the future, it's worth it.

**Comment by KhaiCo** [comment]
>The size is still smaller than it needs to be and you decided to use fill, which is bad when you can do the same thing with a stroke.

It's ok for the first time. If you want to improve the quality of the icon in the future, it's worth it.
>
@x9136 thank you very much for the feedback and helping me along the way, I actually intentionally left the gap there to make the icon wider as with the original but maybe you think that's not the right call.

Now that I know all the settings, guidelines and rules I'll be sure to contribute more in the future. Thank you once again, you too @KTibow!

**Pull request merged**
