### PR TITLE
Link 4 icons

### PR DESCRIPTION
**Pull request by ArtikusHG**
## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons linked
* UntrackMe (linked `app.fedilab.nitterizeme` to `@drawable/trust_wallet`)
* TimeTable - a FOSS timetable app, icon looks very similar to the news glyph, even though the app has a different purpose (linked `com.asdoi.timetable` to `@drawable/news`)
* Librera Reader - not related to google, but icon looks very similar to google books glyph (linked `com.foobnix.pro.pdf.reader` to `@drawable/google_play_books`)
* Iconify - a FOSS UI customization app, again, totally unrelated to the original glyph but looks very similar (linked `com.drdisagree.iconify` to `@drawable/eksi_sozluk`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for the new links. 

Could you change the name of the link to be the same as the the original icon link?

for example:
`<icon drawable="@drawable/news" package="com.asdoi.timetable" name="TimeTable" />`
will change to
`<icon drawable="@drawable/news" package="com.asdoi.timetable" name="News / Nachrichten" />`

This is because links with different names will create duplicates in the icon gallery.

**Comment by ArtikusHG** [comment]
Okay! I should do this for every icon, right?

Side note: wouldn't it be easier (and better) to add a check for duplicate icons in the main menu? This should only take a few lines of code, considering modern languages have built-in methods for removing duplicates in an array. It would also give the user the ability to search for the icon in the app by name.

Just my 5 cents though, if you consider your approach better, I will just change the names.

**Comment by Chefski** [comment]
Best thing here is make the icons for each app. I don't know Kotlin to make it not include duplicate links with different names. You can add a ` / ` between the names of you want like in Just Eat.

**Comment by ArtikusHG** [comment]
Here you go, I changed the icon names to be like the originals, as you requested.

**Pull request merged**
