### PR TITLE
Add i2pd

### PR DESCRIPTION
**Pull request by Sir-Photch**
# Description

https://github.com/PurpleI2P/i2pd-android

### Icons added
* App Name (`org.purplei2p.i2pd`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Review by Chefski — COMMENTED** [review]
I'm not sure if the icon is not a little too thin. Is there any other icon ideas that would be possible for this app? Did you check how it looks on the phone? If you could show a screenshot it'd be nice

**Comment by Sir-Photch** [comment]
Hm, I think you have a valid point there. I guess I could do "mask only". Would be a little generic then though don't you think? Let me know your thoughts. I will try to come up with something else in the meantime.

**Comment by x9136** [comment]
try

**Comment by Sir-Photch** [comment]
looks interesting, but I am not sure if variable length lines fit the contributing guidelines?

**Comment by x9136** [comment]
> but I am not sure if variable length lines fit the contributing guidelines?


Screenshot 2023-12-13 at 20 37 41
Technically, everything fits the guides.

**Comment by Sir-Photch** [comment]
I tried to be a little creative; I didn't want to give up the "structure" around the mask. What do you think? I admit this may not necessarily look like other lawnicons x) (but it does fit the guides, amirite?)

**Comment by x9136** [comment]
> What do you think?

The latter version and the one with just the mask are too different from the original. The reason is that the icon has a very expressive jester's cap.

Screenshot 2023-12-22 at 20 17 51
Stopping at this option, there are 2 comments to it. 1. Actually you made a square icon, so it should be smaller according to the guides. 2. In terms of quality, there are a lot of small spacing between strokes — it looks sloppy on the phone screen.

**Comment by Sir-Photch** [comment]
here goes another try

**Comment by x9136** [comment]
> here goes another try

Screenshot 2024-01-03 at 23 42 28
The only thing that remains is the wrong stroke thickness. I suggest using 10px.

**Comment by Sir-Photch** [comment]
right. I corrected that.

**Review by x9136 — APPROVED** [review]

**Pull request merged**
