### PR TITLE
Update Corona-Warn icon & add Geogebra Graphing Calc and Pons Translate

### PR DESCRIPTION
**Pull request by dercodeling**
## Description
I've created an outlined version of the Corona-Warn icon to replace the current filled one, according to the Lawnicons style, and added an icon for the Geogebra Graphing Calculator (Graphing Calc) and the Pons Translator/Dictionary.

image

The inner parts of corona-warn.svg look weird at 12px width, so I halved it to 6px, which closely resembles the original icon and looks a lot better.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Graphing Calc (`org.geogebra.android`)
* Pons Translate (`com.pons.onlinedictionary`)

### Icons updated
* Corona-Warn (`de.rki.coronawarnapp`)

### CODE REVIEW

**Comment by ZhmieXD** [comment]
Hi! I'm just about to make a new PR< and it seem to use a format now, where do I get it?

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing! I just have some minor changes I'd like to request for `pons_translate.svg`. The icon has goes down a bit at the top (check screenshot), mind fixing that? When you fix that you might just size it up to make sure it fits the 160x160px content area and centre it again as it was a bit off centre. Cheers
Screenshot 2022-09-24 at 22 17 14

**Comment by dercodeling** [comment]
@Chefski Did that

**Review by Chefski — APPROVED** [review]
Thanks for contributing! :)

**Comment by Chefski** [comment]
@Goooler

**Review by Goooler — APPROVED** [review]

**Pull request merged**
