### PR TITLE
Add icon for Pokémon TCG Live

### PR DESCRIPTION
**Pull request by service-paradis**
# Description

Add icon for Pokémon TCG Live (https://play.google.com/store/apps/details?id=com.pokemon.pokemontcgl&hl=en_US)

To keep things simple, I only kept a single card from the original icon (the right one). I think it is recognizable enough while keeping it minimal like the other icons in this package.

### Added
Pokémon TCG Live (`com.pokemon.pokemontcgl`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by x9136** [comment]
There is an unforced imbalance due to the difference in the stroke width of the card and the poke ball. To fix it, just widen the card a little and apply the 10px stroke to the poke ball.
Screenshot 2024-02-11 at 12 34 54

**Comment by service-paradis** [comment]
> There is an unforced imbalance due to the difference in the stroke width of the card and the poke ball. To fix it, just widen the card a little and apply the 10px stroke to the poke ball.

Something like this?

**Comment by x9136** [comment]
> Something like this?

Yes, except the stroke width is wrong.
Screenshot 2024-02-12 at 16 53 57

**Comment by service-paradis** [comment]
Yes, sorry, I saw it just after I commented! Should be better now!

**Pull request merged**
