### PR TITLE
Add Zepto, bigbasket and more 

### PR DESCRIPTION
**Pull request by naveenccmsd**
## Description

`com.bigbasket.mobileapp`
`com.tneb.tangedco`
`com.samsung.android.app.spage`
`com.zeptoconsumerapp`

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* `com.bigbasket.mobileapp`
* `com.tneb.tangedco`
* `com.samsung.android.app.spage`
* `com.zeptoconsumerapp`

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Thanks for the icons! Unfortunately `coindcx.svg` will have to be removed or changed as it does not match the Lawnicons style.

`flasher.svg` goes a bit out of the content area box. Mind fixing it? Rule of thumb is to just have the most outside shape with a 12px centred stroke height/width at 148px however it doesn't always apply to everything.

`free.svg` can be sized up to fit the 160x160px content area size.

<br>
<br>
<br>
For the future I'll also just ask to have the geometric points on whole coordinates or half. Check [here](https://github.com/LawnchairLauncher/lawnicons/pull/502#pullrequestreview-1033490033) for more information.

**Comment by naveenccmsd** [comment]
@Chefski sorry coindcx icons has pushed unintenially , I have removed it now. Also fixed the free.svg icon.

**Comment by lorrding** [comment]
> Rule of thumb is to just have the most outside shape with a 12px centred stroke height/width at 148px however it doesn't always apply to everything.


148px ? isn't it 144px ?

**Review by Chefski — APPROVED** [review]
Thanks

**Pull request merged**
