### PR TITLE
add icon firefox beta

### PR DESCRIPTION
**Pull request by arun54321**

### CODE REVIEW

**Comment by Gaziirafi** [comment]
Add Kiwi Browser,Youtube,Lighroom,google camera

**Comment by Gaziirafi** [comment]
Add kiwi browser icon also Google Camera Port version

**Comment by patrykmichalik** [comment]
Thanks for contributing, @arun54321! I’ve made some minor tweaks to the icons for consistency (see below). Does it work with you if I push a commit to your fork?

image
image

**Comment by arun54321** [comment]
Looks nice.

**Comment by patrykmichalik** [comment]
I removed the curved line to make the Firefox Beta icon consistent with [our icon for the stable version of Firefox](https://github.com/LawnchairLauncher/lawnicons/blob/master/svgs/firefox.svg). Now that you mention it, though, I like the idea of the curved line. I could keep it in the Firefox Beta icon and add it to the icon for the stable version of Firefox. How does that sound to you?

**Comment by arun54321** [comment]
Do whatever you like :) . I am not a expert. I don't mind.

**Comment by patrykmichalik** [comment]
I’ve kept the curved line in the Firefox Beta icon and added it to the icon for the stable version of Firefox. Thanks for your help!

**Comment by arun54321** [comment]
Thank you.

**Pull request merged**
