### PR TITLE
Add PixelDroid

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Adds PixelDroid

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Hmm... same problem as #507

**Comment by ThatOneCalculator** [comment]
Fixed!

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! Iʼd suggest ensuring that all key geometric points have whole coordinates. Please see [here](https://github.com/LawnchairLauncher/lawnicons/pull/502#pullrequestreview-1033490033) for more information.

**Comment by Chefski** [comment]
Can close as its been added in #677 
@Goooler

**Comment by Goooler** [comment]
Duplicate, thanks for yj

**Pull request closed without merging**
