### PR TITLE
Add Evoland & Bing

### PR DESCRIPTION
**Pull request by peterge1998**
## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Bing
* Evoland

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Could you just sort the links in alphabetical order and do the same in the future?

**Comment by peterge1998** [comment]
> Hey! Could you just sort the links in alphabetical order and do the same in the future?

Why do we not set up a ci job to do this automatically? I hate doing stuff manually that can be done via ci

**Comment by peterge1998** [comment]
> Hey! Could you just sort the links in alphabetical order and do the same in the future?

I dont know i I did the sorting correct. Please lets do it automatically

**Comment by Chefski** [comment]
If we can sort the links by name we will setup an Action. In the meantime please try sort manually. I find it annoying too but haven't found anything yet to sort by a specific value.

**Comment by peterge1998** [comment]
> If we can sort the links by name we will setup an Action. In the meantime please try sort manually. I find it annoying too but haven't found anything yet to sort by a specific value.

See my comment ;)

**Comment by peterge1998** [comment]
So whats the status of this MR @Chefski ?

**Comment by Chefski** [comment]
It's sorted by component instead of name which isn't what we want necessarily + there's conflicts

**Pull request closed without merging**
