### PR TITLE
Add Tinkoff, SOVA V RE icons

### PR DESCRIPTION
**Pull request by lazurit11**
Tinkoff is Russian bank; SOVA V RE is custom client for VK social network.

### CODE REVIEW

**Comment by lazurit11** [comment]
crop_Screenshot_20220213-181928_Lawnchair

**Comment by lazurit11** [comment]
Please ignore latter 3 commits, idk how to remove them

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! It would appear that this PR includes accidental edits to `.github/workflows/build_release_apk.yml`. Would you be able to remove these changes from the PR? The easiest way to do this is to copy the content of the [`build_release_apk.yml` file from the `develop` branch](https://raw.githubusercontent.com/LawnchairLauncher/lawnicons/develop/.github/workflows/build_release_apk.yml) into the equivalent file in your fork of Lawnicons and push a commit.

**Comment by lazurit11** [comment]
Okay, I will rebranch it later today. Thanks!

**Comment by lazurit11** [comment]
Will that be enough?

**Pull request merged**
