### PR TITLE
Add 7 icons, Update 1 and Link 1

### PR DESCRIPTION
**Pull request by projjalm**
## Description

This pull adds 7 new app icons including:
1. [GitNex](https://f-droid.org/en/packages/org.mian.gitnex) - A client for [Gitea](https://gitea.io/en-us/)/[Forgejo](https://forgejo.org/) services.
2. [Insular](https://f-droid.org/en/packages/com.oasisfeng.island.fdroid) - Libre fork of [Island](https://play.google.com/store/apps/details?id=com.oasisfeng.island) (an app which leverages Android's work profile feature to create an isolated space for better privacy) build for F-Droid.
3. [Mysplash](https://f-droid.org/en/packages/com.wangdaye.mysplash) - A client for the [Unsplash](https://unsplash.com) web service.
4. [neutriNote CE](https://f-droid.org/en/packages/com.appmindlab.nano) - Community edition of [neutriNote](https://play.google.com/store/apps/details?id=com.appmindlab.nano) (a powerful notes application) with no google dependencies.
5. [OctoDroid](https://play.google.com/store/apps/details?id=com.gh4a) - An open source client for GitHub.
6. [Pocket Paint](https://play.google.com/store/apps/details?id=org.catrobat.paintroid) - Paint app by [Catrobat](https://catrobat.org/).
7. [Vinyl](https://play.google.com/store/apps/details?id=com.poupa.vinylmusicplayer) - A music player forked from [Phonograph](https://github.com/kabouzeid/Phonograph) with pro features free for all users and additional ones.

and updates Cheogram icon and links [`com.bobek.compass`](https://play.google.com/store/apps/details?id=com.bobek.compass) to the generic compass icon.

Some interesting highlights on these icon files:
* Insular's icon has a perspective path effect applied to the depicted insulator's top design, which makes the strokes to get thinner from 12px as you go up. I hope that's ok.
* neutriNote's icon traces the outline of the "n" character in a sans-serif font as the original icon does, and adds a stroke of 8px to it. I avoided 12px just because it looks weird to me. But the merger can decide either. This is how they compare in usage:
compare-octodroid-stroke

## Type of change

:x: Bug fix
:white_check_mark: Icon addition
:x: General change

### Icons added
* GitNex (`org.mian.gitnex`)
* Insular (`com.oasisfeng.island.fdroid`)
* Mysplash (`com.wangdaye.mysplash`)
* neutriNote CE (`com.appmindlab.nano`)
* OctoDroid (`com.gh4a`)
* Pocket Paint (`org.catrobat.paintroid`)
* Vinyl (`com.poupa.vinylmusicplayer`)

### Icons updated
* Cheogram (`com.cheogram.android`)

### Icons linked
* Compass (linked `com.bobek.compass` to `@drawable/compass`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Icons look good! Could you just maybe put rounded corners and endpoints on `gitnex.svg` `insular.svg` and `pocket_paint.svg`. It would fit in better with the Lawnicons style.

By endpoints I mean like the parts where a path ends. Can't remember what they're called but I feel like its not endpoints
image

**Comment by projjalm** [comment]
Done.

_(Honestly, I forgot to do that for the sharped-cornered svgs when I rounded the corners and ends of neutriNote's icon, along with some other fixes as well. Therefore, Thanks for reminding :D )_

The most visible fix is increasing the number of diagonal strips on the insulator's top design in Insular's icon. If the [initial commit's svg](https://github.com/LawnchairLauncher/lawnicons/blob/3eaee490ea8e063d22877cf228c3183cd09246bb/svgs/insular.svg) seemed more appealing, you can request another change :)

Why I considered this one as a "fix" is simply because of its relevance to the original icon, which compare to the initial svg like this:
neutrinote-stroke-compare
While it may look good that the lines are more spaced out in it, but it looks too much of it for me. Therefore, I just simply preferred this commit instead. Would be great to read your comment on this.

**Review by Chefski — APPROVED** [review]
I'll go by what you prefer dude. I think both designs look good for insualar.

If you would prefer the one in the commit right now, let me know and I'll merge. If you want to use the other one, just change it and I'll merge :)

**Comment by projjalm** [comment]
> I'll go by what you prefer dude. I think both designs look good for insualar.
If you would prefer the one in the commit right now, let me know and I'll merge. If you want to use the other one, just change it and I'll merge :)

Great. I am preferring this commit then, merge it.

**Pull request merged**
