### PR TITLE
Adds Dolphin Emulator

### PR DESCRIPTION
**Pull request by il-av**
## Description

Adds the icon for Dolphin Emulator

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Dolphin Emulator (`com.dolphinemu.dolphinemu`)  - added from icon request form

### Icons linked
* App Name (linked `com.dolphinemu.dolphinemu` to `@drawable/dolphin_emulator`)

### CODE REVIEW

**Comment by il-av** [comment]
I have also now relinked some apps that were lost during the transition to an icon pack:

- Garmin Explore
- Garmin Messenger
- Bergfex
- Quick Calculation
- Termux Boot
- Termux Tasker
- Termux Widget
- Termux Float

**Review by Chefski — COMMENTED** [review]
Mind double checking the right svg has been uploaded? Seems like theres two paths one being very sharp.

**Comment by il-av** [comment]
The original icon has multiple colors so the 2 paths are just leftover from that. It didn't seem appropriate to differentiate or remove one of them so I left both filled
Dolphin-logo

**Comment by Chefski** [comment]
I think keeping just one path would be better as the stroke width remains at ≈ 12px. I would maybe just ask to round off the corners to match the style of Lawnicons and just centre it (Example in screenshot)
image

**Comment by il-av** [comment]
Ok. I can fix the positioning and remove the path.
Sorry for asking but I'm not sure how I'd round out an svg path. Can you please explain what you did in the sample image?

**Comment by Chefski** [comment]
I'm not sure which software you use but I can show how to do it in Figma and Illustrator. 

In Figma I just use the corner radius thing
image

In Illustrator I use the direct selection tool then just double click or drag the circles for corners.
image

If you would like I can make the change for this PR

**Review by Chefski — APPROVED** [review]

**Pull request merged**
