### PR TITLE
eternity icon: remake with better proportions and thingy in the ufo

### PR DESCRIPTION
**Pull request by benteg**
# Description

Remake of eternity icon (see #1502 )

### Icons updated
* Eternity (`eu.toldi.infinityforlemmy`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Comment by x9136** [comment]
The trouble with this icon is that it doesn't take the guides into account. That's why I couldn't get the character back right away when I tried to make it myself.

Screenshot 2023-10-28 at 01 49 03

**Comment by x9136** [comment]
Screenshot 2023-10-28 at 02 03 58
I think something like that would be great.

**Comment by benteg** [comment]
Ok, changed it to this:
image

**Comment by x9136** [comment]
> Ok, changed it to this:

Perhaps this icon corresponds to the guides. I don't know because I can only check *.svg.

**Comment by RaduBratan** [comment]
> Ok, changed it to this: image

I think you forgot to update your pull request with this new icon you just showed us.

**Review by x9136 — APPROVED** [review]
Let's accept it that way, but you may want to update the icon in the future because [I found it changed the other day](https://codeberg.org/Bazsalanszky/Eternity/releases).

**Pull request merged**
