### PR TITLE
Add Read You

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Add Read You.

Reference:

Icon:

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Fixed!

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! Unfortunately, this icon doesn’t appear to match the style of Lawnicons. This is due to the large filled area.

**Comment by ThatOneCalculator** [comment]
Yea, I'm not sure how I can change this one to still look good and be all lines. Any suggestions?

**Comment by votcher** [comment]
> Yea, I'm not sure how I can change this one to still look good and be all lines. Any suggestions?

Here is my suggestion based on your work:
read_you
Please feel free to use if you like it!
[read_you.zip](https://github.com/LawnchairLauncher/lawnicons/files/9077666/read_you.zip)

**Comment by patrykmichalik** [comment]
Thanks for your input, @votcher! This is precisely the approach I’d suggest.

**Review by Chefski — APPROVED** [review]
Thanks @votcher ! Applied your suggestion

**Pull request merged**
