### PR TITLE
+6 icons, +1 link

### PR DESCRIPTION
**Pull request by astolfogit**
# Description

Original icon            |  Adaptive icon
:-------------------------:|:-------------------------:
pid-192x192  |  russian_railways
  |  kuper
perek-192x192  |  perekrestok 1
MosMetro-v77-b12-signed-192x192  |  mosmetro
Okey_4 24 0 arm64-v8-144x144  |  okey
sberinvestments  |  sberinvestments
TorrServe_MatriX 134 Client-release-192x192  |  light_start

### Added

Russian Railways (`ru.rzd.pass`)
Купер (Kuper) (`ru.instamart`)
Перекресток (Perekrestok) (`ru.perekrestok.app`)
Moscow Wi-Fi autologin (`pw.thedrhax.mosmetro`)
О'КЕЙ (O'KEY) (`ru.reksoft.okey`)
СберИнвестиции (SberInvestments) (`ru.sberbank.investor`)

### Linked

TorrServe MatriX (`ru.yourok.torrserve` → `light_start.svg`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Review by I21b — CHANGES_REQUESTED** [review]
wrong comment

**Comment by astolfogit** [comment]
I personally think that a single filled grape that is a distinctive part of the company's logo can be considered a sparing use of fill. I might be wrong though..?

**Comment by astolfogit** [comment]
> Don't use fill, use thick stroke to draw a smaller circle

I'm sorry, but either this sentence lacks coherence. Could you please clarify your suggestion? As i understand it now - it is a fairly crude solution to a nonexistent problem.
I have removed this icon from the pr for the time being, let's see if anyone else is willing to have a say on this topic.

boxberry

**Review by x9136 — CHANGES_REQUESTED** [review]
Hey!

1. Some of the icons have the wrong size. 
2. In `appfilter.xml` the drawable of the Moscow Wi-Fi autologin icon are written incorrectly.
3. Most of the icons have areas where the lines are too close. It's worth thinking about how to do it differently. For example:
Screenshot 2024-08-31 at 18 56 38

**Comment by astolfogit** [comment]
Thanks for the dedication! Unfortunately i've just switched to lineageos and this project is no longer relevant for me, neither i have  any more time for introduce any corrections :( Hope someone will pick this pr up somewhere in the future

**Pull request closed without merging**
