### PR TITLE
Add Icon for Tubular

### PR DESCRIPTION
**Pull request by Glich440**
# Description

Add Icon for Tubular (https://github.com/polymorphicshade/Tubular)
A slight edit to the original newpipe logo of the icon pack to create an icon for tubular
### Added
Tubular (`org.polymorphicshade.tubular`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by Glich440** [comment]
I have considered removing the circle and making larger the triangles but decided to keep it like this to maintain consistency with other icons (such as the newpipe logo), if the maintainers think the other option may be better I'm open to change it.

**Comment by Glich440** [comment]
The modified version, it may need some minor tweaking to conform to guidelines
tubular

**Comment by Glich440** [comment]
tubular
It should conform with the guidelines now

**Comment by Glich440** [comment]
tubular
Current pull request version of the tubular logo
tubular
Modified version of the tubular logo
newpipe
Lawnicons version of the newpipe logo, the tubular logo is based on the newpipe logo.

**Comment by x9136** [comment]
Hey! 

If you want to keep the circle, then it is worth to reduce the density of the arrows by applying the 10px stroke.

I think the circle is unnecessary because it makes the icon less unique. I would keep the version with 2 arrows. 


Screenshot 2024-02-11 at 12 55 05

**Comment by Glich440** [comment]
I mainly put the circle just for consistency but I agree that the other one is more unique and readable, changing

**Comment by x9136** [comment]
Screenshot 2024-02-11 at 15 11 41

It remains to correct the stroke width and after that to refine the size.

**Comment by Glich440** [comment]
fixing

**Comment by x9136** [comment]
Screenshot 2024-02-11 at 15 31 01
It remains to refine [the size](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#canvas--sizes).

**Comment by Glich440** [comment]
I'm not sure why the checks are failing, cloning and building on my machine is working

**Comment by SuperDragonXD** [comment]
> I'm not sure why the checks are failing, cloning and building on my machine is working

This will be fixed by #1824. Sorry for this.

**Comment by Glich440** [comment]
> Screenshot 2024-02-11 at 15 31 01 It remains to refine [the size](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#canvas--sizes).

I have struggled a bit with inkscape and managed to get everything correct this time (I think), updating

**Review by x9136 — APPROVED** [review]

**Pull request merged**
