### PR TITLE
Added 42 icons, updated 3 icons, linked 5 icons

### PR DESCRIPTION
**Pull request by Nido-nid**
## Description

Added 42 icons, mostly from switzerland, open source apps or church related. Updated the mastodon app, because i wasn't happy with the current one, and two icons with bugs. Linked the /e/ Browser, Calendar and Camera app, as well as Threema Libre and Geometric Weather.

## Type of change

:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Actionbound (`de.actionbound`)
* Alertswiss (`ch.admin.babs.alertswiss`)
* AntennaPod (`de.danoeh.antennapod`)
* App Lounge (`foundation.e.apps`)
* Barinsta (`me.austinhuang.instagrabber`)
* Blockinger (`org.blockinger.game`)
* Book Reader (`com.github.axet.bookreader`)
* Carnet (`com.spisoft.quicknote`)
* ChurchTools (`tools.church.app`)
* Collabora Office (`com.collabora.libreoffice`)
* Covid Cert (`ch.admin.bag.covidcertificate.wallet`)
* DAVx5 (`at.bitfire.davdroid`)
* DeepL (`com.deepl.mobiletranslator`)
* Erste Hilfe (`com.cube.gdpc.che`)
* Letterboxd (`com.letterboxd.letterboxd`)
* Magic Earth (`com.generalmagic.magicearth`)
* MeteoSwiss (`ch.admin.meteoswiss`)
* Mini Metro (`nz.co.codepoint.minimetro`)
* Mozilla VPN (`org.mozilla.firefox.vpn`)
* myCloud (`com.swisscom.mycloud`)
* OpenFoodFacts (`openfoodfacts.github.scrachx.openfood`)
* OpenKeychain (`org.sufficientlysecure.keychain`)
* OpenTracks (`de.dennisguse.opentracks`)
* Patreon (`com.patreon.android`)
* PhotoTAN (`ch.raiffeisen.phototan`)
* Play Suisse (`ch.srgssr.playsuisse.tv`)
* Quizduel (`se.maginteractive.quizduel2`)
* Raiffeisen E-Banking (`ch.raiffeisen.android`)
* Raiffeisen TWINT (`ch.raiffeisen.twint`)
* Republik (`app.republik`)
* SBB Mobile (`ch.sbb.mobile.android.b2c`)
* ScreenCam (`com.orpheusdroid.screenrecorder`)
* Swisstopo (`ch.admin.swisstopo`)
* Tasks (`org.tasks`)
* Threema Libre (`ch.threema.app.libre`)
* TimeTree (`works.jubilee.timetree`)
* Tricount (`com.trilab.tricount.android`)
* one (`ch.viseca.visecaone`)
* VoteInfo (`ch.bk.voteinfo`)
* WordPress (`org.wordpress.android`)
* YouVersion (`com.sirma.mobile.bible.android`)
* Zapp (`de.christinecoenen.code.zapp`)

### Icons updated
* Mastodon (`org.joinmastodon.android`)
* OperaAPK (`com.dkanada.openapk`)
* WaifuPX(`dg.waifu.walls`)

### Icons linked
* Browser (linked `foundation.e.browser` to `@browser`)
* Calendar (linked `foundation.e.calendar` to `@calendar`)
* Camera (linked `foundation.e.camera` to `@camera`)
* Geometric Weather (linked `wangdaye.com.geometricweather` to `@weather`)
* Threema (linked `ch.threema.app` to `@threema`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
raiffeisen_e_banking doesnt have a straight line at the top

List of icons that new to be sized up:
- mastadon
- collabora_office
- covid_cert
- davx5
- erste_hilfe
- alert_swiss
- blockinger
- book_reader
- carnet
- church_tools
- meteo_swiss
- openfoodfacts
- phototan
- opentracks
- patreon
- playsuisse
- quizduel
- republik
- sbb_mobile
- screencam
- tasks
- swiss_topo
- vote_info
- wordpress
- waifiupx

Zapp has weird elements coming out of the bottom left and top right corner
image


You version can be sized up to 144x144px as its a square

For the future I'll ask to have leave icons as strokes (if possible) and keep all geometric points at full coordinates. (Check [here](https://github.com/LawnchairLauncher/lawnicons/pull/502#pullrequestreview-1033490033) for more information)

**Comment by Nido-nid** [comment]
With the latest commit, I resized all requested icons, some on top, who weren't maxed out either. Fixed the issue with the raiffeisen_e_banking icon. Its top line is not perfectly horizontal, but it being slightly rounded was false. Removed those weird bubbles at the zapp icon.
When I export the icons just as path, the icons don't get transferred correctly to a drawable in android app studio. Might be an issue with the program I use (Affinity Designer). For future contributions, I will place the major point on full coordinates.

**Comment by Nido-nid** [comment]
I fixed those issues. I never contributed to any GitHub project before, so I'm not used to it yet. If I understand it correctly, rebasing is editing my last commit or merging multiple ones. How do i do that?

**Review by Chefski — APPROVED** [review]
Thanks for making the changes :)

**Comment by Chefski** [comment]
> Fixed those issues. I never contributed to any GitHub project before, so I'm not used to it yet. If I understand it correctly, rebasing is editing my last commit or merging multiple ones. How do i do that?

At the bottom of this PR it asks to resolve conflicts. I did it for you. I suppose if you ever contribute again and another conflict appears, it will show at the bottom of the PR

**Pull request merged**
