### PR TITLE
Link deepl and threema apps

### PR DESCRIPTION
**Pull request by daywalk3r666**
## Description

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons linked
* DeepL (linked `com.jamal2367.deepl` to `@drawable/deepl`)
* DeepL (linked `com.example.deeplviewer` to `@drawable/deepl`)
* Threema (linked `ch.threema.app.hws` to `@drawable/threema`)
* Threema (linked `ch.threema.app.fdroid` to `@drawable/threema`)

### CODE REVIEW

**Comment by Goooler** [comment]
Seems these items need to be resorted.

**Comment by daywalk3r666** [comment]
Do you mean sort by package name?

**Comment by Goooler** [comment]
Yep

**Comment by daywalk3r666** [comment]
Ok edit the file

**Review by Goooler — APPROVED** [review]

**Pull request merged**
