### PR TITLE
Add icon for SiriusXM

### PR DESCRIPTION
**Pull request by service-paradis**
# Description

Add icon for SiriusXM (https://play.google.com/store/apps/details?id=com.siriusca&hl=en_US)

~They probably have other packages name (US version for example) that could be linked. I dont know how to find them though.~
I added activity from https://docs.google.com/spreadsheets/d/1AXc9EDXA6udZeGROtB5nuABjM33VluGY_V24tIzHaKc/edit?resourcekey#gid=507544179

### Icons added
* SiriusXM (`com.siriusca`)

## Contributor's checklist

- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Comment by x9136** [comment]
https://variety.com/2023/digital/news/siriusxm-unveils-streaming-app-logo-rebrand-1235784367/
https://blog.siriusxm.com/siriusxm-app-reimagined
As far as I can see, they were planning a rebranding this year and did it last week. They only had time to update the icon for some of their apps.

As a result, the icon you're proposing will be temporarily relevant for apps with old branding. So maybe when SiriusXM update the icon everywhere, it will be worth updating it here as well. Or use the new variant now.

**I would do the new version right away, but it makes sense to accept the old one for now. I'm offering you a choice.**

> They probably have other packages name (US version for example) that could be linked. I dont know how to find them though.

It's easiest to find packages by searching GitHub or installing all app variants from stores like APKPure or APKMirror. For SiriusXM, the second option is more suitable, but there is no need to rush and add all the packages right away.

**Comment by service-paradis** [comment]
Oh, I missed that!
I agree with you, it might be a better idea to use the new logo right away! I'm not sure how the outlined version will look, but I can give it a try!

**Comment by x9136** [comment]
> I just gave it a try, let me know if changes are needed!

This is an option that can be accepted.

Screenshot 2024-01-02 at 19 07 03
If you want, you can correct the spacing between the lines so that they don't stick together too much on small sizes.

**Comment by service-paradis** [comment]
I tried using inner outline with slight adjustment to spacing. Let me know what you think!

**Pull request merged**
