### PR TITLE
deprecate Obsidian icon

### PR DESCRIPTION
**Pull request by Mustang-ssc**
## Description

md.obsidian custom icon can be removed due to:
1. app logo re-design.
2. app includes their own themed icon which is overwritten by this custom icon.

This change reverts md.obsidian icon addition originally added from https://github.com/LawnchairLauncher/lawnicons/pull/734/commits/78bf188b5cf603380c735c8a33234f36dab4b216

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:heavy_check_mark: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

### Icons updated
* Obsidian (`md.obsidian`)

### CODE REVIEW

**Comment by Chefski** [comment]
I think the icon can stay until someone redesigns it. Better to have an icon for an app than not in my opinion

**Comment by Mustang-ssc** [comment]
> I think the icon can stay until someone redesigns it. Better to have an icon for an app than not in my opinion

I agree, however now the app includes its own adaptive icon unlike previously.

From my understanding this icon is overwriting the app's one which was recently themed by the dev.

The objective of this PR is to let this new adaptive icon plus it's new logo design be shown instead of the custom one.
On the other hand if this may negatively affect older android versions feel free to close it.

**Comment by RaduBratan** [comment]
I'm not a mod/admin/owner or anything, but here's my two cents. I believe the purpose of Lawnicons is to create an unified and consistent icon pack with it's own rules. If an app developer creates their own adaptive icon, that won't necessarily mean it will fit this icon pack, and it will break the consistent look.

Therefore, I would suggest to keep this icon until someone designs a new version (one created specifically to fit this icon pack).

**Comment by Chefski** [comment]
I'll be closing this PR. As stated by @RaduBratan, Lawnicons isn't meant to apps that don't yet have an adaptive icon. If I'm not wrong, many apps have adaptive icons but we still have an icon for them in Lawnicons. Thanks for your interest to contribute!

**Pull request closed without merging**
