### PR TITLE
Added Pixelfed, Tusky, and other icons

### PR DESCRIPTION
**Pull request by Casuallynoted**
## Description

Added icon for Pixelfed and Tusky.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Pixelfed (`com.pixelfed`) - added from icon request form
* Tusky (`com.keylesspalace.tusky`) - added from icon request form
* Hue (`com.philips.lighting.hue2`) - added from icon request form
* Parcel Pending (`com.parcelpendingmobile.app`) - added from icon request form
* TubeLab (`app.fedilab.tubelab`) - added from icon request form
* Etsy Seller (`com.etsy.butter.sell_on_etsy`) - added from icon request form
* Libretrack (`org.proninyaroslav.libretrack`) - added from icon request form
* Nextcloud Talk (`com.nextcloud.talk2`) - added from icon request form
* Floatplane (`com.floatplane.floatplane`) - added from icon request form
* Lovebox (`love.lovebox.loveboxapp`) - added from icon request form
* Nextcloud Photos (`com.nkming.nc_photos`) - added from icon request form
* PlayStation App (`com.scee.psxandroid`) - added from icon request form
* Tabs (`com.ultimateguitar.tabs`) - added from icon request form
* Nextcloud News (`de.luhmer.owncloudnewsreader`) - added from icon request form
* Fedilab (`app.fedilab.android`) - added from icon request form

### CODE REVIEW

**Comment by Casuallynoted** [comment]
This is my first pull request (and first attempt at an SVG icon), so please be easy on me! :)

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing. Unfortunately there'll have to be a few changes:

- `appfilter.xml` links should be in alphabetical order. I recommend using icontool.py. There's no guide for it yet but you can add an icon SVG and link like this:
```python3 icontool.py -s /path/to/icon.svg -c com.app.app/com.app.app.appActivity -n "App Name"```.
- The icon canvas is too large. It should be 192x192. Currently its 725x725 (or at least it is when exporting).
- Some icons could also have more rounded corners present. I'll show some example now with circle where it could be rounded
image
image
- `pixelfed.svg` has the correct canvas size however the icon doesn't fit the content area size and a little bit of the inside part seems to be sticking out.
image

I'll review more icons after all of them have the 192x192 content area size since some things may look a little different then.


Also mind me asking how the `tusky.svg` icon was made? There is 2 paths. Kinda inner and out. I've noticed many people do it. Do you draw 2 lines or is it exported like that? The problem with it is that although the stroke is set to 8, it will be a little thicker due to there being 2 lines beside each other with an approximate difference of 1px making it around 9px thickness.
image

**Comment by Casuallynoted** [comment]
> Hey! Thanks for contributing. Unfortunately there'll have to be a few changes:
> 
>     * `appfilter.xml` links should be in alphabetical order. I recommend using icontool.py. There's no guide for it yet but you can add an icon SVG and link like this:
>       `python3 icontool.py -s /path/to/icon.svg -c com.app.app/com.app.app.appActivity -n "App Name"`.
> 
>     * The icon canvas is too large. It should be 192x192. Currently its 725x725 (or at least it is when exporting).
> 
>     * Some icons could also have more rounded corners present. I'll show some example now with circle where it could be rounded
> 
> 
> image
> 
> image
> - `pixelfed.svg` has the correct canvas size however the icon doesn't fit the content area size and a little bit of the inside part seems to be sticking out.
> 
> image
> 
> I'll review more icons after all of them have the 192x192 content area size since some things may look a little different then.
> 
> Also mind me asking how the `tusky.svg` icon was made? There is 2 paths. Kinda inner and out. I've noticed many people do it. Do you draw 2 lines or is it exported like that? The problem with it is that although the stroke is set to 8, it will be a little thicker due to there being 2 lines beside each other with an approximate difference of 1px making it around 9px thickness. image

Hey there! Thank you so much for the feedback!

The sizing issue was due to inkscape- it defaults to mm instead of px so I had it set to 192 mm by accident! That's been fixed now :)

I also went through and smoothed out angles in each of the icons but let me know if there are any that can still be improved! I fixed the sizing on the Pixelfed icon as well, and the icontool was very very helpful!

For Tusky, I used the Inkscape edge trace feature, that seems to be what leaves the dual lines. I've gone ahead and fixed it manually :D

**Comment by Casuallynoted** [comment]
Made some additional corrections after going through them :)

**Review by Chefski — CHANGES_REQUESTED** [review]
Thanks for making the changes. Most icons look fine but they all are a bit smaller than the 160x160px content area size. So you'll need to size them up
image


image

`floatplane.svg`s icon seems a little wonky. Could you make it a perfect circle. Seems small but I can see it on the github preview too

Some corners/edges on libretack are a bit wonky too. Not sure how you made this but I would put guidelines where I would place a point and then just make the path and make the corners rounded. If the corners are not rounded enough, then I would round it manually with the round tool thing (not sure what the exact name for it is but I also use Illustrator so it could be called different)
image

`parcelpending.svg` and `tubelab.svg` still have the wrong canvas size.

### Two more things I should've mentioned previously
- Lawnicons only using two stroke sizes that shouldn't be change in width for each own path. In `tubelab.svg` I noticed that it kinda comes out and in sometimes. Though it is how the original icon looks, unfortunately it doesn't fit the lawnicons guidelines. If I'm not wrong, tubelab icon circle doesn't seem to be a perfect circle so maybe you could just have that?
- the `hue.svg` icon has a very thin stroke. It should be 8px or 12px. If you'd like a smaller stroke for the philips text you can use 6px. Try minimally rounded the corners for the philips text too.

Sorry for so many changes. Standards need to be kept the same or else the overall quality of icons will get worse...

**Comment by Casuallynoted** [comment]
> Thanks for making the changes. Most icons look fine but they all are a bit smaller than the 160x160px content area size. So you'll need to size them up image
> 
> image
> 
> `floatplane.svg`s icon seems a little wonky. Could you make it a perfect circle. Seems small but I can see it on the github preview too
> 
> Some corners/edges on libretack are a bit wonky too. Not sure how you made this but I would put guidelines where I would place a point and then just make the path and make the corners rounded. If the corners are not rounded enough, then I would round it manually with the round tool thing (not sure what the exact name for it is but I also use Illustrator so it could be called different) image
> 
> `parcelpending.svg` and `tubelab.svg` still have the wrong canvas size.
> ### Two more things I should've mentioned previously
> 
>     * Lawnicons only using two stroke sizes that shouldn't be change in width for each own path. In `tubelab.svg` I noticed that it kinda comes out and in sometimes. Though it is how the original icon looks, unfortunately it doesn't fit the lawnicons guidelines. If I'm not wrong, tubelab icon circle doesn't seem to be a perfect circle so maybe you could just have that?
> 
>     * the `hue.svg` icon has a very thin stroke. It should be 8px or 12px. If you'd like a smaller stroke for the philips text you can use 6px. Try minimally rounded the corners for the philips text too.
> 
> 
> Sorry for so many changes. Standards need to be kept the same or else the overall quality of icons will get worse...

That's ok!! It helps me get better :) Try these and see if they work better!

**Review by Chefski — CHANGES_REQUESTED** [review]
I fixed some icons up but theres some icons here that I just won't be able to fix up quickly. (Good rework on the `hue.svg` icon)

`pixelfed.svg` has a line that is wonky.
image

`parcel_pending.svg` stroke is too small... Not sure how to really change it to look good with 8px but maybe the squares can be smaller?

`libretrack.svg` is still a bit wobbly in some parts? I suppose I could do it myself when I have time if you think it may be too difficult.

**Comment by Casuallynoted** [comment]
> I fixed some icons up but theres some icons here that I just won't be able to fix up quickly. (Good rework on the `hue.svg` icon)
> 
> `pixelfed.svg` has a line that is wonky. image
> 
> `parcel_pending.svg` stroke is too small... Not sure how to really change it to look good with 8px but maybe the squares can be smaller?
> 
> `libretrack.svg` is still a bit wobbly in some parts? I suppose I could do it myself when I have time if you think it may be too difficult.

I think I got them this time! :) (And thank you, I figured the bulb works a lot better anyway XP)

**Comment by Casuallynoted** [comment]
Added two more icons but I think these ones should both be pretty good- they're fairly simple

**Review by Chefski — APPROVED** [review]
Thanks!

**Pull request merged**
