### PR TITLE
Add Cred 

### PR DESCRIPTION
**Pull request by naveenccmsd**
## Description

https://play.google.com/store/apps/details?id=com.dreamplug.androidapp
https://play.google.com/store/apps/details?id=com.simplemobiletools.clock
~~https://play.google.com/store/apps/details?id=com.google.android.calendar~~

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Cred (`com.dreamplug.androidapp`)
* Clock (`com.simplemobiletools.clock`)
* ~~calendar(`com.google.android.calendar`)~~

### Icons linked
* Samsung  Clock (`com.sec.android.app.clockpackage`) 
* ~~Samsung  Calendar(`com.samsung.android.calendar`)~~
* Dominos (`com.Dominos`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Nice one! Mind deleting the calendar icon (as well as the drawable and the links) as we already have a calendar icon built into Lawnchair 12

**Comment by naveenccmsd** [comment]
> Nice one! Mind deleting the calendar icon (as well as the drawable and the links) as we already have a calendar icon built into Lawnchair 12

@Chefski can you help me how to link it

**Comment by naveenccmsd** [comment]
@Chefski removed calendar icon

**Review by Chefski — APPROVED** [review]

**Comment by Chefski** [comment]
@Goooler

**Review by Goooler — APPROVED** [review]

**Pull request merged**
