### PR TITLE
Add icon for openScale

### PR DESCRIPTION
**Pull request by Sir-Photch**
## Description

I noticed that the icon for openScale is missing from lawnicons. I tried to come up with a svg. I hope that it fits the requirements.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`com.health.openscale`)

### Icons linked
* App Name (linked `com.health.openscale` to `@drawable/openscale`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! The circle does not seem to be perfectly round and the exporting seems to be a bit a strange. Did you export it with a height and width of 192x192?

Could you make the circle round?

**Comment by Sir-Photch** [comment]
The width and height should now be properly set to 192x192.
I also adjusted the circle. Let me know if there is anything else

**Review by Chefski — CHANGES_REQUESTED** [review]
Thanks for fixing the width and height. Unfortunately there are a few changes needed:

- The circle is still not perfectly round
- The icon goes outside the 160x160px content area size. It needs to be made a bit smaller
- The shape inside does not join with the other lines which leaves a gap between both lines

image

Could you also round this line?
image

**Comment by Sir-Photch** [comment]
Here goes my third attempt

**Review by Chefski — CHANGES_REQUESTED** [review]
Cool. Last two things I think. Not sure if I only noticed it now but the strokes have an opacity of 99.8% instead of 100%. Also the circle doesnt have a stroke of 12px.

**Comment by Sir-Photch** [comment]
I double checked about the stroke width now. By chance, do you know if using Inkscape and exporting it as an "optimized" svg causes issues?

**Review by Chefski — APPROVED** [review]
Looks good. Thanks

**Comment by Chefski** [comment]
I don't know if Inkscape has any issues. Used it maybe once so I basically have no experience with it

**Pull request merged**
