### PR TITLE
Added 13 icons

### PR DESCRIPTION
**Pull request by thismoon**
## Description

Added 13 new icons

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Aliucord Installer (`com.aliucord.installer`)
* Coffee (`com.github.muellerma.coffee`)
* Download Navi (`com.tachibana.downloader`)
* Droid-ify (`com.looker.droidify`)
* FFUpdater (`de.marmaro.krt.ffupdater`)
* ibisPaint X (`jp.ne.ibis.ibispaintx.app`)
* Icon Pack Studio (`ginlemon.iconpackstudio`)
* PixaPencil (`com.therealbluepandabear.pixapencil`)
* Raindrop (`io.raindrop.raindropio`)
* Screenshot Tile (`com.github.cvzi.screenshottile`)
* Simple QR (`com.tomfong.simpleqr`)
* The Battle Cats (`jp.co.ponos.battlecatsen`)
* Xtra (`com.github.andreyasadchy.xtra`)

before: 
lawniconsdisabled
after:
lawniconsenabled

### CODE REVIEW

**Comment by thismoon** [comment]
I forgor to add something to the droidify icon 🗿 gonna add it

**Comment by thismoon** [comment]
screenshot:
droidify fix

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Nice additions. Unfortunately all the icons are still either smaller or bigger than the 160x160 content area. Mind sizing them up?

**Comment by thismoon** [comment]
hello @Chefski, thanks for reviewing. I resized the droidify icon to the 160x160 content area while keeping the 12px width and centering it, is it good now and i should do this to the other icons too?

**Comment by Chefski** [comment]
> should do this to the other icons too?

Yes please. The new droidify icon looks good!

**Comment by thismoon** [comment]
i resized all the icons to 160x160 (had to recreate/modify ones)
here's how it looks:
icons
is everything good now?

**Review by Chefski — COMMENTED** [review]
Thanks for resizing them. Mind just changing `tile_noroot.svg` to be 144x144 instead of 160x160. Completely my fault for not specifying, sorry about that. Once you change that, the PR looks ready to be merged!

**Comment by thismoon** [comment]
screenshot tile

**Review by Chefski — APPROVED** [review]
Thanks!

**Comment by Chefski** [comment]
@Goooler

**Review by Goooler — APPROVED** [review]

**Pull request merged**
