### PR TITLE
Added 1 new icon!

### PR DESCRIPTION
**Pull request by Markellas**
## Description

Hi there! It's my first time adding icons to Lawnicons, so I'm very excited of contributing this great project!

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Yandex (`ru.yandex.searchplugin`)

### CODE REVIEW

**Comment by SuperDragonXD** [comment]
Thanks for your interest in contributing! For each new icon, an XML file and an SVG file should be added. This is described in [`CONTRIBUTING.md`](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md). However, it would appear that no SVG file is included in this pull request.

**Comment by Markellas** [comment]
Okay, I'll add it! Thanks for understanding

**Review by SuperDragonXD — APPROVED** [review]
Thanks for adding the file! Will merge the PR.

**Comment by Markellas** [comment]
Thanks for merging! I'm very excited about this project

**Pull request merged**
