### PR TITLE
Add icon for FluffyChat

### PR DESCRIPTION
**Pull request by Sir-Photch**
## Description

https://fluffychat.im/

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`chat.fluffy.fluffychat`)

* App Name (linked `chat.fluffy.fluffychat` to `@drawable/fluffychat`)

### CODE REVIEW

**Review by Chefski — APPROVED** [review]

**Comment by Sir-Photch** [comment]
Hm, seems like the fluffyness is lost:



I designed it to be a dotted like, at least for the circle. Any ide why that is not applied? @Chefski

**Comment by Chefski** [comment]
When I was reviewing I noticed it looked different than what GitHub was showing but thought it was a problem from my end. Something was wrong with the SVG code I think and it just got rendered wrong. I'll check out the SVG later and see if I can do a quick fix.

**Comment by Chefski** [comment]
Did you use some kind of pattern that was made based on the path? Or was each circle separate? You could convert the circles in to shapes which wouldn't be ideal for editing in the future but would fix the problem (or at least usually does for me).

**Comment by Sir-Photch** [comment]
I started with a circle, using a dotted path. Then, I converted the circle to a path, to split the path at the ears and on the bottom left.

**Comment by Chefski** [comment]
That might've been the problem. Try make another one and then you can zip it up and link here in the comments

**Comment by Sir-Photch** [comment]
fluffychat

Here you go. Seems to have uploaded the .svg correctly

**Comment by Chefski** [comment]
Yeah the icon looks good now. Did you do anything differently?

I'll change it now

**Comment by Sir-Photch** [comment]
I did the dots differently according to some sketchy youtube tutorial. If I understand correctly, the dots are now circles, or "objects on their own".

**Pull request merged**
