### PR TITLE
+3 icons

### PR DESCRIPTION
**Pull request by elisenlebkuch**
# Description
Added 3 icons and one link
### Added
Open Note (com.yangdai.opennote/com.yangdai.opennote.MainActivity)
LineageOS Music (org.lineageos.twelve/org.lineageos.twelve.MainActivity)
Revenge Manager (app.revenge.manager/app.revenge.manager.ui.activity.MainActivity)

Added link for OpenEUICC (im.angry.openeuicc/im.angry.openeuicc.ui.PrivilegedMainActivity)

### CODE REVIEW

**Comment by x9136** [comment]
Most icons have the wrong size, there are other inconsistencies with the Lawnicons style, but most importantly, you need to improve the quality.

**Comment by elisenlebkuch** [comment]
Better now?

**Comment by x9136** [comment]
Hey!

`open_note.svg`, `revenge_manager.svg` and `twelve.svg` are suitable icons. You can leave only them in the PR if you want me to merge it immediately, since working on other icons requires more time and attention.

The rest of the icons have quality issues and several other inconsistencies with the Lawnicons guidelines. The **github-actions** bot wrote more about the quality.

**Comment by x9136** [comment]
You haven't fixed the conflicts. It's easier for me to do this through a new PR. #2459 

Thanks!

**Pull request closed without merging**
