### PR TITLE
make sparkassen icons look the same

### PR DESCRIPTION
**Pull request by peterge1998**
This looks best. Its copied from sparkasse and resized. Inkscape reports a strange stroke width, i am not sure if its 8 px

### CODE REVIEW

**Comment by daywalk3r666** [comment]
Screenshot_20230105-172057_Trebuchet
It seems something is wrong

**Comment by peterge1998** [comment]
It looks fine inside the files changed tab

**Comment by peterge1998** [comment]
> Screenshot_20230105-172057_Trebuchet It seems something is wrong

image

**Comment by Chefski** [comment]
image

The XML looks as intended. Are you looking at the SVGs? I think its fine as the "files changed" shows it properly

**Review by Chefski — APPROVED** [review]

**Pull request merged**
