### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by Steccah**
## Description

Added 8 icons

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Curve (`com.imaginecurve.curve.prd/com.imaginecurve.curve.main.MainActivity`)
* N26 (`de.number26.android/com.n26.home.presentation.HomeActivity`)
* Hype (`it.hype.app/it.hype.app.ui.main.MainActivity`)
* PosteID (`posteitaliane.posteapp.appposteid/posteitaliane.posteapp.appposteid.home.HomeAc`)
* Subito (`it.subito/it.subito.main.impl.MainActivity`)
* Together Price (`com.togetherprice/com.togetherprice.MainActivity`)
* Trenitalia (`com.lynxspa.prontotreno/com.ibm.android.states.main.MainActivity`)
* Uniwhere (`lu.gian.uniwhere/lu.gian.uniwhere.features.home.ui.HomeActivity`)

### CODE REVIEW

**Comment by Steccah** [comment]
They seem small compared to the others, but i had to make them 144*144, or am i wrong?

**Review by Chefski — CHANGES_REQUESTED** [review]
All the icons can be 160x160 as none of them have a square shape. Most of them are currently smaller than 144x144px. You can change the size to 160x160px for all the icons

Could you fix this make this curve a little more smooth if possible? I think it may also be sharp in the top left corner (Might be fine, can't remember)
image

The curve logo could also be rounded a little more as it looks a bit off with one of the lines being straight.
image
 Thanks

**Comment by Steccah** [comment]
i should have fixed everything

**Comment by Steccah** [comment]
photo_2023-02-19_17-55-04
Hype icon has something wrong, but i don't know why

**Review by Chefski — APPROVED** [review]

**Comment by Chefski** [comment]
> photo_2023-02-19_17-55-04 Hype icon has something wrong, but i don't know why

Does it look like this on the homescreen as well? Try the new APK as well

**Comment by Steccah** [comment]
Latest apk is ok

**Pull request merged**
