### PR TITLE
add 4 icons

### PR DESCRIPTION
**Pull request by peterge1998**
## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
de.eplus.mappecc.client.android.alditalk
de.peterge.combined
de.comdirect.app
de.cloneapps.crypto_prices
co.appreactor.news

### CODE REVIEW

**Comment by peterge1998** [comment]
How should I do the name for these 2 fdroid icons? They are called "Nachrichten" and "Krypto Preise" instead of "News" and "Crypto Prices" in english. I just left name= on the default english name.

```
<icon drawable="@drawable/crypto_prices" package="de.cloneapps.crypto_prices" name="Crypto Prices" />
<icon drawable="@drawable/news" package="co.appreactor.news" name="News" />

**Comment by peterge1998** [comment]
Please check comdirect and Aldi Talk icons. I guess they are not correct, because they are smaller than 160x160?

**Review by Chefski — CHANGES_REQUESTED** [review]
Hiya! Thanks for the new icons. I've got small changes to 3 icons.

Increase content area size to 160x160px for:
- `crypto_prices.svg`

Decrease content area size to 160x160px for:
- `combined.svg`

<br>
<br>
The shapes inside `news.svg` are too big. Could you reduce the height to be 12px?
image

Thanks

**Comment by Chefski** [comment]
> How should I do the name for these 2 fdroid icons? They are called "Nachrichten" and "Krypto Preise" in german instead of "News" and "Crypto Prices" in english.

You can add a `/` after the English name. Just Eat also has multiple different names in each country. Feel free to look at it. So in that case the links would look like this:
`<icon drawable="@drawable/crypto_prices" package="de.cloneapps.crypto_prices" name="Crypto Prices / Krypto Preise" />
<icon drawable="@drawable/news" package="co.appreactor.news" name="News / Nachrichten" />`

**Comment by peterge1998** [comment]
> Hiya! Thanks for the new icons. I've got small changes to 3 icons.

Done :)

**Comment by peterge1998** [comment]
> You can add a `/` after the English name. Just Eat also has multiple different names in each country. Feel free to look at it. So in that case the links would look like this: `<icon drawable="@drawable/crypto_prices" package="de.cloneapps.crypto_prices" name="Crypto Prices / Krypto Preise" /> <icon drawable="@drawable/news" package="co.appreactor.news" name="News / Nachrichten" />`

Just Eat has many names, five languages total. Here German is the third. Where is the order specified for the name it actually takes? I guess it looks for the phone's language, right?
`<icon drawable="@drawable/just_eat" package="com.justeat.app.ie" name="Just Eat / Pyszne.pl / Lieferando.de / Takeaway.com / Thuisbezorgd.nl" />`

**Review by Chefski — APPROVED** [review]
Thank you

**Comment by Chefski** [comment]
@peterge1998 it can be any order. Doesn't matter what order it is in but English first is preferred. The name is used for searching for an icon in the app. If you make a the same package link but different name, the icon will appear twice in app.

**Pull request merged**
