### PR TITLE
Add 4 icons

### PR DESCRIPTION
**Pull request by peterge1998**
## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* BeReal
* Tabletop Tools
* imgur
* waistline

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
`bereal.svg` does not have whole numbers for it's strokes. Could you change it to 8px (I'll try make different guidelines for letters). If you dont like the look of it in 8px, you can maybe use the favicon on [bere.al](https://bere.al/en).

`imgur.svg` could use 12px. Was the decision to use 8px to make it closer to the original icon?

**Comment by peterge1998** [comment]
> `bereal.svg` does not have whole numbers for it's strokes. Could you change it to 8px (I'll try make different guidelines for letters). If you dont like the look of it in 8px, you can maybe use the favicon on [bere.al](https://bere.al/en).

What do you mean with using the favicon? Just B.?
The line numbers are fucked up because it looks like shit otherwise. In the a I need like two width for this font...
 
> `imgur.svg` could use 12px. Was the decision to use 8px to make it closer to the original icon?

Done

**Comment by Chefski** [comment]
> What do you mean with using the favicon? Just B.? The line numbers are fucked up because it looks like shit otherwise. In the a I need like two width transitioning to each other for this font...

Would a stroke of 6px work better? Do you think it would be suitable as a global stroke width for all text?

**Comment by peterge1998** [comment]
> Would a stroke of 6px work better? Do you think it would be suitable as a global stroke width for all text?

I prefer B. ...

**Comment by Chefski** [comment]
Sure! You can make the B.

**Comment by peterge1998** [comment]
> Sure! You can make the B.

Done :)

**Review by Chefski — APPROVED** [review]
Thanks

**Pull request merged**
