### PR TITLE
Add icon for Etar

### PR DESCRIPTION
**Pull request by h3x-code**
## Description

New Etar icon added. Designed from scratch.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Etar (`ws.xsoh.etar`)

### Icons linked
* Etar Lineageos (linked `org.lineageos.etar` to `@drawable/etar_calendar`)

### CODE REVIEW

**Comment by daywalk3r666** [comment]
Calendar icons now are stored in lawnchair launcher

**Comment by h3x-code** [comment]
So how can I apply it to my calendar icon ?
Is there a list of apps stored into the launcher ?
Thanks

**Comment by daywalk3r666** [comment]
Use the last lawnchair action build
https://github.com/LawnchairLauncher/lawnchair/actions/runs/3820749138

**Comment by Chefski** [comment]
Closing for the reason mentioned by @daywalk3r666

**Pull request closed without merging**
