### PR TITLE
Added AdAway, Aegis, AntennaPod icons

### PR DESCRIPTION
**Pull request by elea11**

### CODE REVIEW

**Comment by arun54321** [comment]
image

Aegis icon is not symmetric.

**Comment by elea11** [comment]
> image
> 
> Aegis icon is not symmetric.

Indeed will review and amend accordingly. Thanks for your extra pair of eyes.

**Comment by elea11** [comment]
Will push a new PR

**Comment by arun54321** [comment]
I have asked aegis developers for svg and they have provided it.

**Comment by elea11** [comment]
Good. Thx. Having trouble to properly using GitHub anyway...

**Pull request closed without merging**
