### PR TITLE
Add icon for Twire

### PR DESCRIPTION
**Pull request by ASTRELION**
## Description

Added icon for [Twire](https://github.com/twireapp/Twire).

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Twire (`com.perflyst.twire`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Icon looks good however it was filled. I suggest these changes: [twire.zip](https://github.com/LawnchairLauncher/lawnicons/files/9574344/twire.zip). You're free to implement your own changes too

**Comment by ASTRELION** [comment]
I like that suggestion, I went ahead and updated it

**Review by Chefski — APPROVED** [review]
Looks good :)
Just update the `twire.xml` on this icon too

**Comment by ASTRELION** [comment]
When I go to update `twire.xml`, the preview now looks like this:
image
Any idea why and/or how to fix it? I tried re-exporting the svg and replacing the file but it looks the same.

**Comment by Chefski** [comment]
Not sure what's happening there. I don't seem to have this issue with the icon I linked
image
Are you using the `twire.zip` I linked or your own version of the icon?

**Comment by ASTRELION** [comment]
I was using the same `twire.svg` that was in the previous commit. I also tweaked the svg slightly and tried again, same thing. Maybe just a quirk with android studio, I'm not sure.

**Comment by ASTRELION** [comment]
This is the vector it generates, not sure if its just the preview or the vector itself that is incorrect
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="192dp"
    android:height="192dp"
    android:viewportWidth="50.8"
    android:viewportHeight="50.8">
  <path
      android:pathData="m25.423,5.825c-10.773,0 -19.598,9.497 -19.598,20.955C13.679,21.274 20.143,7.778 31.626,14.339a14.028,14.097 90,0 1,3.99 3.576,13.054 13.119,90 0,1 2.53,6.196c1.553,-1.083 5.014,-3.642 5.338,-5.582 0.197,-1.167 -0.851,-2.607 -1.434,-3.539A19.88,19.979 90,0 0,25.423 5.825ZM25.423,20.567a6.003,6.033 90,0 0,-1.205 0.116c-6.227,1.196 -4.051,10.852 2.075,9.833 6.219,-1.035 4.857,-9.907 -0.878,-9.949zM44.976,24.122C37.163,29.598 30.285,43.472 18.882,36.297A14.11,14.18 90,0 1,15.227 32.967c-1.415,-1.826 -2.109,-3.97 -2.575,-6.196 -1.529,1.059 -5.054,3.668 -5.338,5.606 -0.173,1.128 0.936,2.647 1.503,3.539a19.34,19.436 90,0 0,7.98 7.115C30.838,49.6 44.968,38.724 44.968,24.114Z"
      android:strokeLineJoin="round"
      android:strokeWidth="12"
      android:fillColor="#00000000"
      android:strokeColor="#000"
      android:strokeLineCap="round"/>
</vector>
```

**Comment by Chefski** [comment]
Handy dandy stackoverflow showed me how to preview the icons. If you right click on the icon and then choose "Open in right split" it'll show the code with the preview on the right side
image

**Comment by ASTRELION** [comment]
Yeah, I've been using that too, and it also shows the same big black blob. Other svgs preview fine, so maybe something going on with `twire.svg` for some reason

**Comment by Chefski** [comment]
Yea... Not sure honestly why that happens. Maybe you can make the icon again or I'll just PR it

**Comment by ASTRELION** [comment]
Hopefully fixed it. I ended up just creating a new svg file with the same content and for some reason that worked.

**Review by Goooler — APPROVED** [review]

**Pull request merged**
