### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by Autines**
## Description

add new icons include ithome, cloudmusic,minimap,saltmusic,bilibili,tiktok,dingtalk,hwmarket,wemeet,purelive,qqmusic,qqmail,qqtim,alicloud,iqiyi,jingdong,meituan,taobao,qqlive,didi

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* ithome (`com.ruanmei.ithome`) 
* cloudmusic (`com.netease.cloudmusic`)
* minimap (`com.autonavi.minimap`)
* saltmusic (`com.salt.music`)
* bilibili (`com.bilibili.app.in`)
* dingtalk (`com.alibaba.android.rimet`)
* hwmarket (`com.huawei.appmarket`)
* wemeet (`com.tencent.wemeet.app`)
* purelive (`com.mystyle.purelive`)
* qqmusic (`com.tencent.qqmusic`)
* qqmail (`com.tencent.androidqqmail`)
* qqtim (`com.tencent.tim`)
* alicloud (`com.alicloud.databox`)
* iqiyi (`com.qiyi.video`)
* jingdong (`com.jingdong.app.mall`)
* meituan (`com.sankuai.meituan`)
* taobao (`com.taobao.taobao`)
* qqlive (`com.tencent.qqlive`)
* didi (`com.sdu.didi.psnger`)

### Icons linked
* tiktok (linked `com.ss.android.ugc.aweme` to `@drawable/package`)

### CODE REVIEW

**Review by Chefski — COMMENTED** [review]
Hey! Just before I start reviewing I want to mention that drawable vectors no longer need to be added. You can delete them. Along that we no longer add links to `grayscale_icon_map.xml`.

Make sure to read the [new updated guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md) if you're not familiar with them yet.

**Comment by Autines** [comment]
> 

yeah, I know new updated guidelines. Nextime I will delete them and then create a new pull request inclouding some new icons.

**Review by Chefski — CHANGES_REQUESTED** [review]
Many icons here will need changes as they don't meet the Lawnicons guidelines. For examples `alivloud` uses fill and the line is thciker than 12px. 

`appchecker` also does not meet guidelines as although the stroke is 12, it makes one wide line as there's no gap. The corners are also not rounded and the icon does not fit the 160x160 content area.

`caifu` has the right size and rounded corners but the line is too thick and the mountain shaped object should use a stroke not fill.

Overall many of the icons (if not all) will need changes. Make sure the endpoint for paths is rounded too. Alongside the icon changes please also sort the links in alphabetical order as we don't have automatic sorting yet.

The exporting seems to have wrong settings too. Each time I import into Figma the icon is hidden behind a mask. I'm not sure if it'll display properly on phone. You can check this using the debug APK.
image

Thank you

**Comment by Autines** [comment]
ok, but I am a little busy recently. I will try to change them. By the way, I have tried debug apk and all icons display properly on my phone.

**Pull request closed without merging**
