### PR TITLE
Adding icons for pyypl and ininal

### PR DESCRIPTION
**Pull request by EnchantedGoldenApple**
# Description
Added icon for pyypl (```com.pyypl```)
and for ininal (```com.ininal.wallet```)

# Contributor's checklist

✅  I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
✅ I have ensured that Lawnicons builds correctly
✅ I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Comment by EnchantedGoldenApple** [comment]
I am contributing first time, and something went wrong. Help

**Comment by x9136** [comment]
> I am contributing first time, and something went wrong. Help

Everything is ok, except that the icons are made without considering [Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#contributing-icons).

**Comment by EnchantedGoldenApple** [comment]
The size is 144×144. And lines are 12px. Which parameter do I need to change.

**Comment by x9136** [comment]
> The size is 144×144. And lines are 12px. Which parameter do I need to change?

Screenshot 2023-12-09 at 21 35 44
Both icons are made with a fill, and you need a stroke. As you can see, the size of the icons is also far which is needed.

Screenshot 2023-12-09 at 21 38 03
I enlarged your icons for an example of what size they should be.

**Comment by KTibow** [comment]
image

**Comment by x9136** [comment]
@KTibow If you pay attention to the example, it's actually done incorrectly, so it's easy to think that the square is a conditional shape rather than a literal square.

I've already mentioned this problem somewhere — there is no clear explanation in the guides what is considered a square: a literal square or a shape that forms a square but has gaps. Given the reviews I've gotten and that I've done myself, it's almost always meant a square without gaps.

**Comment by KTibow** [comment]
Yeah I know, I was trying to clarify that the 144 size only applies if you have a square on the outside

**Pull request closed without merging**
