### PR TITLE
Add microsoft remote desktop icon

### PR DESCRIPTION
**Pull request by fikimaul**
Add microsoft remote destop icon

### CODE REVIEW

**Comment by fikimaul** [comment]
> Thanks for your interest in contributing! It would appear that the two arrows in the icon are slightly rotated (see image). Would you be able to correct this?
> 
> image

Okay, i will correct ASAP. 👍

**Comment by fikimaul** [comment]
Hi, @patrykmichalik , i have correct the icon. 

Thanks

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Cheers! One last thing: the coordinates of some of the anchor points appear to be unnecessarily complex. I’d suggest updating the path like so: [`microsoft_remote_desktop.zip`](https://github.com/LawnchairLauncher/lawnicons/files/8837538/microsoft_remote_desktop.zip).

**Comment by fikimaul** [comment]
Thanks for suggesting, i have already updated the icon.

**Comment by patrykmichalik** [comment]
Cheers!

**Review by patrykmichalik — APPROVED** [review]

**Pull request merged**
