### PR TITLE
Add icon for Kvaesitso

### PR DESCRIPTION
**Pull request by Sir-Photch**
## Description

Adding icon for Launcher [Kvaesitso](https://github.com/MM2-0/Kvaesitso).

Also:
I have fixed the name-tag for OpenMensa. Is this somehow influencing, if the icon gets applied? Currently, it is not applied. (But the name is also wrong.) If this is activity related, how can I find out every activity of an app?

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Kvaesitso (`de.mm20.launcher2.release`)

### CODE REVIEW

**Comment by Chefski** [comment]
You can find the activity name for apps by using and adb command or 3rd party apps like IconRequest or Icon Pusher. You can read more about this in [the guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#how-to-find-the-package-and-activity-name-of-your-app).

I like to use [Icon Pusher](https://play.google.com/store/apps/details?id=dev.southpaw.iconpusher&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) since it just lets me send all apps activity name and then I can easily copy and paste it into the code from the [website](https://iconpusher.com/).

**Review by Chefski — APPROVED** [review]
The link is correct. It's showing the icon on my device. The name will be used to let the icon be searched in app.

(I'll be approving this however I won't be merging till the next Lawnicons release)

**Comment by Sir-Photch** [comment]
> (I'll be approving this however I won't be merging till the next Lawnicons release)

Why is that, or when is the next release?

**Comment by Chefski** [comment]
@Sir-Photch soon

**Pull request merged**
