### PR TITLE
Add LibreTube

### LINKED ISSUE #569: Icon Request - LibreTube
Hi,

Can you make an icon for LiberTube?

Thanks in advance,
Bye

### PR DESCRIPTION
**Pull request by Bnyro**
Added the LibreTube icon, I'd love to see it included in lawnicons :)

closes #569

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
To fit with the style of the other icons, I think you should use a stroke instead of a fill :)

image

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! It would appear that the size of `libretube.svg` is 1280 by 1280 pixels. However, for Lawnicons, we use an artboard size of 192 by 192 pixels (see [`CONTRIBUTING.md`](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md)). I would suggest resizing `libretube.svg` accordingly.

**Comment by Bnyro** [comment]
Alright, thanks for your feedback. I resized it now as suggested.

**Comment by Bnyro** [comment]
Whoops, sorry for rerequesting your review.

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Cheers for applying the changes, and no worries about the duplicate review request. As a final request, I’d suggest these minor geometric tweaks: [`libretube.zip`](https://github.com/LawnchairLauncher/lawnicons/files/9062670/libretube.zip).

**Comment by Bnyro** [comment]
Applied your suggested SVG, I agree that the geometry looks more balance now.
I bet you would be faster by force pushing your changes instead of always requesting them.
Thank you for all your work, I really appreciate your help :)

**Comment by patrykmichalik** [comment]
Cheers for applying the edits! While it would certainly speed things up if I applied my suggestions directly, I prefer to allow the author of the pull request to evaluate the suggestions and express their thoughts on them. Design is in large part a subjective matter, so I’m open to discussing ideas. Thanks for contributing!

**Review by patrykmichalik — APPROVED** [review]

**Pull request merged**
