### PR TITLE
Add Clipto, Xodo, Flud, QuickEdit

### PR DESCRIPTION
**Pull request by Chefski**
## Description
Add requested icons from list

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Clipto (`com.wb.clipboard.pro`)
* Xodo (`com.xodo.pdf.reader`)
* Flud (`com.delphicoder.flud`)
* Flud (Ad Free) (`com.delphicoder.flud.paid`)
* QuickEdit Text Editor (`com.rhmsoft.edit`)
* QuickEdit Text Editor Pro (`com.rhmsoft.edit.pro`)

### CODE REVIEW

**Comment by Chefski** [comment]
I'm open to any suggestion to change the QuickEdit icon. I have kept the rectangle in fill as I've seen other icons (e.g. Google Classroom) use squares bigger than 12px or not using a stroke.

**Comment by Goooler** [comment]
```
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile resource file: /home/runner/work/lawnicons/lawnicons/app/src/main/res/xml/grayscale_icon_map.xml: . Cause: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[139,5]
     Message: Element type "icon" must be followed by either attribute specifications, ">" or "/>".). Check logs for more details.
```

**Review by Goooler — APPROVED** [review]

**Comment by Goooler** [comment]
```
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile resource file: /home/runner/work/lawnicons/lawnicons/app/src/main/res/xml/grayscale_icon_map.xml: . Cause: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[655,94]
     Message: The entity name must immediately follow the '&' in the entity reference.). Check logs for more details.
```

**Review by SuperDragonXD — APPROVED** [review]
Thanks for the PR! The icons look good to me. As for the QuickEdit icon, having a small inconsistency from the normal icon guidelines is okay.

**Pull request merged**
