### PR TITLE
Add Mull Icon

### PR DESCRIPTION
**Pull request by pickleRick1313**

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! There appear to be some minor geometric errors in the icon (see image). Would you be able to correct these? Cheers! 

2022-02-06-100944_395x503_scrot png-mh

**Comment by pickleRick1313** [comment]
> Thanks for your interest in contributing! There appear to be some minor geometric errors in the icon (see image). Would you be able to correct these? Cheers!
> 
> 2022-02-06-100944_395x503_scrot png-mh

Hello I have updated my branch. I hope this is all correct now.

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
One last thing: would you be able to resize the icon such that the circle on which the globe is based is exactly 20 by 20 px? It is currently slightly larger:

2022-02-10-221646_659x748_scrot

**Comment by patrykmichalik** [comment]
Thanks, @pickleRick1313!

**Pull request merged**
