### PR TITLE
Add credit_mutuel

### PR DESCRIPTION
**Pull request by lorrding**
preview:
lawnicons_credit_mutuel
base logo:
unnamed

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! There appears to be a tiny gap in the center of the icon. Iʼd suggest correcting this.

image

**Comment by lorrding** [comment]
Sorry for the long delay, it should be fixed now 😅

**Review by Chefski — CHANGES_REQUESTED** [review]
Thanks for fixing it, the icons seems to be bigger than the 160x160px content area. Mind fixing that? :)

**Comment by lorrding** [comment]
Hi sorry again for the late fix 😅
I've edited the svg to fit the 160px size! Only thing I can't understand is when exporting to a drawable xml, it change the stroke size to 11.17px ? It may be due to the fact that I'm using a transform matrix to resize the svg 🤷‍♂️

**Review by Chefski — APPROVED** [review]
Thanks for making the changes. I fixed the stroke being 11.17

**Pull request merged**
