### PR TITLE
Add icon for Alipay

### PR DESCRIPTION
**Pull request by Uni-Rider**
## Description

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`com.eg.android.AlipayGphone`) 

### Icons linked
* App Name (linked `com.eg.android.AlipayGphone` to `@drawable/alipay`)

### CODE REVIEW

**Review by Chefski — APPROVED** [review]

**Comment by Uni-Rider** [comment]
@Chefski Sorry, the icon seems not displayed correctly in debug.apk

**Comment by Chefski** [comment]
@Uni-Rider you can make another PR with the fixed XML

**Comment by Uni-Rider** [comment]
> @Uni-Rider you can make another PR with the fixed XML

Actually I don't use android studio because I can't find the function of converting svg to xml, I don't know why. So I still use some online code, but it sometimes works, sometime doesn't

**Comment by Chefski** [comment]
No problem, I'll fix it now. After I update it, check if its fixed as I don't have an Android with me now

**Comment by Uni-Rider** [comment]
> No problem, I'll fix it now. After I update it, check if its fixed as I don't have an Android with me now

Thank you, it is correct now

**Pull request merged**
