### PR TITLE
Add several icons

### PR DESCRIPTION
**Pull request by RaduBratan**
## Description
I added icons for some of my installed apps that haven't received the Lawnicons treatment yet.

## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

### Icons added
* Journal (`com.intelligentchange.fiveminutejournal`)
* BambooHR (`com.mokinetworks.bamboohr`)
* TV Remote Control (`remote.control.tv.universal.forall.roku`)
* SystemUI Tuner (`SystemUI Tuner`)
* Garanti BBVA (`com.garanti.cepsubesi`)
* Garanti BBVA Romania (`com.garantibank.cepsubesiro`)

### CODE REVIEW

**Comment by RaduBratan** [comment]
Let me know if I should change the icons of [Journal](https://play.google.com/store/apps/details?id=com.intelligentchange.fiveminutejournal&hl=en&gl=US) and/or [TV Remote Control](https://play.google.com/store/apps/details?id=remote.control.tv.universal.forall.roku). Both of them have strokes way thinner than 12px.

**Review by Grabstertv — CHANGES_REQUESTED** [review]
> Let me know if I should change the icons of [Journal](https://play.google.com/store/apps/details?id=com.intelligentchange.fiveminutejournal&hl=en&gl=US) and/or [TV Remote Control](https://play.google.com/store/apps/details?id=remote.control.tv.universal.forall.roku). Both of them have strokes way thinner than 12px.

Yes, we have specific guidelines for what stroke widths are allowed and when to use them. Please refer to our [contribution](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md) page for more information.

**Comment by Goooler** [comment]
@SuperDragonXD Can we enable "squash commit" only in settings?

**Comment by SuperDragonXD** [comment]
Sorry for the late response, but enabled it in settings.

**Pull request merged**
