### PR TITLE
Added 3 New Icons

### PR DESCRIPTION
**Pull request by sujoybyte**
# Description

### Added
Nykaa (`com.fsn.nykaa`)
Nykaa Fashion (`com.fsn.nds`)
Nykaa Man (`com.fsn.nykaa.man`)

### Linked
Nykaa (`com.fsn.nykaa` → `nykaa.svg`)
Nykaa Fashion (`com.fsn.nds` → `nykaa_fashion.svg`)
Nykaa Man (`com.fsn.nykaa.man` → `nykaa_man.svg`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by sujoybyte** [comment]
Hi, does anyone know why `first-interaction / check_pr (pull_request)` check is failing ?

**Comment by x9136** [comment]
Screenshot 2024-02-27 at 19 31 58

All icons have the wrong size. Optionally, you can create N of 3 lines instead of the current option.

> Hi, does anyone know why first-interaction / check_pr (pull_request) check is failing ?

It's broken, you can ignore it.

**Comment by sujoybyte** [comment]
Hi @x9136 
I fit all the icons to 160px. Earlier I thought the icon size should not cross 160 x 160 (154 x 154 if square type) and stay inside. Btw I tried N of 3 lines but I felt there are similar kinds and that doesn't go well with Nykaa brand asthetic.

**Comment by x9136** [comment]
>  Earlier I thought the icon size should not cross 160 x 160 (154 x 154 if square type) and stay inside.

So the words in the guideline aren't precise enough. Here's an option:
`Most icons must fit the 160×160px content area size, but squares must fit the 154×154px content area size.`

Do you think this wording more accurately describes what size is needed, or is it also a bit confusing? How would you describe the size requirements for yourself?

**Comment by sujoybyte** [comment]
> Do you think this wording more accurately describes what size is needed, or is it also a bit confusing?

I feel it's well written only and just an error from my side understanding it. 

> How would you describe the size requirements for yourself?

Just in case an example icon showing that we should not go less then 160x160px or 154x154px might be clearer to some people.

**Pull request merged**
