### PR TITLE
Add Catima

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Adds Catima

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Inkscape for drawing and https://shapeshifter.design for clean-up and conversion.

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! Iʼd suggest ensuring that all key geometric points have whole coordinates. Please see [here](https://github.com/LawnchairLauncher/lawnicons/pull/502#pullrequestreview-1033490033) for more information.

**Review by Chefski — APPROVED** [review]
Fixed points. Thanks for making the icon

**Comment by lorrding** [comment]
You're even fixing old PRs of other now 🥲 thanks for your hard work

**Pull request merged**
