### PR TITLE
Add & Update Icons

### PR DESCRIPTION
**Pull request by leifniem**
added: 

- AdAway
- DHL
- Enpass
- Feedly
- Figma
- Geometric Weather
- GrubHub
- Loop Habit Tracker
- Notion
- Obsidian
- SeriesGuide
- Sparkasse
- Thenx

updated:

- Mega
- Infinity for Reddit

### CODE REVIEW

**Comment by leifniem** [comment]
The updated icons weren't up to the specs in the contribution guide, i took the liberty to make more fitting versions.

**Comment by patrykmichalik** [comment]
Hello, and thanks for your interest in contributing! What would be your thoughts on using rounded stroke caps for `thenx.svg`? Since the icons in Lawnicons generally use such stroke caps, I’d say this would make `thenx.svg` match the remaining icons better.

**Comment by Chefski** [comment]
Hi @leifniem , could you increase the icon size to fit the 160x160px content area (apart from thenx as I've already updated it)? There's some icons here that would be great additions!

**Review by Chefski — CHANGES_REQUESTED** [review]
Hi @leifniem , could you increase the icon size to fit the 160x160px content area (apart from thenx as I've already updated it)? There's some icons here that would be great additions!

**Comment by leifniem** [comment]
Sorry this has been sitting idle for so long, i kinda lost track of this PR.

Sorry for getting my metrics wrong on the other icons, seems i misaligned my guides, i'll see if i can fix those, apparently i converted my outlines and saved the file 💀

**Comment by Chefski** [comment]
No worries. Happy to see that the icons won't be abandoned and left unfixed. Thanks for trying to fix them :)

**Pull request closed without merging**
