### PR TITLE
Add paytm icon

### PR DESCRIPTION
**Pull request by naveenccmsd**
## Description
Added icon for [Paytm](https://play.google.com/store/apps/details?id=net.one97.paytm).

Fixes #(issue) 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Paytm (`net.one97.paytm`)

### CODE REVIEW

**Comment by naveenccmsd** [comment]
Is Stoke insted of Fill is applicable for Text as well?

**Comment by ZhmieXD** [comment]
> Is Stoke insted of Fill is applicable for Text as well?

Yes, I use stroke for text on my submitted icons all the time

**Review by Chefski — APPROVED** [review]
Thanks for contributing :D

**Comment by Chefski** [comment]
@Goooler

**Pull request merged**
