### PR TITLE
Add plex

### PR DESCRIPTION
**Pull request by lorrding**
lawnicons_plex

### CODE REVIEW

**Comment by lorrding** [comment]
Fixes #552

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! Iʼd suggest making the gaps highlighted in the image at least 8 px wide. This way, the gap width would better match the stroke width. Additionally, thin gaps, when viewed at small sizes, can be mistaken for artifacts. Another option would be to extend the two smaller shapes such that there are no gaps at all.

image

**Comment by lorrding** [comment]
Hi, another late fix! I've made the gaps larger tell me if it's still not large enough :)

**Review by Chefski — APPROVED** [review]
Looks good! Thanks for making the change! :D

**Pull request merged**
