### PR TITLE
Add 1dm, 1dm+, messaging and mobile legends icon

### PR DESCRIPTION
**Pull request by thunderkex**

### CODE REVIEW

**Comment by arun54321** [comment]
You could you simple and sharper mobile legends android vector.

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#000"
        android:pathData="M5.03,3 L12.598,3 C14.276,3,14.678,3.402,15.392,4.106 L19.774,8.447 C20.528,9.191,21,9.663,21,11.392 L21,18.839 L18.065,15.925 L18.065,9.06 L15.462,6.487 L11.995,9.925 Z M19.352,21 L15.372,17.05 L15.372,10.347 L11.995,13.704 L8.618,10.347 L8.618,17.603 L5.935,14.94 L5.935,7.683 L3,4.77 L3,12.609 C3,14.338,3.472,14.8,4.226,15.554 L8.608,19.895 C9.322,20.598,9.724,21,11.402,21 L12.397,21 Z M7.14,21 L3,16.89 L3,21 Z M16.848,3 L21,7.11 L21,3 Z" />
</vector>

```

**Comment by thunderkex** [comment]
done changed

**Comment by arun54321** [comment]
[mobile legends.zip](https://github.com/LawnchairLauncher/lawnicons/files/7696938/mobile.legends.zip)
I've made few edits. It should look even more sharper and have smaller file size.

**Comment by thunderkex** [comment]
> [mobile legends.zip](https://github.com/LawnchairLauncher/lawnicons/files/7696938/mobile.legends.zip) I've made few edits. It should look even more sharper and have smaller file size.

done changed sir thanks

**Comment by arun54321** [comment]
https://github.com/LawnchairLauncher/lawnicons/issues/76

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! Unfortunately, there appear to be geometric faults in `1dm.svg` and `1dm_plus.svg`. Please see the image below for an example. Additionally, as of commit d891025d332843ff98915bfe229d0097ee19e795, Lawnicons already includes an icon for system messaging apps. Previously, this icon was included in Lawnchair. I’d suggest merging the latest changes from `LawnchairLauncher:master` into `thunderkex:master` and linking the `com.android.messaging` package to `@drawable/messages`.

image

**Comment by thunderkex** [comment]
> Thanks for your interest in contributing! Unfortunately, there appear to be geometric faults in `1dm.svg` and `1dm_plus.svg`. Please see the image below for an example. Additionally, as of commit [d891025](https://github.com/LawnchairLauncher/lawnicons/commit/d891025d332843ff98915bfe229d0097ee19e795), Lawnicons already includes an icon for system messaging apps. Previously, this icon was included in Lawnchair. I’d suggest merging the latest changes from `LawnchairLauncher:master` into `thunderkex:master` and linking the `com.android.messaging` package to `@drawable/messages`.
> 
> image

im done to make some change, thanks you sir

**Pull request closed without merging**
