### PR TITLE
 Add: Aurora Droid, Blokada, KDE Connect and 9 others...

### PR DESCRIPTION
**Pull request by bmFtZQ**
I added icons for:

- Aurora Store
- Blokada
- Designer Tools
- Doodle
- Galaxy Store
- Hex Installer
- KDE Connect
- MIDI Player
- miniSweeper
- Privacy Dashboard
- Samsung Notes
- Sennheiser Smart Control

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for your interest in contributing! I would suggest these minor tweaks related to sizing and alignment: [`suggestions.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7980720/suggestions.zip).

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks a bunch for updating the icons to match the new style! Just two small things. In the KDE Connect icon, the KDE logo is somewhat inconsistent with the outlined style. There is rather little room here, so you could consider replacing it with just a _K_. For the Sennheiser Smart Control icon, I would suggest outlining the shape inside the rectangle so as to avoid creating large filled areas.

**Comment by bmFtZQ** [comment]
I didn't do those tweaks initially because I though they looked weird/less recognisable but now I notice they definitely stick out when next to other icons.

**Review by patrykmichalik — APPROVED** [review]

**Comment by patrykmichalik** [comment]
Thanks for contributing, @bmFtZQ!

**Pull request merged**
