### PR TITLE
Add and link some icons on coloros

### PR DESCRIPTION
**Pull request by AngelaCooljx**
## Description

Add & link icons

## Type of change

✔️ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)

### Icons added
* 5G Tile (`moe.xzr.fivegtile`) 
* Aijiasu (`com.fvcorp.android.aijiasuclient`)
* Amap (`com.autonavi.minimap`)
* AliyunDrive (`com.alicloud.databox`)
* AndFTP (`lysesoft.andftp`)
* AnHui 10000 (`com.wondertek.ahPalm10000`)
* App Market (`com.heytap.market`)
* Baidu IME (`com.baidu.input`)
* Baidu NetDisk (`com.baidu.netdisk`)
* bilibili (`tv.danmaku.bili`)
* bilibili (`com.bilibili.app.in`)
* Breeno (`com.heytap.speechassist`)
* Chaoxing (`com.chaoxing.mobile`)
* Clash (`com.github.kr328.clash`)
* Clone Phone (`com.coloros.backuprestore`)
* HeyTap Cloud (`com.heytap.cloud`)
* HeyTap Music (`com.heytap.music`)
* My OnePlus (`com.heytap.vip`)
* OPPO Store (`com.oppo.store`)
* Phone Manager (`com.coloros.phonemanager`)
* Taobao (`com.taobao.taobao`)
* Videos (`com.heytap.yoli`)
* Zhihu (`com.zhihu.android`)

### Icons linked
* Browser (linked `com.heytap.browser` to `@drawable/browser`)
* Calculator (linked `com.coloros.calculator` to `@drawable/calculator`)
* Calendar (linked `com.coloros.calendar` to `@drawable/calendar`)
* Clock (linked `com.coloros.alarmclock` to `@drawable/clock`)
* Compass (linked `com.coloros.compass2` to `@drawable/compass`)
* Files (linked `com.coloros.filemanager` to `@drawable/files`)
* Notes (linked `com.coloros.note` to `@drawable/notes`)
* Recorder (linked `com.coloros.soundrecorder` to `@drawable/recorder`)
* Theme Store (linked `com.heytap.themestore` to `@drawable/themes`)
* Wallet(linked `com.finshell.wallet` to `@drawable/wallet`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing! Icons look great but some changes need to be made:

`ahpalm_10000.svg` goes outside the content area. Could you make it smaller?
image

A number of icons are not fit to size of the content area. Could you look at them all and make sure they fit the content area?
image

`andftp.svg` has a bit of a bumpy corner on the left side. Could you fix it?
image

`chaoxing.svg` has a bumpy corner in the bottom left. Mind fixing it?
image

`clash.svg` the minimum a stroke can go is 6px. The mouth is unfortunately 3px. Could you change it? 

`clone_phone.svg` can have a content area of 160x160 as its not exactly a square. Same can be done for other icons that are 144x144 as they are not squares. (The ones I remember are `zhihu.svg`, app_market.svg)

`tabao.svg` has an endpoint that is a bit sharp. Could you make it rounded?
image

`videos.svg` does not have a black colour. Please make it black
image

**Comment by AngelaCooljx** [comment]
Thank you very much for your corrections, I will correct them one by one

**Comment by AngelaCooljx** [comment]
### Icons fixed
- AnHui 10000 (com.wondertek.ahPalm10000)
- Aijiasu (com.fvcorp.android.aijiasuclient)
- AndFTP (lysesoft.andftp)
- App Market (com.heytap.market)
- Chaoxing (com.chaoxing.mobile)
- Clash (com.github.kr328.clash)
- Clone Phone (com.coloros.backuprestore)
- Taobao (com.taobao.taobao)
- Videos (com.heytap.yoli)
- Zhihu (com.zhihu.android)

### Icons added
- Bank of China (com.chinamworld.bocmbci)
- DSU Sideloader (vegabobo.dsusideloader)
- ele.me (me.ele)
- ICBC (com.icbc)
- JD (com.jingdong.app.mall)
- Kernel Flasher (com.github.capntrips.kernelflasher)
- Meituan Waimai (com.sankuai.meituan.takeoutnew)
- Remote Desktop Manager (com.devolutions.remotedesktopmanager)
- Share (com.hengye.share)
- Tailscale (com.tailscale.ipn)
- WakeUp Schedule (com.suda.yzune.wakeupschedule)
- WiFi Moho (com.ruijie.wifim)
- WiFi Moho (cn.com.ruijie.magicbox)

**Review by Chefski — COMMENTED** [review]
Icons look amazing! I guess I just have 1 very small changes

Could the right ear on `meituan_wamai.svg` be more smooth? I feel like it could be a little more smooth
image

Other than that great job on all these icons and thank you :D

**Comment by AngelaCooljx** [comment]
### Icons fixed
- Meituan Waimai (`com.sankuai.meituan.takeoutnew`)

### Icons added
- Cainiao (`com.cainiao.wireless`)
- DataBackup (`com.xayah.databackup`)
- Devcheck (`flar2.devcheck`)
- DNA-Android (`com.dna.tools`)
- e-CNY (`cn.gov.pbc.dcep`)
- Fake Location (`com.lerist.fakelocation`)
- Fenbi (`com.fenbi.android.servant`)
- GIF Helper (`com.didikee.gifparser`)
- Guotai (`com.guotai.dazhihui`)
- Huawei Health (`com.huawei.health`)
- Shortcut Creator (`com.x7890.shortcutcreator`)
- Umetrip (`com.umetrip.android.msky.app`)

**Review by Chefski — APPROVED** [review]
Thank you! :)

**Comment by Chefski** [comment]
Could you just resolve conflicts and I'll merge

**Comment by AngelaCooljx** [comment]
`  <item component="ComponentInfo{in.startv.hotstar/com.hotstar.MainActivity}" drawable="hotstar" name="Disney+ Hotstar" />
`
Done, but #1177 This line may have been lost in the last merge #1176

**Comment by AngelaCooljx** [comment]
### Icons redesigned
- Cainiao (`com.cainiao.wireless`)
- Umetrip (`com.umetrip.android.msky.app`)

### Icons added
- LibChecker (`com.absinthe.libchecker`)
- Litiaotiao (`hello.litiaotiao.app`)
- Magic iPerf (`com.nextdoordeveloper.miperf.miperf`)
- MemoryDetector (`io.github.huskydg.memorydetector`)
- Mirai Plugin for Parabox (`com.ojhdtapp.miraipluginforparabox`)
- MyAndroidTools (`cn.wq.myandroidtools`)
- NetEase Music (`com.netease.cloudmusic`)
- NP Manager (`com.wn.app.np`)
- Parabox (`com.ojhdtapp.parabox`)
- Quark (`com.quark.browser`)

**Comment by Chefski** [comment]
Ok wow the conflicts are gone crazy... Yeah I guess you can correct those

**Comment by AngelaCooljx** [comment]
Just marked as resolved

**Comment by AngelaCooljx** [comment]
These commits got messed up due to conflicts, I think it would be clearer to reopen a pull request #1180 and close the current PR

**Comment by Chefski** [comment]
Yeah we can close this one

**Pull request closed without merging**
