### PR TITLE
Add icon for Wallcandy

### PR DESCRIPTION
**Pull request by khaled-0**
## Description
Add icon for Wallcandy
https://play.google.com/store/apps/details?id=in.wallpaper.wallpapers
Reference icon used from the app
12px stroke is applied over the fill

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Wallcandy(`in.wallpaper.wallpapers`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Could you change `wallcandy.svg` to have a size of 192x192px?

**Comment by khaled-0** [comment]
may I know what are the uses for svgs in the svg folder?

**Review by Chefski — CHANGES_REQUESTED** [review]
image
The icon goes outside the 160x160px content area size. Could you reduce the size? Mind if I ask why the icon also has 2 paths?

**Comment by Chefski** [comment]
> may I know what are the uses for svgs in the svg folder?
> 
> 

It's used to easily make changes to an icon if needed instead of making the icon from scratch

**Comment by Chefski** [comment]
I have just made the icon in the preferred way which makes it easier to edit. Feel free to check it out

**Pull request merged**
