### PR TITLE
Add bing, payback &evoland, link onvista

### PR DESCRIPTION
**Pull request by peterge1998**
Should be sorted correctly :)
I used `cat appfilter.xml | sort -t '"' -k 4 > appfilter_tmp.xml`

### CODE REVIEW

**Comment by Stabiron** [comment]
Hey did you cross check after sorting?

Everything seems to be out of order now.

These are just some examples from your xml.

Screenshot 2023-03-06 102933
Screenshot 2023-03-06 103008
Screenshot 2023-03-06 103042
Screenshot 2023-03-06 103158
Screenshot 2023-03-06 103247

**Comment by peterge1998** [comment]
We want to sort it by the name instead of the drawable, correct? Need to take 6th instead of 4th field, thats why two-zero... is nect to twitter...

**Comment by Stabiron** [comment]
Correct! sort by name tag instead of drawable.

**Comment by Stabiron** [comment]
> Done :) 
`cat appfilter.xml | sort -t '"' -k 6 > appfilter_tmp.xml`

Perfect!

**Review by Chefski — APPROVED** [review]

**Pull request merged**
