### PR TITLE
[PR] +5 icons

### PR DESCRIPTION
**Pull request by I21b**
# Description

Added 2 icons, sorted `appfilter.xml`.

### Added

Rizline (`com.PigeonGames.Rizline`)<br>
rizlineoriginalmutate

律动轨迹 ~~ Rizline (`com.leiting.ldgj`)<br>
rizline_cnoriginal_cnmutate

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Review by I21b — COMMENTED** [review]
### Canvas and sizes
- [x] 1. Canvas: `192×192px`.
- [x] 2. Non-square icons: the long side of the icons should be `160px`.
   3. Square icons: `154×154px`.

### Color, stroke width and rounding
- [ ] 1. Color: black `#000`.
- [x] 2. No fill. Base stroke width: `12px`. `14px`, `10px`, `8px` — depending on the shape of the icons. `6px` — for fine details.
- [x] 3. Rounded ends and joins. 90° corners are rounded by `6-32px`.

### Naming
- [x] 1. Names should match the official app name and contain no additional text.
- [x] 2. If the first `3` characters of the app name contain letters not from the English alphabet, then add a localized (or transliterated) name via `~~`.
Example: `京东 ~~ JD`.
- [x] 3. The names of the drawables should repeat the names of the apps if nothing prevents it.

### Quality
- [x] 1. Ensure that icons are easily recognizable.
- [x] 2. Align icons to [the visual center](https://www.google.com/search?sca_esv=1fcec3f5e0b15e20&q=what+is+visual+center+of+an+icon&tbm=isch&source=lnms).
- [x] 3. Avoid noticable black spots by reducing the stroke width or simplifying the icons.
- [x] 4. Avoid close distances between strokes. The icons on the phone screen will be smaller, so the small distances between the strokes will stick together.
- [x] 5. Avoid drastic changes in stroke widths. When the strokes next to each other differ in width by 4px or more, the icon will look sloppy.

**Review by I21b — COMMENTED** [review]
### Canvas and sizes
- [x] 1. Canvas: `192×192px`.
- [x] 2. Non-square icons: the long side of the icons should be `160px`.
   3. Square icons: `154×154px`.

### Color, stroke width and rounding
- [x] 1. Color: black `#000`.
- [x] 2. No fill. Base stroke width: `12px`. `14px`, `10px`, `8px` — depending on the shape of the icons. `6px` — for fine details.
- [x] 3. Rounded ends and joins. 90° corners are rounded by `6-32px`.

### Naming
- [x] 1. Names should match the official app name and contain no additional text.
- [x] 2. If the first `3` characters of the app name contain letters not from the English alphabet, then add a localized (or transliterated) name via `~~`.
Example: `京东 ~~ JD`.
- [x] 3. The names of the drawables should repeat the names of the apps if nothing prevents it.

### Quality
- [x] 1. Ensure that icons are easily recognizable.
- [x] 2. Align icons to [the visual center](https://www.google.com/search?sca_esv=1fcec3f5e0b15e20&q=what+is+visual+center+of+an+icon&tbm=isch&source=lnms).
- [x] 3. Avoid noticable black spots by reducing the stroke width or simplifying the icons.
- [x] 4. Avoid close distances between strokes. The icons on the phone screen will be smaller, so the small distances between the strokes will stick together.
- [x] 5. Avoid drastic changes in stroke widths. When the strokes next to each other differ in width by 4px or more, the icon will look sloppy.

**Comment by I21b** [comment]
# Description


Added 1 icon.

## Icons addition information

### Added


Fandango (`com.fandango/com.fandango.material.activity.LaunchAdActivity`, `com.fandom.app/com.fandom.app.splash.SplashActivity`)<br>
fandangooriginalmutate
[from](https://github.com/LawnchairLauncher/lawnicons/pull/2133)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

**Comment by I21b** [comment]
# Description


Added 1 icon.

## Icons addition information

### Added


Fandango (`com.fandango/com.fandango.material.activity.LaunchAdActivity`, `com.fandom.app/com.fandom.app.splash.SplashActivity`)<br>
fandangooriginalmutate
[from](https://github.com/LawnchairLauncher/lawnicons/pull/2133)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

**Comment by x9136** [comment]
Let's sort out the mess a little bit and eliminate unnecessary work.

1.
> sorted appfilter.xml

It's not necessary. Moreover, there is no need to group applications by language in this file. There should be only those changes that relate to the added icons. For example, if you add 3 icons that have 3 links, then in `appfilter.xml` should be only 3 new lines.

2. The size of the icons. All icons are smaller than needed. They should be 160×160px. To figure out what size you need, I suggest you download some previously added icons and compare them with yours.

3. What you can save time on:
- it may be more convenient for you, but just in case: the checklist for self-review is made as a reminder. It does not need to be duplicated and filled in.
- the original icons are not needed if they can be found in Google. That is, they are almost always not needed.
- screenshots of the icons are not needed, because the icons are already in the pull request (PR).
- if you add a new icon or link to the PR, then it is enough to edit the description after that, rather than making a comment on each icon. You can see how previously accepted PRs are made.

I suggest fixing the size of the icons and the mess in `appfilter.xml`. Then I will say the rest of the comments specifically to some icons.

**Comment by I21b** [comment]
> Let's sort out the mess a little bit and eliminate unnecessary work.
> 
> 1.
> > sorted appfilter.xml
> 
> It's not necessary. Moreover, there is no need to group applications by language in this file. There should be only those changes that relate to the added icons. For example, if you add 3 icons that have 3 links, then in `appfilter.xml` should be only 3 new lines.
> 
> 2. The size of the icons. All icons are smaller than needed. They should be 160×160px (at least 1 direction should be 160px). To figure out what size you need, I suggest you download some previously added icons and compare them with yours.
> 
> 3. What you can save time on:
> 
> * it may be more convenient for you, but just in case: the checklist for self-review is made as a reminder. It does not need to be duplicated and filled in.
> * the original icons are not needed if they can be found in Google. That is, they are almost always not needed.
> * screenshots of the icons are not needed, because the icons are already in the pull request (PR).
> * if you add a new icon or link to the PR, then it is enough to edit the description after that, rather than making a comment on each icon. You can see how previously accepted PRs are made.
> 
> I suggest fixing the size of the icons and the mess in `appfilter.xml`. Then I will say the rest of the comments specifically to some icons.

160×160px and aligning the icon to the visual center will touch the safe zone between 192×192px, so I made it smaller.
How should I make it bigger?

**Comment by x9136** [comment]
> How should I make it bigger?

As usual. Size is more important than the visual center.

**Pull request closed without merging**
