### PR TITLE
Add some icons

### PR DESCRIPTION
**Pull request by s-liwka**
### Icons added
* Geometry Dash (`com.robtopx.geometryjump`) - added from (my own) icon request form 
* Wulkanowy (`io.github.wulkanowy`) - added from (my own) icon request form 
* Molly (`im.molly.app`) - added from (my own) icon request form 
* Calendar (`org.lineageos.etar`) - added from (my own) icon request form 
* Music (`org.lineageos.eleven`) - added from (my own) icon request form, copied and edited the apple music icon
* Nitter (`com.plexer0.nitter`) - added from (my own) icon request form 
* Spotiflyer (`com.shabinder.spotiflyer`) - added from (my own) icon request form 
* Permission Ruler (`com.stefanosiano.permissionruler`) - added from (my own) icon request form 
* Root Checker (`com.joerykrim.rootcheck`) - added from (my own) icon request form 

### Icons linked
* AccA (linked `mattecarra.accapp` to `@drawable/accubattery`)

### CODE REVIEW

**Review by Chefski — COMMENTED** [review]
Could you add the drawable files and remove the calendar icon? (calendar will now be part of the lawnchair dynamic icons in the next release)

**Comment by s-liwka** [comment]
done

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing. Got some changes:

- geometry_jump is not centred and is smaller than the 144x144 content area size. Could you centre and increase the size
- molly needs to be centred and also sized up. The icon also has some shapes which have an opacity that is not 100%. Could you also make the corners rounded instead of sharp?
- music needs to be centred and sized up
- nitter needs to be sized up and corners need to be rounded
- permission_ruler needs to be sized up & corners need to be rounded
- spotiflyer goes outside the content area size
- wulkanowy needs rounded corners and needs to be sized up

I'd also just ask to check if every line has a stroke of either 8px or 12px (not for example: 8.37 or 12.11)

**Comment by Chefski** [comment]
I'll be closing this PR as there has not been any activity since it was created. Thanks for contributing though

**Comment by s-liwka** [comment]
i forgor

**Comment by Chefski** [comment]
You can make re-open this PR or make a new one with the changes if you would like

**Pull request closed without merging**
