### PR TITLE
Add icon for MT Manager

### PR DESCRIPTION
**Pull request by Fldicoahkiin**
## Description

https://www.coolapk.com/apk/bin.mt.plus

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* MT Manager (`bin.mt.plus`) - added from icon request form
* MT Manager (`bin.mt.plus.canary`)

### Icons updated
* MT Manager (`bin.mt.plus`)
* MT Manager (`bin.mt.plus.canary`)

### Icons linked
* MT Manager (linked `bin.mt.plus` to `@drawable/mt_manager`)
* MT Manager (linked `bin.mt.plus.canary` to `@drawable/mt_manager`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! The icon has slight imperfections on the letters. The lines are not straight and theres parts at which the path comes out. Mind fixing it?
image

**Comment by Fldicoahkiin** [comment]
> Hey! The icon has slight imperfections on the letters. The lines are not straight and theres parts at which the path comes out. Mind fixing it?
> image
> 

ok i will try

**Comment by Fldicoahkiin** [comment]
@Chefski I have a question,can you help me,just like it describe: [Discord #help](https://discord.com/channels/803299970169700402/1064210309478367282)

**Comment by daywalk3r666** [comment]
A little hint. If you use the github app Pull. You must use a new branch for pull request. The app rebase your branch and your changes are gone

**Comment by Fldicoahkiin** [comment]
> A little hint. If you use the github app Pull. You must use a new branch for pull request. The app rebase your branch and your changes are gone

ok,thanks

**Comment by daywalk3r666** [comment]
https://user-images.githubusercontent.com/15938117/213521211-7ad6e72c-6754-45fa-a0e4-89fca7e8455b.mp4

@Fldicoahkiin hope this helps

**Pull request merged**
