### PR TITLE
Add 18 new icons

### PR DESCRIPTION
**Pull request by gabehowe**
## Description
Add icons for 18 new icons and rename dji_ronin.svg to dji.svg
link com.dji.ronin and dji.go.v5 to dji.svg

## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Alto's Odyssey (`com.noodlecake.altosodyssey`)
* Desmos (`com.desmos.calculator`)
* DroneDeploy (`com.dronedeploy.beta`)
* Feit Electric (`com.feit.smart`)
* First Citizen's Bank (`com.mcom.firstcitizens`)
* Forest (`cc.forestapp`)
* GPS Test (`com.chartcross.gpstest`)
* GuitarTuna (`com.ovelin.guitartuna`)
* Habitica (`com.habitrpg.android.habitica`)
* Hulu (`com.hulu.plus`)
* Kindle (`com.amazon.kindle`)
* LG ThinQ (`com.lgeha.nuts`)
* Google Live Transcribe (`com.google.audio.hearing.visualization.accessibility.scribe`)
* myQ (`com.chamberlain.android.liftmaster.myq`)
* Real Piano (`com.bilkon.easypiano`)
* Tempest (`com.weatherflow.smartweather`)
* Twinkly (`com.twinkly`)
* Xbox Game Pass (`com.gamepass`)

### Icons updated
changed name of dji_ronin.svg to dji.svg

### Icons linked
* DJI Fly (linked `dji.go.v5` to `@drawable/dji`)
* DJI Ronin (linked `com.dji.ronin` to `@drawable/dji`)

### CODE REVIEW

**Comment by gabehowe** [comment]
My concern with the `first_citizens_bank` and the `hulu` logos is that they would be unrecognizable as the logos they are intended to be.

**Comment by Chefski** [comment]
Then you can gently curve the corners. Some of the icons just don't look right to be part of Lawnicons.

Also a thing I forgot to mention is corners not full corners or something is sticking out. It's present on the h and both u's. Not sure if its just a `hulu` issue or others have it too.
image

**Comment by gabehowe** [comment]
I fixed some bugs related to decimal precision and completed the requested actions

**Comment by gabehowe** [comment]
I fixed the `tempest` logo. Any idea why I keep having to merge HEAD into develop?

**Comment by Chefski** [comment]
Honestly speaking, I have no idea. When it happens it happens and its annoying but yeah idk

**Pull request merged**
