### PR TITLE
Add George Icon

### PR DESCRIPTION
**Pull request by vascYT**
### Icons added
* George Österreich/Austria (`at.erstebank.george`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing!

I can see the svg canvas size is 160x160px. Could you make it 192x192px?
The content area size should be fit to 160x160px instead?

The curved line should also have rounded end points. I made some quick changes in the screenshot. Not sure if you want to make the curve a little different with rounded end points

image

**Comment by vascYT** [comment]
Sure! I'll make the changes tomorrow.

**Comment by vascYT** [comment]
I've made the requested changes to the icon 🤠

**Review by Chefski — APPROVED** [review]
Thanks. Icon still didn't fit the content area but i fixed it. Mentioning for the future :)

**Pull request merged**
