### PR TITLE
Add 10 new icons

### PR DESCRIPTION
**Pull request by Stabiron**
## Description

Add 10 new icons.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Cx File Explorer (`com.cxinventor.file.explorer`) - added from icon request form
* Lithium EPUB Reader Free/Paid (`com.faultexception.reader`) - added from icon request form
* Edison Mail (`com.easilydo.mail`) - added from icon request form
* InShot (`com.camerasideas.instashot`) - added from icon request form
* Kahoot! (`no.mobitroll.kahoot.android`) - added from icon request form
* Kimcy Screen Recorder (`com.kimcy929.screenrecorder`) - added from icon request form
* Nothing X (`com.nothing.smartcenter`) - added from icon request form
* ONLYOFFICE (`com.onlyoffice.documents`) - added from icon request form
* rif is fun Free/Paid (`com.andrewshu.android.reddit`) - added from icon request form
* Wallfever (`com.amaan.wallfever`) - added from icon request form

Screenshot

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
`lithium` can have a content area size of 160x160 as its a rectangle. Not sure if it was done by an accident. Other that everything looks good :)

**Comment by Stabiron** [comment]
Have fixed it. I was a bit confused.  @Chefski

**Review by Chefski — APPROVED** [review]

**Comment by Chefski** [comment]
Mind just resolving the conflicts? Thanks

**Comment by Stabiron** [comment]
Done!

**Pull request merged**
