### PR TITLE
Added Govee Home, Infinity for Reddit, 1.1.1.1, OVinfo and 9292 icon

### PR DESCRIPTION
**Pull request by JordyEGNL**
My last pr had some errors in it, started from scratch. This one is tested and works

### CODE REVIEW

**Comment by JordyEGNL** [comment]
1.1.1.1 Icon added. #171

**Comment by JordyEGNL** [comment]
ProtonVPN icon added #182

**Comment by JordyEGNL** [comment]
[OVinfo ](https://play.google.com/store/apps/details?id=nl.skywave.ovinfo&hl=en_US&gl=US) icon added

**Comment by JordyEGNL** [comment]
[9292](https://play.google.com/store/apps/details?id=nl.negentwee&hl=en_US&gl=US) icon added

**Comment by JordyEGNL** [comment]
Fixed #237

**Comment by GravityNL** [comment]
Wow! Great icons man. Would love to see these in the app. 

Keep up the good work <3
@JordyEGNL

**Review by GravityNL — APPROVED** [review]

**Pull request merged**
