### PR TITLE
Added Booking icon

### PR DESCRIPTION
**Pull request by AnXh3L0**
## Description

Added Booking icon

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Booking (`com.booking`)

### Icons linked
* Booking (linked `com.booking` to `@drawable/booking.xml`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hiya! Thanks for contributing. Unfortunately the submitted icon does not follow the lawnicons style. You're free to read the [guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and make the icon again with the appropriate style. The commit also seems to be missing the link for `booking.svg`. Mind adding the link?
Thanks

**Comment by mustafakhalaf-git** [comment]
@Chefski 
how about this?

booking

**Comment by Chefski** [comment]
The dot is not a perfect circle. Maybe make the dot a filled circle instead of stroked.
image

**Comment by mustafakhalaf-git** [comment]
@Chefski done
booking

**Comment by Chefski** [comment]
@mustafakhalaf-git you can open your own PR for this icon if you would like

**Comment by mustafakhalaf-git** [comment]
I'll do it as soon as possible

**Comment by mustafakhalaf-git** [comment]
@Chefski https://github.com/LawnchairLauncher/lawnicons/pull/821

**Comment by Chefski** [comment]
Closing as icon has been added in #821

**Pull request closed without merging**
