### PR TITLE
Added 4 new Icons & 1 Updated

### PR DESCRIPTION
**Pull request by Stabiron**
**Description**

Added 4 new icons and updated an Existing one.

**Icons added**
* Gallery By WSTxda (`com.alensw.PicFolder`) - added from icon request form
* Simple Social (`com.creativetrends.simple.app`) - added from icon request form
* Open Link With (`com.tasomaniac.openwith`) - added from icon request form
* OfficeSuite (`com.mobisystems.office`) - added from icon request form

**Icons updated**
* Google (`com.google.android.googlequicksearchbox`)

Sorry if any mistakes made. I'm not familiar with Github.

Screenshot

### CODE REVIEW

**Comment by Uni-Rider** [comment]
I suggest keep the google icon unchanged, I find that the single line is more consistent. if you put it on your phone screen you will know what I mean. I am going to simplify some double line icons to single line.

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing! Got some small suggestions:
Could you reduce the size of `gallery_wstxda` as it goes outside the 160x160 content area size
image

Could you also add rounded corners to `open_link_with` (the endpoints of the bottom left and top right lines) and `office suite`. Could you also slightly reduce the size of `office_suite` as its slightly larger than 160x160px
image

You can also remove the google icon to keep the icons more consistent as stated by @Uni-Rider .

Also congratulations on the being the 1000th PR!

**Comment by Stabiron** [comment]
Hi @Chefski 

As requested I've made the changes let me know if all okay now.

**Review by Chefski — APPROVED** [review]

**Comment by Chefski** [comment]
Thanks!

**Comment by Stabiron** [comment]
@Chefski looks like you made some adjustments to OfficeSuite icon at your end. It now has this weird edge protruding out.

Just letting you know.

Screenshot 2023-01-28

**Comment by Chefski** [comment]
Thanks I'll fix it now

**Pull request merged**
