### PR TITLE
Add icon for Standard Notes

### PR DESCRIPTION
**Pull request by ASTRELION**
## Description

Added icon for [Standard Notes](https://github.com/standardnotes/app)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Standard Notes (`com.standardnotes`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
`standard_notes.svg` could have a change. The square is 11px in width rather than 12px. Mind changing it to 12px. The square could also be made with an inner stroke rather than fill to ensure the width is 12px. Other than that the icon is great

image

**Comment by ASTRELION** [comment]
Must've accidentally happened on a resize, should be fixed now :)

**Review by Chefski — APPROVED** [review]

**Comment by Chefski** [comment]
Forgot to mention to update the `standard_notes.xml` file 😅 after that the icon seems ready to be merged

**Comment by ASTRELION** [comment]
> Forgot to mention to update the `standard_notes.xml` file 😅 after that the icon seems ready to be merged

Is there a way to automatically regenerate the drawable, or do you just delete and re-make?

**Comment by Chefski** [comment]
> > Forgot to mention to update the `standard_notes.xml` file 😅 after that the icon seems ready to be merged
> 
> Is there a way to automatically regenerate the drawable, or do you just delete and re-make?

You can just go into android studio and generate it again with the same name and I'm pretty sure it replaces the old one. If that doesn't work then deleting and generating is the only method I know of. Would be nice for it just to generate after importing the new icon into the svg's folder

**Review by Goooler — APPROVED** [review]

**Pull request merged**
