### PR TITLE
76 icons added, 1 replaced, 10 icons linked to existing icons

### PR DESCRIPTION
**Pull request by SARRAF-5757**
Replaced - Infinity for Reddit

Linked to Existing Icons- Droid-ify, Dolby Audio, Harpy for Twitter, Wallpapers app (pixels), Shein, Shizuku

New Added - Activity Launcher, Adobe Fill and Sign, Adobe Photoshop, Adobe Scan, Apollo Lighting, Atlas VPN, AutoNotification, Backtrackit, Battery Guru, Bank (general wallet icon), Bitdefender, Blynk IoT, Brevent, Caffeine, Clock, Color Picker, Crayon Icon Pack, Dolby On, Draw on Screen, Facelapse/FaceApp, FusiOn for KWGT, FlorisBoard, Florisboard Beta, Forest Wallpaper, Google Opinion Rewards, Icon Pack Studio + (Exported), KWGT pro key, Lawnchair, Lawnicons, LG Tone Free, Linex Icon pack, Macrodroid, Medibang Paint, Mimo, Minecraft, Mini Metro, MiUI's Earth Super Wallpaper, Mars Super Wallpaper, Moto Game Time, Nomad, Nova Launcher, Nova Launcher Prime, Notion, Oppo Relax, Panels, Pi, Pi browser, Pix Wallpapers, Pix You icon pack, Pyroid3, Quick edit,  Quran (general), Remind, RescueTime, Samsung game launcher, Screen Dimmer, SD Maid, Sesame, Shadow KWGT, Sonic 3 Air, Spaceflight Simulator, Spike Mail, Spotiflyer, Stumble Guys, Tapet, ThemeX, Ting, LG Tone Free, Uzuri KWGT, VN Vieo editor, Volume Styles, WatchFace App (general), Xiaomi Game Turbo, Xiaomi Screen Recorder, Xiaomi Voice Recorder, Xiaomi Security, Xiaomi Weather, Whicons, YouCut, Zepp Life

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! Unfortunately, it would appear that the icons contain geometric errors, possibly because they were created using a tool for converting PNGs to SVGs. As a result, the shapes are crooked and the complexity of the paths is higher than necessary.

image

**Comment by SARRAF-5757** [comment]
Okay, I will try to recreate them all one by one. But it might take some time. Should I close this PR for now or do I just update this thread once I'm done with all of the icons?

**Comment by patrykmichalik** [comment]
I’d suggest keeping the pull request open and marking it as a draft, but if you’d rather open a new pull request later on, that works too.

Additionally, I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. I hope another team member will handle it. Thank you for your interest in contributing!

**Comment by Goooler** [comment]
@SARRAF-5757 Could you please rebase?

**Comment by SARRAF-5757** [comment]
> @SARRAF-5757 Could you please rebase?

Just did... see if it works

**Comment by SuperDragonXD** [comment]
I'll convert this into a draft since you're still applying changes.

**Pull request closed without merging**
