### PR TITLE
Add icons & redo xml

### PR DESCRIPTION
**Pull request by peterge1998**
## Description

Fixes #(issue)

It fixes my last PR, which introduced scrambled xmls due to https://inloop.github.io/svg2android/ suggested by @daywalk3r666.
This time i generated the xmls with android studio to prevent fucking them up.
I redesigned the threema icon.
The rest are new icons.

## Type of change

:white_check_mark:  Bug fix (non-breaking change which fixes an issue)
:white_check_mark:  Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added

```
    <icon drawable="@drawable/grapheneos_pdf" package="app.grapheneos.pdfviewer.play" name="Secure PDF Viewer" />
    <icon drawable="@drawable/paperless" package="eu.bauerj.paperless_app" name="Paperless" />
    <icon drawable="@drawable/pixel_buds" package="com.google.android.apps.wearables.maestro.companion" name="Pixel Buds" />
    <icon drawable="@drawable/watchbuddy" package="de.pietsmiet.watchbuddy" name="Watchbuddy" />
    <icon drawable="@drawable/octoremote" package="com.kabacon.octoremote" name="OctoRemote" />
    <icon drawable="@drawable/rvk" package="koeln.kvb.ticket.rvkapp" name="RVK" />
    <icon drawable="@drawable/steam_chat" package="com.valvesoftware.android.steam.friendsui" name="Steam Chat" />
    <icon drawable="@drawable/microflux" package="com.constantin.microflux" name="Microflux" />
    <icon drawable="@drawable/shelter" package="net.typeblog.shelter" name="Shelter"/>
    <icon drawable="@drawable/warnwetter" package="de.dwd.warnapp" name="WarnWetter" />
```

### Icons updated
ch.threema.app

### XML updated
com.mlk.rockamring
cloud.valetudo.companion

### CODE REVIEW

**Review by daywalk3r666 — CHANGES_REQUESTED** [review]
Fix typo....watchbuddy

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Got some changes:

In `microflux.svg`, the bottom of the M on the left side is not aligned with the right side
image

`shelter.svg` has strokes that are above 12px. Could you reduce to 12px?

**Review by Chefski — CHANGES_REQUESTED** [review]
`graphenos_pdf.svg`: The square is just about a pixel too big than 144x144px. Could you fix it

`paperless.svg`: Seems to have a path between both leaves which has a stroke of 0px. Assuming its not needed, could you delete it?

`pixel_buds.svg`: Could be sized up more to fit the 160x160px border

`threema.svg`: Could you just make the stroke have a full view in the rectangle for the lock?

These are all small changes and I know its a bit annoying to keep making small changes but its to maintain quality icons.

**Comment by peterge1998** [comment]
> `threema.svg`: Could you just make the stroke have a full view in the rectangle for the lock?

What exactly do you mean by that? I don't understand... (DeepL translates trash)

> These are all small changes and I know its a bit annoying to keep making small changes but its to maintain quality icons.

No problem dude! I am designing these SVG for about a week now, I am no pro at this yet! (Referring to quality icons: I look at you threema, mydealz and covpass 👀)

**Comment by Chefski** [comment]
> What exactly do you mean by that? I don't understand... (DeepL translates trash)

I'm sorry. Maybe I was thinking about something else while writing that. The stroke for the rectangle is 8.08 or something similar. I wanted to say "full digit" (as in no decimals. Just 8px). I'll edit the comment now

**Review by Chefski — COMMENTED** [review]
Everything looks fine. I'll just wait for the threema change and merge

**Comment by peterge1998** [comment]
image
...

**Review by Chefski — APPROVED** [review]
Not sure why it was making the XML wrong but I added the XML myself and was turning out fine. Thanks for making the changes

**Comment by peterge1998** [comment]
<icon drawable="@drawable/grapheneos_pdf" package="app.grapheneos.pdfviewer" name="Secure PDF Viewer" />
    .play is the playstore version. This line has to be added for the stock version coming preinstalled

**Pull request merged**
