### PR TITLE
Add Physics Wallah 

### PR DESCRIPTION
**Pull request by Zack-Bloodshot**
## Description

Add icon for Physics Wallah 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`xyz.penpencil.physicswala`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
The icon does not meet lawnicons design rules like rounded edges and stroke width of 12px. 

The 'W' seems to be going outside the circle and leaving a sharp corner:
image

The icon also goes beyond the 160x160 content area:
image

For more guidelines, please check [here](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md).

**Comment by Zack-Bloodshot** [comment]
> The icon does not meet lawnicons design rules like rounded edges and stroke width of 12px.
> 
> The 'W' seems to be going outside the circle and leaving a sharp corner: image
> 
> The icon also goes beyond the 160x160 content area: image
> 
> For more guidelines, please check [here](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md).

Ahh sorry! I will try to fix it!

**Review by Chefski — CHANGES_REQUESTED** [review]
Nice change on leaving out the outside circle. I gives more room for the letters now.

However the icon is now larger than the content area and artboard size. Please change the artboard size to 192x192 and make sure that stroke width is 12px
image

The circle isn't quite round and some corners are fully round or just have weird turns.
image
image

Thanks for your effort to contribute

**Comment by Zack-Bloodshot** [comment]
Thanks for the guidance, I will definitely try and fix those

**Review by Goooler — APPROVED** [review]

**Pull request merged**
