### PR TITLE
Add Calculator Plus icon

### PR DESCRIPTION
**Pull request by arch10**
## Description
Added Icon for Calculator Plus app. 
https://play.google.com/store/apps/details?id=com.gigaworks.tech.calculator

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Calculator Plus (`com.gigaworks.tech.calculator`)

### Icons linked
* Calculator Plus (linked `com.gigaworks.tech.calculator` to `@drawable/calculator_plus`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for the new icon! Would you mind resizing the icon to fit the 160x160px content area?
image

**Comment by arch10** [comment]
Hey @Chefski 
Sorry, I didn't really understood your question.
This is a square icon and, as per the contribution doc, needs to fit inside the 144px square area. Also this icon is similar to existing calculator icon with elements re-arranged.

Do you want me to increase the size of elements to fit inside 160px content area?

**Comment by Chefski** [comment]
> Do you want me to increase the size of elements to fit inside 160px content area?

Yes. Didn't know the calculator icon has a content area of 144x144px. I'll probably change it to 160x160

**Review by Chefski — APPROVED** [review]

**Comment by arch10** [comment]
Thanks for updating the PR. 😄

**Pull request merged**
