### PR TITLE
Add Google Opinion Rewards

### PR DESCRIPTION
**Pull request by Chefski**
## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Google Opinion Rewards (`com.google.android.apps.paidtasks`)

### CODE REVIEW

**Comment by naveenccmsd** [comment]
@Chefski mind sharing activty details for     
<icon drawable="@drawable/google_opinion_rewards" package="com.google.android.apps.paidtasks" name="Google Opinion Rewards" />

**Comment by Chefski** [comment]
@naveenccmsd yeah i'm getting that info

**Comment by Chefski** [comment]
<item component="ComponentInfo{com.tpcstld.twozerogame/com.tpcstld.twozerogame.MainActivity}" drawable="2048"/>

	
	<item component="ComponentInfo{com.adobe.scan.android/com.adobe.scan.android.SplashActivity}" drawable="adobe_scan"/>

	
	<item component="ComponentInfo{com.bendingspoons.dawn.ai/com.bendingspoons.remini.MainActivity}" drawable="dawn_ai"/>

	
	<item component="ComponentInfo{com.mobile_infographics_tools.mydrive/com.mobile_infographics_tools.mydrive.activities.IntroActivity}" drawable="drives"/>

	
	<item component="ComponentInfo{com.truecaller.guardians/com.truecaller.guardians.home.HomeActivity}" drawable="guardians"/>

	
	<item component="ComponentInfo{com.getmimo/com.getmimo.ui.SplashActivity}" drawable="mimo"/>

	
	<item component="ComponentInfo{com.stephaneginier.nomad/com.stephaneginier.nomad.AppActivity}" drawable="nomad_sculpt"/>

	
	<item component="ComponentInfo{com.prisma3D.prisma3D/com.prisma.prismaplugin.UnityPlayerActivityStatusBar}" drawable="prisma3d"/>

	
	<item component="ComponentInfo{ru.iiec.pydroid3/ru.iiec.pydroid.MainActivity}" drawable="pydroid_3"/>

	
	<item component="ComponentInfo{com.google.android.apps.paidtasks/com.google.android.apps.paidtasks.activity.LaunchActivity}" drawable="rewards"/>

	
	<item component="ComponentInfo{com.miui.securitycenter/com.miui.securityscan.MainActivity}" drawable="security"/>

	
	<item component="ComponentInfo{com.StefMorojna.SpaceflightSimulator/com.unity3d.player.UnityPlayerActivity}" drawable="spaceflight_simulator"/>

	
	<item component="ComponentInfo{com.thetileapp.tile/com.thetileapp.tile.activities.MainActivity}" drawable="tile"/>

Here's the activity info for icons I'll be adding. Got this from the requester so you might need to double check some drawable names

**Comment by Chefski** [comment]
It's in the list I provided @naveenccmsd

**Pull request merged**
