### PR TITLE
Icon proposal for LEGO® Builder

### PR DESCRIPTION
**Pull request by service-paradis**
# Description

Icon proposal for LEGO® Builder (https://play.google.com/store/apps/details?id=com.lego.legobuildinginstructions)

### Added
LEGO® Builder (`com.lego.legobuildinginstructions`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by service-paradis** [comment]
This s the version submitted in this PR:
image

This is another option:
image

Which one would be better? Or is there another option that would look best?

**Comment by x9136** [comment]
Screenshot 2024-03-08 at 11 12 09

I would simplify the connections even more to avoid blackness. If this option would not work, I would reduce the number of shapes to 2 or 1, but make the connections as similar as possible to LEGO.

**Comment by x9136** [comment]
> Maybe I could keep only those 2 parts with connections similar to y 2nd proposal?

It's up to you. Given the limitations of the style, it's probably best to make one lego piece that leaves no doubt that it's LEGO.

**Comment by service-paradis** [comment]
Thank you for your comments. I just sent a new simplified version with only 2 shapes and reduced corner radius. I also have the following version on hand:
image

**Comment by x9136** [comment]
Blackness is worth avoiding. Don't forget to round the bottom corners.

Screenshot 2024-03-11 at 18 44 39

**Comment by service-paradis** [comment]
Sure, just pushed rounded bottom corners!

**Pull request merged**
