### PR TITLE
Add WTMP

### PR DESCRIPTION
**Pull request by Chefski**
Adds WTMP (Who touched my phone) icon

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! Iʼd suggest these tweaks: [`who_touched_my_phone.zip`](https://github.com/LawnchairLauncher/lawnicons/files/9127997/who_touched_my_phone.zip).

**Comment by Chefski** [comment]
updated icon :)

**Comment by patrykmichalik** [comment]
Cheers for applying the changes! I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. I hope another team member will handle it. Thank you for your interest in contributing!

**Comment by SuperDragonXD** [comment]
Sorry for the delay, but have merged the PR. Thanks!

**Pull request merged**
