### PR TITLE
Adding ViMusic app as vi_music.svg

### PR DESCRIPTION
**Pull request by medtty**

### CODE REVIEW

**Review by projjalm — COMMENTED** [review]
I think this svg looks better than mine for the same app (ViMusic) which got merged sometime back (#1112). It just needs a bit of scaling and realigning to fit into the 160x160px grid centrically.

**Comment by Chefski** [comment]
image
Is this the original icon?

**Comment by projjalm** [comment]
Yes, that one.

**Comment by projjalm** [comment]
Ah, no, if you find the previous one more suitable then let it be that way :)
The reason I thought this one looks better is because of its simplicity, but reviewing it again now makes me think it is, way too simple.
Let the previous icon remain and wait for @medtty to comment.

**Comment by Chefski** [comment]
I'll be closing this PR. The current icon has been agreed upon as more suitable. Thanks for contributing

**Pull request closed without merging**
