### PR TITLE
Material files, aves gallery, qksms, Tachiyomi, Sony camera, Xbox; Link Amazon india.

### PR DESCRIPTION
**Pull request by arun54321**
https://github.com/LawnchairLauncher/lawnicons/issues/207

https://github.com/LawnchairLauncher/lawnicons/issues/61

https://github.com/LawnchairLauncher/lawnicons/issues/166

https://github.com/LawnchairLauncher/lawnicons/issues/215

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Sorry for keeping you waiting! Iʼd suggest making the logo in the Tachiyomi icon a bit smaller ([`tachiyomi.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7936111/tachiyomi.zip)). Additionally, because Sony Camera is a system camera app, Iʼd suggest linking the `com.sonyericsson.android.camera` package to `@drawable/camera`.

**Comment by yancelawang** [comment]
Is the sony camera not linked yet?

**Comment by yancelawang** [comment]
> Sorry for keeping you waiting! Iʼd suggest making the logo in the Tachiyomi icon a bit smaller ([`tachiyomi.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7936111/tachiyomi.zip)). Additionally, because Sony Camera is a system camera app, Iʼd suggest linking the `com.sonyericsson.android.camera` package to `@drawable/camera`.

How about sony camera? Is it not linked yet?

**Comment by arun54321** [comment]
Sorry. I forgot this pull request. If anyone want to add these svgs, feel free to do. I don't use themed icons and lawnchair now.

**Pull request closed without merging**
