### PR TITLE
Brave icon replace + Add Beta and Nightly

### PR DESCRIPTION
**Pull request by Chefski**
I created a new icon for the Brave Browser as the previous one felt underwhelming. In addition, I made icons for Brave Beta and Brave Nightly

### Brave
Screenshot 2022-06-03 154312

### Brave Beta
Screenshot 2022-06-03 154154

### Brave Nightly
Screenshot 2022-06-03 155029

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
This doesn't follow the round lines design, and has inconsistent line thicknesses in unnecessary places.

**Comment by Chefski** [comment]
> has inconsistent line thicknesses in unnecessary places.

Surely some thickness can decreased in places to make it visually appealing. Does this new design work better?

image

**Comment by ThatOneCalculator** [comment]
Not perfect but definitely better

**Comment by Chefski** [comment]
Being realistic, you can't make a perfect replicate with limitations. Final proposition

image

**Comment by ThatOneCalculator** [comment]
Looks great!

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR, @Chefski, and cheers for your input, @ThatOneCalculator! The symbol of the lion looks great to me. However, the “Beta” and “Nightly” labels appear not to match the style of Lawnicons. I’d suggest utilizing an approach similar to the one used in the Chrome Beta and Chrome Dev icons.

**Review by SuperDragonXD — APPROVED** [review]

**Pull request merged**
