### PR TITLE
Added Aegis (cleaned), Antennapod and AdAway Icons

### PR DESCRIPTION
**Pull request by elea11**

### CODE REVIEW

**Comment by elea11** [comment]
Giving up

**Comment by arun54321** [comment]
Simple adaway svg for you. if you like

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   version="1.1"
   id="svg4"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8" />
  <path
     d="M7.873 2 2.012 7.846 2 16.127l5.846 5.861 8.281.012 5.861-5.846L22 7.873l-5.846-5.861zm.826 2 6.623.01L20 8.7l-.01 6.622L15.3 20l-6.622-.01L4 15.3l.01-6.622zM6.314 7.252c-.087.009-.087.064.016.19.595 1.226.997.876 2.432 1.529 1.034.162-1.53.657-1.727.414.218 1.016 1.252.801 1.838.894 1.2.255-1.532.66.014 1.522.163.544-.04 1.714 1.8 1.799 1.115.05 2.349-.43 2.4.101.045.45-.983.763-3.087 2.256-.89.743.661.807.635 1.125.57.962.95-.21 1.316.402.192.304.59.757.938.748l.584.018c0-.813.252-1.703.697-2.129 1.396-1.546 2.815-1.372 2.701-4.533.02-1.131.81-2.463 1.379-2.494-.166-.077-.324-.235-.498-.406-.16-.158-.792-.705-1.225-.641-.555.122-1.047 1.262-1.447 1.455-.981.474-1.15.104-1.926-.629-.345-.363-.813-.721-2.045-.797-2.397-.009-4.416-.862-4.795-.824zm10.46 1.586a.217.217 0 1 1 0 .435.217.217 0 0 1 0-.435z"
     id="path2" />
</svg>

```


image

**Comment by arun54321** [comment]
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="24"
   height="24"
   version="1.1"
   id="svg4"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8" />
  <path
     id="path2"
     d="M 7.8730469 2 L 2.0117188 7.8457031 L 2 16.126953 L 7.8457031 21.988281 L 16.126953 22 L 21.988281 16.154297 L 22 7.8730469 L 16.154297 2.0117188 L 7.8730469 2 z M 5.0742188 6.5019531 C 5.516409 6.4570408 7.8713238 7.4639722 10.667969 7.4746094 C 12.105377 7.5644339 12.652168 7.9889389 13.054688 8.4179688 C 13.960068 9.2843021 14.156221 9.7203773 15.300781 9.1601562 C 15.767472 8.9320494 16.342701 7.585598 16.990234 7.4414062 C 17.495428 7.3657646 18.233246 8.0124784 18.419922 8.1992188 C 18.622933 8.4013238 18.806323 8.5867312 19 8.6777344 C 18.336132 8.7143733 17.413955 10.290223 17.390625 11.626953 C 17.523632 15.362941 15.868986 15.157156 14.240234 16.984375 C 13.72104 17.487864 13.425781 18.539115 13.425781 19.5 L 12.746094 19.478516 C 12.340072 19.489153 11.874403 18.953047 11.650391 18.59375 C 11.223368 17.870426 10.780267 19.256128 10.115234 18.119141 C 10.14557 17.743297 8.3366134 17.667215 9.375 16.789062 C 11.829795 15.024484 13.029063 14.654902 12.976562 14.123047 C 12.91706 13.495458 11.476682 14.062986 10.175781 14.003906 C 8.0290042 13.903444 8.2663484 12.519907 8.0761719 11.876953 C 6.2724107 10.858155 9.4606207 10.37951 8.0605469 10.078125 C 7.3768446 9.9682077 6.1703621 10.222295 5.9160156 9.0214844 C 6.1458608 9.3086863 9.1360831 8.724671 7.9296875 8.5332031 C 6.2554339 7.7614218 5.7859996 8.1755728 5.0917969 6.7265625 C 4.9716256 6.5776425 4.9727144 6.5125911 5.0742188 6.5019531 z " />
</svg>

```


image

**Comment by arun54321** [comment]
There is already an adaway icon in pull [request ](https://github.com/LawnchairLauncher/lawnicons/pull/173)

**Comment by elea11** [comment]
Yeah, i know.  Don't know which one to keep. And if the PR is fine to merge or if I messed up big time😃. Mind having a look?

**Comment by arun54321** [comment]
No. It's messy. Please take a look at changes at grayscale xml. You've removed links of existing icons, making them useless and your vectors are too big too. i.e. adaway xml is around 20 kb

**Pull request closed without merging**
