### PR TITLE
Remove unused calendar.xml

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Follow up #750.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:white_check_mark: General change (non-breaking change that doesn't fit the above categories like copyediting)

### CODE REVIEW

**Comment by Goooler** [comment]
CC @naveenccmsd.

**Comment by naveenccmsd** [comment]
yes we can remove, may be after the pr https://github.com/LawnchairLauncher/lawnicons/pull/815 merged

**Comment by Goooler** [comment]
Why? It's already unused now.

**Comment by naveenccmsd** [comment]
@Goooler yes , it's no used . This can be removed now.

**Pull request merged**
