### PR TITLE
Add Careem & Qibla Direction

### PR DESCRIPTION
**Pull request by mustafakhalaf-git**
## Description

Added 4 icons

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Careem (`com.careem.acma`)
* Qibla Direction (`qibla.compass.finddirection.hijricalendar`)

### Icons linked
* Quran (linked `com.quran.labs.androidquran` to `@drawable/quran`)
* Quran English (linked `com.andi.alquran.en` to `@drawable/quran`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing. Could reduce the circle stroke in `qibla_direction.svg` to 12px? If you would like to keep the shapes inside the the circle smaller, you can reduce their stroke to 8px if you would like. Could you also change the colour to be solid rather than linear?

**Comment by mustafakhalaf-git** [comment]
Aight

**Comment by mustafakhalaf-git** [comment]
think I fixed it this time, can you confirm?

**Review by Chefski — APPROVED** [review]
Thanks

**Comment by thismoon** [comment]
> If you would like to keep the shapes inside the the circle smaller, you can reduce their stroke to 8px if you would like

@Chefski can you please add this info to the CONTRIBUTING.md image? it's not there yet but it's allowed
also why 8px instead of 6px (half of 12px)?

**Comment by Chefski** [comment]
The original creator of the guidelines went by 12/8px. 6px can be hard to see sometimes so its only used in very specific scenarios.

**Comment by mustafakhalaf-git** [comment]
@Chefski Ah cool, but still could you put it in guidelines?

**Comment by Chefski** [comment]
> could you put it in guidelines?

Yeah I'll add it :)

**Pull request merged**
