### PR TITLE
`main-wip` style icons for `GCam MWP Clone`, `TickTick`, `Flamingo`, `ekşi sözlük` and `TurboTel Pro`

### PR DESCRIPTION
**Pull request by halacoglu**
`com.eksiteknoloji.eksisozluk`
`com.GoogleCamera.mwp83`
`com.samruston.twitter` #227 
`com.ticktick.task` #238 
`ellipi.messenger`

Screenshot_1643842028-1

### CODE REVIEW

**Comment by halacoglu** [comment]
- Refined Flamingo icon lines
- Aligned TurboTel icon vertically

**Comment by halacoglu** [comment]
- Refined Flamingo icon lines
- Aligned TurboTel icon vertically

**Review by halacoglu — COMMENTED** [review]
- Refined Flamingo icon lines
- Aligned TurboTel icon vertically

**Comment by halacoglu** [comment]
Added gradient style for `Flamingo` #227

**Comment by halacoglu** [comment]
All four icons updated with `main-wip` design language.

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
For the TickTick and ekşi sözlük icons, I’d suggest using rounded stroke caps and joins, like so: [`suggestions.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7989815/suggestions.zip). This is a guideline I’ve forgotten to include in `CONTRIBUTING.md`. Sorry about it!

**Comment by halacoglu** [comment]
> For the TickTick and ekşi sözlük icons, I’d suggest using rounded stroke caps and joins, like so: [`suggestions.zip`](https://github.com/LawnchairLauncher/lawnicons/files/7989815/suggestions.zip). This is a guideline I’ve forgotten to include in `CONTRIBUTING.md`. Sorry about it!

Thank you, Patryk. I made the suggested changes. By the way, how come your SVGs are half the size of mines? Is there a tip to reduce the file size?

**Comment by patrykmichalik** [comment]
Thanks for applying the changes, @halacoglu! Regarding your question, I believe the reason for the difference in size between my SVGs and yours is that the lines in yours were represented as filled paths, meaning there were more anchor points:

2022-02-03-192540_357x372_scrot 2022-02-03-192548_357x369_scrot

**Review by patrykmichalik — APPROVED** [review]

**Comment by patrykmichalik** [comment]
Thank you for contributing!

**Comment by halacoglu** [comment]
> Thanks for applying the changes, @halacoglu! Regarding your question, I believe the reason for the difference in size between my SVGs and yours is that the lines in yours were represented as filled paths, meaning there were more anchor points:
> 
> 2022-02-03-192540_357x372_scrot 2022-02-03-192548_357x369_scrot

Makes perfect sense. Thank you!

**Pull request merged**
