### PR TITLE
Add Codecademy Go

### PR DESCRIPTION
**Pull request by Chefski**
Adds Codecademy Go icon

Screenshot 2022-06-08 184030

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! Iʼd suggest these tweaks: [`codecademy_go.zip`](https://github.com/LawnchairLauncher/lawnicons/files/9127944/codecademy_go.zip).

**Comment by Chefski** [comment]
Changed it :)

**Comment by patrykmichalik** [comment]
Cheers for applying the changes! I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. I hope another team member will handle it. Thank you for your interest in contributing!

**Comment by SuperDragonXD** [comment]
Sorry for the delay, but merged the PR. Thanks!

**Pull request merged**
