### PR TITLE
Add calendar, Camera connect, IDFC and few more

### PR DESCRIPTION
**Pull request by naveenccmsd**
## Description
* com.samsung.android.calendar
* jp.co.canon.ic.cameraconnect
* https://play.google.com/store/apps/details?id=com.fiserv.IDFCMerchantServices
* https://play.google.com/store/apps/details?id=com.udemy.android
* https://play.google.com/store/apps/details?id=com.snapwork.hdfc
* https://play.google.com/store/apps/details?id=com.adobe.reader
* https://play.google.com/store/apps/details?id=com.simpl.android

#697 

Fixes #(issue) 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Samsung Calendar (`com.samsung.android.calendar`)
* Canon Camera Connect (`jp.co.canon.ic.cameraconnect`)
* `com.fiserv.IDFCMerchantServices`
* `com.udemy.android`
* `com.snapwork.hdfc`
* `com.adobe.reader`
* `com.simpl.android`

### Icons Linked 
* `com.idfcfirstbank.optimus`
* `cz.seeq.prog.android.packageviewer` 

Note : Linked cz.seeq.prog.android.packageviewer to `app_manager` insted `package_manager` because the official icon is same as `app_manager`.

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
`idfc.svg`: Could you change the rectangles inside the square to be rounded? And also make the content area size 144x144 as it is a square
image


`hdfc.svg`: Could you make the corners rounded to maintain the rounded corner style. The icon can also be reduced to a content area size of 144x144 as its a square.

`paper_duty.svg`: I believe all corners in this icon could be rounded too.

Thanks

**Comment by naveenccmsd** [comment]
@Chefski  chaanged all iicons as per suggestion and added adobe icon , I tried as per you suggesstion in #685 But It's difficult to use stroke as 12px for one line and less that 6px for another cureved line, so used 12px stroke for entire logo.

**Comment by naveenccmsd** [comment]
> Wasn't sure if consistent 12px line will work with the Adobe icon but it looks really good. There's just and unneeded point which is making the shape go in a bit at the top of the Adobe icon. Mind fixing it?
> 
> image

@Chefski fixed extra node

**Review by Chefski — APPROVED** [review]
Cheers

**Comment by naveenccmsd** [comment]
@Chefski , I don't see themed icon applied to lawnchair icon , wonder why it was not added  in lawnicons yet or not added to lawnchair app ? should I  add it ?
WhatsApp Image 2022-09-28 at 5 37 16 PM

**Comment by Chefski** [comment]
Guess nobody added it yet. I have the app hidden so I didn't even notice

**Pull request merged**
