### PR TITLE
Add 6 icons

### PR DESCRIPTION
**Pull request by IAmRuMaks**
### Original Icons:
Before
### New Icons:
After

### CODE REVIEW

**Comment by IAmRuMaks** [comment]
New icons - Orbot, Tutanota & Pixel Wallpapers:

**Comment by IAmRuMaks** [comment]
Apparently, a QuickSwitch icon has been already added in #297. I will keep my version of it in this PR, since i like it more, but let me know if i should remove it.

**Comment by ZhmieXD** [comment]
> Apparently, a QuickSwitch icon has been already added in #297. I will keep my version of it in this PR, since i like it more, but let me know if i should remove it.

Hey, I actually like your version! It looks even better! Hopefully this got merged soon! 😁

**Comment by patrykmichalik** [comment]
Thank you, @IAmRuMaks!

**Pull request merged**
