### PR TITLE
21 new, 3 linked apps (5 links overall)

### PR DESCRIPTION
**Pull request by SiMah5**
## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories, such as copyediting)

### Icons added from icon request form
* ATH Móvil (`com.evertec.athmovil.android/com.evertec.athmovil.android.SplashScreen`)
* auth (`io.ente.auth/io.ente.auth.MainActivity`)
* Mapillary (`com.mapillary.app/app.mapillary.android.activity.SplashActivity`)
* Samsung Pay Mini (`com.samsung.android.spaymini/com.samsung.android.spay.ui.SpayMainActivity`)
* One Hand Operation + (`com.samsung.android.sidegesturepad/com.samsung.android.sidegesturepad.settings.SGPSettingsActivity`)
* Secure Folder (`com.samsung.knox.securefolder/com.samsung.knox.securefolder.switcher.SecureFolderShortcutActivity`)
* Next Player (`dev.anilbeesetti.nextplayer/dev.anilbeesetti.nextplayer.MainActivity`)
* MoneyWallet (`com.oriondev.moneywallet/com.oriondev.moneywallet.ui.activity.LauncherActivity`)
* Sense (`com.f0x1d.sense/com.f0x1d.sense.ui.activity.MainActivity`)
* Simple Clipboard Editor (`com.trianguloy.clipboardeditor/com.trianguloy.clipboardeditor.Editor`)
* TagMo (`com.hiddenramblings.tagmo.eightbit/com.hiddenramblings.tagmo.BrowserActivity`)
* Warpinator (`slowscript.warpinator/slowscript.warpinator.MainActivity`)
* ente Photos (`io.ente.photos/io.ente.photos.MainActivity`)
* Graded (`com.NightDreamGames.Grade.ly/com.NightDreamGames.Grade.ly.MainActivity`)
* I2P (`net.i2p.android.router/net.i2p.android.I2PActivity`)
* LingoDeer (`com.lingodeer/com.lingo.lingoskill.ui.base.SplashActivity`)
* Rays (`com.skyd.rays/com.skyd.rays.ui.activity.MainActivity`)
* NextDNS Manager (`com.doubleangels.nextdnsmanagement/com.doubleangels.nextdnsmanagement.MainActivity`)
* NextDNS (`io.nextdns.NextDNS/io.nextdns.NextDNS.MainActivity`)
* DreamLab (`au.com.vodafone.dreamlabapp/au.com.vodafone.dreamlabapp.activity.SplashScreenActivity`)
* Spotube (`oss.krtirtho.spotube/com.ryanheise.audioservice.AudioServiceActivity`)
* giffgaff (`com.giffgaffmobile.controller/com.giffgaff.reapps.SplashActivity`)

### Icons linked from icon request form
* Luna (linked `com.jggdevelopment.bookbuddy/com.jggdevelopment.bookbuddy.ui.main.MainActivity` to `@drawable/generic_moon`)
* SCEE (linked `de.westnordost.streetcomplete.expert/de.westnordost.streetcomplete.screens.MainActivity` to `@drawable/streetcomplete`)
* LMHT: Toc Chien (linked `com.riotgames.league.wildriftvn/com.tencent.lolm.lgame` to `@drawable/wild_rift`)
* DreamLab (linked `au.com.vodafone.dreamlabapp/au.com.vodafone.dreamlabapp.presentation.launcher.LauncherScreenActivity` to `@drawable/dreamlab`)
* Secure Folder (linked `com.samsung.knox.securefolder/com.samsung.knox.securefolder.presentation.switcher.view.SecureFolderShortcutActivity` to `@drawable/secure_folder`)
* Mapillary (linked `com.mapillary.app/app.mapillary.android.activity.TabbedMainActivity` to `@drawable/mapillary`)

### CODE REVIEW

**Comment by RaduBratan** [comment]
It appears both you and #1306 added `dreamlab.svg` lmao

**Comment by SiMah5** [comment]
@RaduBratan  lol i knew this would happen eventually, thanks for telling me, gonna remove mine then .

**Comment by x9136** [comment]
@SiMah5 Sorry, I was checking your PR before creating mine, but I didn't notice dreamlab.svg. I don't usually make icons that someone has already suggested.

If you're wondering, before I start working on svgs, I plan the list and update it after merging a PR. Maybe this will be useful for synchronization. https://docs.google.com/spreadsheets/d/12IuwraEILgskEuGqqUFjAhzjUB3H2Sr0vn3p0uIEkC8/edit#gid=1702695761&range=A2

**Comment by SiMah5** [comment]
@x9136 no worries, its hard to prevent something like this with how the icon forum request is set up. wish we had a better icon request system. 
oh that spreadsheet is definitely gonna help with synchronization, thanks!

**Comment by lorrding** [comment]
> @x9136 no worries, its hard to prevent something like this with how the icon request form is set up. wish we had a better icon request system. oh that spreadsheet is definitely gonna help with synchronization, thanks!

It would indeed be great to have a board in the [Projects](https://github.com/LawnchairLauncher/lawnicons/projects) tab of the repo so everyone could grab an icon request and reference it in his PR, we could also set milestones to plan release every hundred or so icons added or every month

**Comment by x9136** [comment]
> It would indeed be great to have a board in the [Projects](https://github.com/LawnchairLauncher/lawnicons/projects) tab of the repo so everyone could grab an icon request and reference it in his PR, we could also set milestones to plan release every hundred or so icons added or every month

There's a lot of manual work now, and this will be extra. Desynchronization is a small thing. It's about organizing the collection of requests, it needs to be automated. On the other hand there are a couple of thousand icons left to do, then there won't be many requests. For example, last month 400 icons appeared and 250 new applications were linked to old icons. During this time there were 40-50 entirely new requests.

So it makes little sense to bother. However, requests automation has greatly simplified the path of the icon from the request to the appearance in the main branch.

Now this path is something like this: an user sees that there is no icon → the user is looking for how to request it → the user is looking for how to find out an app component name → the user send a list through the form → I enter it from the requests table into my table to form a list by popularity → I install the most popular apps from the list to clarify whether they have icons and generate a list of full component names → I check other PRs → I transfer the names of components to an additional table, to form a command for the Terminal → I create icons according to the guidelines → I export icons to my repo → I create a PR → I check the dev's build to make sure there are no typo → I make corrections to PR and remove ready-made components from my table. At this time, ready-made icons are added to the main branch. 

Which way should be: the list of missing icons is formed automatically by popularity and the full names of the components are immediately written → I create icons according to the guidelines → I export icons to my repo and create a PR → until the request is accepted, these icons are marked in the table as in progress → when merging the PR with the main branch, the icons in the table are marked as ready and removed from the list of not ready.

**Comment by lorrding** [comment]
> In fact, now I'm already wondering if it's possible to teach a neural network to follow guidelines. It would be easy to throw her pictures for icons, and it will do it. Only the editing will remain. Then it would be possible to make all the icons at once, and then to improve the quality by hands. :D

You can check for [localGPT](https://github.com/PromtEngineer/localGPT), it's an AI that can ingest documents and images, and I think you should be able to make it output svg or at least pipe the answer to a fine-tuned text to image AI.

But that would cost a lot in term of GPU power

**Review by Chefski — APPROVED** [review]

**Pull request merged**
