### PR TITLE
Icon for A&W

### PR DESCRIPTION
**Pull request by service-paradis**
# Description

Icon proposal for A&W (https://play.google.com/store/apps/details?id=com.myelane2_aw)

### Added
A&W (`com.myelane2_aw`)

## Contributor's checklist

- [x] I made the icons following [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by KTibow** [comment]
The icon could be simplified a bit if desired, removing the arrow, since most Lawnicons only show the essential part that shows up across brand use.

**Comment by service-paradis** [comment]
Good catch. I think I never saw this brand without the arrow, but I can submit the following icon if needed:
```svg
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 192 192"><path stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="6" stroke-width="12" d="M22 111.625 38.948 87.31c2.69-3.395 5.864-7.123 12.912-6.678l5.487 30.994"/><path stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="6" stroke-width="8" d="M25.551 107.697h31.795M97.695 81.131c-11.298-7.513-28.89 2.17-18.722 9.35-18.011 8.94-8.48 24.593 10.3 22.909 23.765-3.426 18.16-28.409-.778-15.563"/><path stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="6" stroke-width="12" d="m114.318 80.63 5.488 30.995h3.066l17.592-30.994 2.86.13 4.242 30.864h5.487l16.946-30.994"/></svg>
```
image

**Comment by x9136** [comment]
Screenshot 2024-02-01 at 17 21 53

If you want, I can explain why I changed your version that way. In general, since Lawnicons style is described within a specific framework, it suggests a stylization of the original, not an attempt to copy the original shapes as much as possible.

That's why I usually think about how to make an icon in Lawnicons style while maintaining the recognizability of the original, rather than trying to twist and tweak the requirements of the style to fit the shape of the original. I hope I was able to convey the idea.

In code, if you want to check the size and the stroke thickness.
```
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m124 83 6 31 19-31 4 31 19-31m-98 31-6-31h-4l-28 36m12-14h23m38.449-19.521c-10.15-6.849-25.952 1.98-16.818 8.523-16.18 8.149-7.617 22.418 9.254 20.884 21.348-3.124 16.313-25.897-.7-14.187" stroke="#000" stroke-width="8" stroke-miterlimit="6" stroke-linecap="round" stroke-linejoin="round"/><path d="m120 52 13.5 15.69m0 0c-9.963-2.685-21.115-4.264-32.595-4.615s-22.978.535-33.606 2.59c-10.629 2.054-20.102 5.222-27.687 9.258-7.585 4.036-13.079 8.833-16.056 14.018-2.978 5.186-3.36 10.622-1.115 15.887 2.244 5.266 7.054 10.219 14.058 14.479 7.003 4.259 16.012 7.709 26.33 10.084C73.145 131.765 84.495 133 96 133" stroke="#000" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/></svg>
```

**Comment by service-paradis** [comment]
Looking good! Thank you for the feedback! I have this bad habit of trying to be closest as possible to the original. As you just demonstrate, we can keep the essence of the original while matching Lawnicons style. Just committed your version, but feel free to mark yourself as coauthor since I dont want to have all the merit for this one!

**Pull request merged**
