### PR TITLE
Add ESPN, Game Launcher, and Tips icons

### PR DESCRIPTION
**Pull request by 77Z**
## Description
More icons I'm pretty confident in: ESPN, Game Launcher, and Tips

Game Launcher and Tips are both exclusive to Samsung Android, so I didn't know if I should've prefixed them with `samsung_` but looking at other examples, I chose to leave it out as the original app names don't include "Samsung" at the beginning. Let me know if this is something desired and I'll change it.

I was also going to do the Bixby icon but the rounding was fighting me, so that might be my next icon, and I'll try and do some from the Google Sheet.

## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* ESPN (`com.espn.score_center`)
* Game Launcher (`com.samsung.android.game.gamehome`)
* Tips (`com.samsung.android.app.tips`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Could you just increase the size of `espn.svg` as its minimally smaller than the 160x160px content area size.

**Comment by Chefski** [comment]
I think the names are fine. They might change in the future but for now they're fine.

**Comment by 77Z** [comment]
Must've slipped past me. Changes made

**Review by Chefski — APPROVED** [review]
Thanks!!

**Pull request merged**
