### PR TITLE
9 various new icons

### PR DESCRIPTION
**Pull request by Grabstertv**
## Description

Added 9 various icons

### CODE REVIEW

**Review by Chefski — COMMENTED** [review]
Overall icons are fine just sizes aren't fit to the 160x160px content area

**Comment by Grabstertv** [comment]
I used the guides from contributions and they fit perfectly for me. Do let me know how they aren't fitting so i can fix them
image

**Comment by Chefski** [comment]
I tend to group all my paths and make either the width, height or both (depending which is bigger) 148px if stroke is 12px or 152px if its 8px. Some other factors can make it have to be 150px width/height sometimes. Maybe its an issue from my end. Wanna do that and I'll check if it still appears wrong for me

The sizes were not terribly wrong. Usually like 1 to 4 pixels off. 
image

The Asphalt icon is a fill icon which means me resizing will make the stroke thicker. Not sure if it was meant to use fill or stroke.

**Comment by Chefski** [comment]
Alright so I merged `acode.svg` made by @thismoon. Both look good

@thismoon and @Grabstertv, wanna decide which one would be more suitable? Maybe a Discord poll can be made or something?

**Comment by Grabstertv** [comment]
> I tend to group all my paths and make either the width, height or both (depending which is bigger) 148px if stroke is 12px or 152px if its 8px. Some other factors can make it have to be 150px width/height sometimes. Maybe its an issue from my end. Wanna do that and I'll check if it still appears wrong for me
> 
> The sizes were not terribly wrong. Usually like 1 to 4 pixels off. image
> 
> The Asphalt icon is a fill icon which means me resizing will make the stroke thicker. Not sure if it was meant to use fill or stroke.

fixed scaling. Take a look and let me know if they look better now. As for the Asphalt 9 icon, i had to make it an outline from stroke to add some inner rounded corners.

**Comment by Grabstertv** [comment]
> Alright so I merged `acode.svg` made by @thismoon. Both look good
> 
> @thismoon and @Grabstertv, wanna decide which one would be more suitable? Maybe a Discord poll can be made or something?

I like their's tbh but lets have a community vote. Now we wait.
image

**Review by Chefski — APPROVED** [review]
Yeah icons are correct size now. 3 were still wrong size but it might've just been overlooked. Its literally perfect tho :')

Now we just wait a few hours for poll results

**Comment by thismoon** [comment]
> I like their's tbh but lets have a community vote. Now we wait.

I think yours is simpler therefore more fitting in lawnicons, and probably look better in small size (mine is detailed and look a bit weird)

by the way I wasn't aware of this pr, so it is a coincidence

also you won
image

**Comment by Chefski** [comment]
> by the way I wasn't aware of this pr, so it is a coincidence

Yeah thats what I thought so i just decided that making a poll will probably be best since its community based

**Comment by Chefski** [comment]
B is the community choice
image

**Pull request merged**
