### PR TITLE
Added 5 icons, linked 2, updated 6

### PR DESCRIPTION
**Pull request by Fxsch**
# Description

- Added icons for Tipico Sportwetten, Character.AI, Kõnele, MyFRITZ! and Finamp
- Linked tipico to Tipico Games and google_chrome to Mulch
- Updated findroid, jellyfin and nova_launcher icons to follow design guidelines
- Updated netto to fit into the icon pack better
- Updated thunder to use a line width of 12px instead of 10px
- Remade tusky with a line width of 12px

### Icons added
* Tipico Sportwetten (`tipico.sports`)
* Character.AI (`ai.character.app`)
* Kõnele (`ee.ioc.phon.android.speak`)
* MyFRITZ! (`de.avm.android.myfritz2`)
* Finamp (`com.unicornsonlsd.finamp`)

### Icons updated
* Findroid (`dev.jdtech.jellyfin`)
* Jellyfin (`org.jellyfin.mobile`)
* Netto (`com.valuephone.vpnetto`)
* nova (`com.teslacoilsw.launcher`)
* Thunder (`com.hjiangsu.thunder`)
* Tusky (`com.keylesspalace.tusky`)

### Icons linked
* Tipico Games (linked `de.tipico.games` to `@drawable/tipico`)
* Mulch (linked `us.spotco.mulch` to `@drawable/google_chrome`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Comment by KTibow** [comment]
remember to save as a plain svg, not an inkscape svg

**Comment by Fxsch** [comment]
Didn't know there was a difference. That rarely caused issues and I always just manually fixed it. Is there an issue with any of the icons in this pr?

**Comment by KTibow** [comment]
> Didn't know there was a difference.

Go into a code editor and look at the SVGs you added. They have a bunch of crap in them. While saving as a plain SVG still includes some crap, it helps remove some of it.
For context, a Lawnicon can be as small as this:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" viewBox="0 0 192 192"><path fill="none" stroke="#000" stroke-linejoin="round" stroke-width="12" d="M135.9 95.9c0 22.1-17.9 40-40 40s-40-17.9-40-40 17.9-40 40-40 40 17.9 40 40zm-58.5-59L62 31.8c-2.3-.8-4.8.7-5.3 3.1l-3.3 16c-.3 1.6-1.6 2.9-3.2 3.2l-15.7 3c-2.4.5-3.9 2.9-3.1 5.3l5.2 15.8c.5 1.5.1 3.2-1.1 4.3l-12.2 11c-1.8 1.6-1.8 4.5.1 6.1l12 10.4c1.3 1.1 1.7 2.8 1.2 4.4l-5.3 15.5c-.8 2.3.6 4.8 3.1 5.3l16.2 3.2c1.6.3 2.9 1.6 3.2 3.2l3.2 15.9c.5 2.4 3 3.8 5.3 3.1l15.7-5.2c1.6-.5 3.3 0 4.3 1.2l10.6 12.1c1.6 1.8 4.5 1.9 6.1 0l10.9-12.2c1.1-1.2 2.8-1.7 4.3-1.2l15.7 5.1c2.3.7 4.8-.7 5.2-3.1l3-15.7c.3-1.6 1.5-2.9 3.1-3.2l16-3.5c2.4-.5 3.7-3 3-5.2l-5-15.3c-.5-1.6 0-3.3 1.2-4.3l12.2-10.7c1.9-1.6 1.9-4.5 0-6.2l-12.1-10.4c-1.2-1.1-1.7-2.8-1.2-4.3l5.2-16c.8-2.3-.7-4.8-3.1-5.3L141.5 54c-1.6-.3-2.9-1.5-3.2-3.1l-3.7-16.4c-.5-2.4-3-3.8-5.3-2.9l-14.9 5.2c-1.6.5-3.3.1-4.4-1.1L98.9 23.4c-1.6-1.8-4.4-1.8-6.1 0L81.7 35.7c-1.1 1.2-2.8 1.7-4.3 1.2z"/></svg>
```

**Comment by Fxsch** [comment]
Okay, I'll just resave the icons as plain svg

**Review by Chefski — APPROVED** [review]
Cool, thanks :)

**Pull request merged**
