### PR TITLE
Add icon for CoolApk

### PR DESCRIPTION
**Pull request by Fldicoahkiin**
## Description

https://www.coolapk.com/

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App CoolApk(`com.coolapk.market`) - added from icon request form

### Icons linked
* App CoolApk(linked `com.coolapk.market` to `@drawable/coolapk`)
* App CoolApk(linked `com.coolapk.market.vn` to `@drawable/coolapk`)

### CODE REVIEW

**Comment by Fldicoahkiin** [comment]
After my test,keep the filled style will have the best effect on the phone,but it's up to you

**Comment by Fldicoahkiin** [comment]
I think it's best to delete this commit (06cd2dd)

**Comment by Fldicoahkiin** [comment]
> 经过我的测试，保持填充样式在手机上效果最好，但这取决于你

If take the outline form, the gap in the middle will be only a little, and take the filling form, will be better to look at, and does not affect the Lawnicons design style

**Review by Chefski — APPROVED** [review]
Thanks

**Pull request merged**
