### PR TITLE
Make "External Links" a translatable String

### PR DESCRIPTION
**Pull request by Chefski**
## Description
Made "External Links" a translatable String and added the Polish Translation.

"Icon Request Form" remains as the last String which I couldn't get to work.

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : General change (non-breaking change that doesn't fit the above categories, such as copyediting)

### CODE REVIEW

**Comment by service-paradis** [comment]
Great, it would be "Liens externes" in french :)

**Comment by Chefski** [comment]
@service-paradis thanks! Added it :)

**Review by SuperDragonXD — APPROVED** [review]
I'll migrate the other strings to `strings.xml` later, but looks good.

**Comment by x9136** [comment]
Just in case, I will draw your attention to the idea that it is better to keep all translations in one file, because it will be easier to add, edit or delete lines.

**Pull request merged**
