### PR TITLE
Add 4 icons

### PR DESCRIPTION
**Pull request by TyrionWarMage**
## Description
Added 4 new icons. Ecovacs Home and Nextcloud Passwords may seem a bit small, but this is inline with the original icon
### Icons added
- Calculator Plus Plus (org.solovyev.android.calculator, @drawable/calculator_plusplus)
- Ecovacs Home (com.eco.global.app, @drawable/ecovacs_home)
- Nextcloud Passwords (de.jbservices.nc_passwords_app, @drawable/nc_passwords)
- NZB360 (com.kevinforeman.nzb360, @drawable/nzb360)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Could you round the corners in `calculator_plusplus.svg`, `ecovacs_home.svg` and `nzb360.svg`. 

Could you also make the strokes in `nzb360.svg` 8px or 12px and fix oen of the corners
image

**Comment by TyrionWarMage** [comment]
For ecovacs, i tried to mimic the endings of the E with markers (see https://play-lh.googleusercontent.com/6Jlor0t0DstVrCG0tDj-k7RldcKP9wknE27FGMQFwS5rQdqDnKmbh8ry7MVpIGF-DGI), but i overlooked that Android Studio is not supporting markers. Is there a way to create these kinds of caps? (For now, switched to round, as requested)

**Review by Chefski — APPROVED** [review]

**Comment by Chefski** [comment]
> mimic the endings of the E with markers

Are you referring to the sharp corners? 

> Furthermore, i assumedthe 160px content area is the max area to be used, not the intended area as well. Maybe this can be clarified in the contrib document

I'll add more guidelines about this. Thanks for contributing

**Comment by TyrionWarMage** [comment]
> > mimic the endings of the E with markers
> 
> Are you referring to the sharp corners?
> 
> > Furthermore, i assumedthe 160px content area is the max area to be used, not the intended area as well. Maybe this can be clarified in the contrib document
> 
> I'll add more guidelines about this. Thanks for contributing

I'm referring to this:
grafik
In Inkscape, i used rotated arrow-head markers to mimic this.

**Comment by Chefski** [comment]
@TyrionWarMage i suppose you could try doing what you did, then converting it to a shape. Not ideal but I think it should maintain the sharp corners

**Pull request merged**
