### PR TITLE
Add Aware

### PR DESCRIPTION
**Pull request by Pukimaa**
# Description

### Icons added
* Aware (`aware`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Comment by Pukimaa** [comment]
Weirdly it does have a fill in the build, but not in the SVG file. Any ideas?

**Comment by KTibow** [comment]
Why is the icon made with stroke instead of fill?

**Comment by Pukimaa** [comment]
> Why is the icon made with fill (essentially outlining the icon) instead of stroke?

Could be an exporting issue...will try to fix this later today

**Comment by x9136** [comment]
#1746

**Pull request closed without merging**
