### PR TITLE
Update Revolut icon

### PR DESCRIPTION
**Pull request by Chefski**
# Description

Updated Revolut to the new icon
image

### Icons updated
* Revolut

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Review by x9136 — CHANGES_REQUESTED** [review]
Screenshot 2023-10-14 at 08 49 30
I propose the following changes:
1. Move the vertical line 1px to the left.
2. Use a stroke instead of a fill in the right part.
3. Use a true semicircle.
4. Move the icon slightly to the right to compensate for the jagged right edge.

**Comment by Chefski** [comment]
Out of curiosity, any idea how to prevent Figma from changing the stroke to fill? Not on my usual setup so don't have Illustrator...

**Comment by Chefski** [comment]
Check this one. For me it says its a stroke
image

**Comment by x9136** [comment]
> Check this one. 

It's a stroke now.

> Out of curiosity, any idea how to prevent Figma from changing the stroke to fill?



I haven't encountered Figma changing the stroke to fill on its own. I've had it happen when I saved with a fill because I accidentally made it myself or forgot to remove it when I checked the dimensions. It's easy to change the stroke to fill through this option: Screenshot 2023-10-14 at 15 51 01

So I don't know how to help you, but I'd dig into the change history. Maybe you saved the icon with a fill and the fill appeared because of something else.

**Pull request merged**
