### PR TITLE
Redesign ProtonVPN & YouTube Studio; Add AudioFX

### PR DESCRIPTION
**Pull request by IAmRuMaks**
### Original icons:
Before
### New icons:
After

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Hi! Some minor suggestions: [`suggestions.zip`](https://github.com/LawnchairLauncher/lawnicons/files/8140143/suggestions.zip).

**Comment by IAmRuMaks** [comment]
Just wanted to say that the ProtonVPN icon doesn't really look centered:

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Ah, you’re right. Apologies for the error! Here’s a corrected version: [suggestion.zip](https://github.com/LawnchairLauncher/lawnicons/files/8155137/suggestion.zip).

**Review by patrykmichalik — APPROVED** [review]

**Comment by patrykmichalik** [comment]
Thanks, @IAmRuMaks!

**Pull request merged**
