### PR TITLE
Add XPlayer

### LINKED ISSUE #477: icon request
App Name: XPlayer
Package Name: video.player.videoplayer
Install: 50M+

### PR DESCRIPTION
**Pull request by Chefski**
Adds XPlayer icon (Resolves #477)

Screenshot 2022-06-03 132556

### CODE REVIEW

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! Iʼd suggest these minor geometric tweaks: [`xplayer.zip`](https://github.com/LawnchairLauncher/lawnicons/files/9086212/xplayer.zip).

**Comment by Chefski** [comment]
Updated new icon. For future icons, whats the prefered corner radius?

**Comment by patrykmichalik** [comment]
Cheers for applying the changes! The icons in Lawnicons are generally constructed as follows, with round stroke joins. Therefore, the preferred minimum corner radius is the final radius of a sharp corner with a round stroke join. This is equivalent to 6 px.

image 
image

Additionally, I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. I hope another team member will handle it. Thank you for your interest in contributing!

**Comment by Chefski** [comment]
> Additionally, I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. I hope another team member will handle it. Thank you for your interest in contributing!

Thank you for your service to the Lawnchair and best of luck to you in the future :)

**Comment by patrykmichalik** [comment]
Cheers, @Chefski!

**Review by SuperDragonXD — APPROVED** [review]

**Comment by SuperDragonXD** [comment]
Sorry for the delay, but thanks for the PR!

**Pull request merged**
