### PR TITLE
Add meetup

### PR DESCRIPTION
**Pull request by Sir-Photch**
Compare #1178

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
As previously mentioned, could you change the icon so that the two paths in the `m` don't join a make one thick stroke. With the new guidelines you can use 6px if required however I'd recommend trying to maybe get rid of the dots around it or something else. Also at the top left or the bubble the path isn't quite smooth. You can look at the previous screenshot.

**Comment by Sir-Photch** [comment]
Will do eventually, though which screenshots do you mean?

**Comment by Chefski** [comment]
> though which screenshots do you mean?

In this PR #1178

**Comment by Sir-Photch** [comment]
Is it just me or aren't there any comments with screenshots?

**Comment by Chefski** [comment]
Could be just you:
image

**Comment by Sir-Photch** [comment]
I've tried removing the dots and increasing the size of the icon, but then the two lines of the 'm' still connect. So I changed it to 6px. Also, I've smoothed the edge you were mentioning.

**Review by Chefski — APPROVED** [review]
Thanks

**Pull request merged**
