### PR TITLE
Add Slice 

### PR DESCRIPTION
**Pull request by naveenccmsd**
## Description

Added icon for [Slice](https://play.google.com/store/apps/details?id=indwin.c3.shareapp).

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Slice (`indwin.c3.shareapp`)

### Icons updated
NA

### Icons linked
NA

### CODE REVIEW

**Comment by naveenccmsd** [comment]
PR is linked with https://github.com/LawnchairLauncher/lawnicons/pull/682

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing again. Unfortunately the icon is smaller than the 160x160px content area and should have a stroke width of 12px (rather than the 6px it has right now).
Screenshot 2022-09-24 at 20 51 37

There also seems to be some odd corners that appear where the two corners touch. Although its very subtle, it would be nice to get it fixed. If you can't it'll depend whether the maintainer thinks its fine. It probably won't be noticeable on home screens 
Screenshot 2022-09-24 at 20 56 16

**Comment by naveenccmsd** [comment]
> Hey! Thanks for contributing again. Unfortunately the icon is smaller than the 160x160px content area and should have a stroke width of 12px (rather than the 6px it has right now). Screenshot 2022-09-24 at 20 51 37
> 
> There also seems to be some odd corners that appear where the two corners touch. Although its very subtle, it would be nice to get it fixed. If you can't it'll depend whether the maintainer thinks its fine. It probably won't be noticeable on home screens Screenshot 2022-09-24 at 20 56 16

Thanks for suggestion , corners are fixed now.

image

**Review by Chefski — APPROVED** [review]
Cheers!

**Comment by Chefski** [comment]
@Goooler

**Review by Goooler — APPROVED** [review]

**Pull request merged**
