### PR TITLE
9 icons added, 2 icons updated, 1 icons linked

### PR DESCRIPTION
**Pull request by ZTzTopia**
Icons added:
- App Manager Debug
- Brainly
- Droid-ify
- Lawnicons
- LibChecker
- Neo Backup
- Neo Store
- Play Integrity API Checker
- QuickEdit

Icons updated:
- Google Play Store
- Swift Backup

Icons linked:
- TikTok (Link another TikTok package name)

### CODE REVIEW

**Comment by MominRaza** [comment]
Make Playstore Icon off centre like the previous icon, because play icon (triangle) looks weird inside a circle.

**Comment by ZTzTopia** [comment]
> Make Playstore Icon off centre like the previous icon, because play icon (triangle) looks weird inside a circle.

Yes I see it weird too, I will update it later

**Comment by Goooler** [comment]
@ZTzTopia Could you please rebase? CC @Chefski

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Nice icons! I've got some changes here:

- `quickedit.svg`, `quickedit.xml` and the link for quickedit can be removed as its been added in #658 
- `lawnicons.svg`, `lawnicons.xml and the link for lawnicons can be removed as the icon is already present
- `swift_backup.svg` is placed off centre and is smaller than the 160x160px content area
image

- `app_manager_debug.svg` looks good but I'd just ask to make it 160x160
image

- For the B in `brainly.svg`, I'd just like it to be more refined. There is an unecessary point in in the top right which makes a straight line rather than rounded. The inside parts of the B could also be rounded better. I'll also ask to try and make the stroke for the B 8px but if the icon doesn't work well with the 8px stroke, then we can keep it smaller. Other than that, the icon looks good and has the correct size.
image

- `droid_ify.svg`, `droid_ify.xml` and the link for droid-ify can be removed as its been added in #669 
- `play_integrity_api_checkersvg` needs to be resized to 160x160
image

- In `neo_backup.svg`, could you change the 3 shapes inside the circle on the right side to have a stroke of at least 6px (preferably 8px)
image

- For `neo_store.svg`, the ears could be changed to a width of 6px and the eyes could also be changed to be 6x6px
image

Thanks for your effort :)

**Pull request closed without merging**
