### PR TITLE
Add icon for Geode

### PR DESCRIPTION
**Pull request by wojtas3422**
# Description
Add icon for [Geode launcher](https://geode-sdk.org/)

### Added
Geode (`com.geode.launcher`)

## Contributor's checklist
- [x] I followed [the Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) (upd. Jan 2024) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by x9136** [comment]
Screenshot 2024-04-14 at 21 24 03

Too small.
https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md#canvas--sizes

**Comment by wojtas3422** [comment]
Im sorry, i was using the circle size as reference. Should be fixed now :)

**Comment by x9136** [comment]
> Should be fixed now :)

The icon size is now correct, but the canvas size remains incorrect.

**Comment by wojtas3422** [comment]
Sorry again, set the canvas size to 160x160

**Comment by x9136** [comment]
> set the canvas size to 160x160

Why?
Screenshot 2024-04-14 at 22 04 11


Thanks anyway!

**Pull request merged**
