### PR TITLE
add divvydiary, mk tour, sm run, parqet & paperless share

### PR DESCRIPTION
**Pull request by peterge1998**
## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

### CODE REVIEW

**Comment by peterge1998** [comment]
Designing both mario icons was very hard. might need help here

**Comment by daywalk3r666** [comment]
For super mario run. I test some changes. I remove the group,  path_1 and path_6 and made all strokes 6px.

super_mario_run
Let know what do you think

**Comment by peterge1998** [comment]
> 

Thanks! Looks good!

**Comment by peterge1998** [comment]
It has the wrong dimensions. When I open it with inkscape and export with correct width & height, its invisible. Could you add it to this pr @daywalk3r666 ? Thx!

**Comment by daywalk3r666** [comment]
Give me some minutes. I made a svg in inkscape.

**Comment by daywalk3r666** [comment]
super_mario_run

**Comment by daywalk3r666** [comment]
please check this svg

super_mario_run

**Comment by daywalk3r666** [comment]
What do you think about using this for whole circle instead mario kart
Screenshot_20230314-101331_Trebuchet

**Comment by peterge1998** [comment]
> What do you think about using this for whole circle instead mario kart

Never used shapeshifter for designing before. Looks good, way better than my shitty try :)

**Comment by daywalk3r666** [comment]
I used this only for showing my suggestion. For making svg i use inkscape too

**Comment by peterge1998** [comment]
Ah ok. still learning inkscape tho^

**Comment by daywalk3r666** [comment]
I can try to make an svg tomorrow.

**Comment by daywalk3r666** [comment]
We have sh*t weather. So i make the svg now. Please check it and let me know what do you think

mario_kart_tour

And @Chefski can abmake a review

**Comment by daywalk3r666** [comment]
Oh, I saw that this needs to be aligned
Screenshot_20230314-153111_Trebuchet

**Comment by peterge1998** [comment]
I like it. Looks better than my font attempt

**Review by Chefski — APPROVED** [review]

**Pull request merged**
