### PR TITLE
Add Progressbar95 icon

### PR DESCRIPTION
**Pull request by SamCool939**

### CODE REVIEW

**Comment by arun54321** [comment]
The xml file looks like a svg code. Are you sure it works on android?

**Comment by leapofazzam123** [comment]
Yeah, I don't see any valid Android vector drawable format in the file, you may need to use https://shapeshifter.design/ to convert it to a valid Android vector drawable

**Comment by SamCool939** [comment]
Hold a sec...

**Comment by arun54321** [comment]
The size for vector is 24. not 6. Here is the fixed svg and android vector xml.

```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="@dimen/theme_icon_size"
    android:height="@dimen/theme_icon_size"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="@android:color/white"
        android:pathData="M16.998 4h2v1.999h-2zm0 4.002h2V10h-2zm-4-2.003h2v2.003h-2zm0 4h2v2h-2zM8.996 8.002h2V10h-2zm-4 1.999h2v1.999h-2zm0-4.001h2v2.003h-2zm4-1.999h2v1.999h-2zM3 13.994V20h18v-6.006zm9.997 2h6.002V18h-6.002z" />
</vector>
```

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   height="24"
   width="24"
   version="1.1"
   id="svg4"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs8" />
  <path
     d="M16.998 4h2v1.999h-2zm0 4.002h2V10h-2zm-4-2.003h2v2.003h-2zm0 4h2v2h-2zM8.996 8.002h2V10h-2zm-4 1.999h2v1.999h-2zm0-4.001h2v2.003h-2zm4-1.999h2v1.999h-2zM3 13.994V20h18v-6.006zm9.997 2h6.002V18h-6.002z"
     fill=""
     id="path2" />
</svg>

```

**Comment by SamCool939** [comment]
Everything is fine now, I think...

**Comment by SamCool939** [comment]
Hmm.... Now what?

**Comment by arun54321** [comment]
Looks good to me.  Let's wait for project maintainer's review.

**Review by patrykmichalik — APPROVED** [review]

**Comment by patrykmichalik** [comment]
Thank you, @SamCool939, @arun54321, and @leapofazzam123!

**Comment by SamCool939** [comment]
No problem. 😁

**Pull request merged**
