### PR TITLE
Add Icon for Qobuz

### PR DESCRIPTION
**Pull request by Sir-Photch**
## Description

Adding an icon for Qobuz with (hopefully) round circles.

https://play.google.com/store/apps/details?id=com.qobuz.music

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`com.qobuz.music`)

### Icons linked
* App Name (linked `com.qobuz.name` to `@drawable/qobuz`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing. Got some changes:

- The circles are not perfect circles. Could you fix that?
- The icon goes outside the 160x160px content area size. Mind making it a bit smaller?
- Could you make the line in the bottom right have rounded endpoints?
image

**Comment by Sir-Photch** [comment]
Remade it

**Review by Chefski — APPROVED** [review]
Thanks

**Comment by Sir-Photch** [comment]
Weird, I did not modify the opacity at all. I will make sure this is not an issue in the future.

**Pull request merged**
