### PR TITLE
Add Buckwheat

### PR DESCRIPTION
**Pull request by ZTzTopia**
# Description
Add Buckwheat app icon

### Icons added
* Buckwheat (`com.danilkinkin.buckwheat`)

## Contributor's checklist
- [x] I have followed the [Lawnicons Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md)
- [x] I have ensured that Lawnicons builds correctly
- [x] I am willing to make changes to my icons if someone suggests changes

### CODE REVIEW

**Review by x9136 — CHANGES_REQUESTED** [review]
Thank you for contributing!

The size of the icon is roughly equal to the size of the canvas. Please make the canvas size to 192×192px, keeping the current icon size.

**Comment by x9136** [comment]
Screenshot 2023-09-24 at 17 28 16

The canvas size is fine now, but you've shrunk the icon. Icons should be 160x160px according [to the guides](https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/CONTRIBUTING.md#artboard--grid).

**Comment by ZTzTopia** [comment]
yeah, but if I use 160x160px it will look weird. so should I change it to 160x160px?

**Comment by x9136** [comment]
> yeah, but if I use 160x160px it will look weird. so should I change it to 160x160px?

Screenshot 2023-09-24 at 17 46 09

I think it's okay. Let me clarify. The main thing is that the width or height should be 160px, it's not necessarily a 160×160px square.

**Comment by ZTzTopia** [comment]
image

oh, so it's like this?

**Comment by x9136** [comment]
> oh, so it's like this?

Yeah, that's about right. In my version, I moved it a little to the right so it would be centered rather than pressed against the left edge.

**Pull request merged**
