### PR TITLE
adding Alipay app as ali_pay.svg

### PR DESCRIPTION
**Pull request by medtty**

### CODE REVIEW

**Comment by projjalm** [comment]
The added svg looks very similar to alipay.svg, which I think it is meant to replace.

**Review by projjalm — COMMENTED** [review]
The added svg looks very similar to `alipay.svg`, which I think it is meant to replace.

**Review by Chefski — COMMENTED** [review]
Icon is the same as `alipay.svg` except this one isn't linked to anything. This seems unnecessary the Alipay already has an icon

**Comment by Chefski** [comment]
I'll be closing this PR as it adds the same icon but with a different file name. Thanks for contributing

**Pull request closed without merging**
