### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by mwchiao**
Garmin Connect, GroupMe, Hinge, Trime, wger

## Description

Fixes #(issue) 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Garmin Connect (`com.garmin.android.apps.connectmobile`)
* GroupMe (`com.groupme.android`)
* Hinge (`co.hinge.app`)
* Trime (`com.osfans.trime`)
* wger (`de.wger.flutter`)

edit 2022-10-08: `com.hinge.app` --> `co.hinge.app`

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing! Unfortunately the icons are smaller than the 160x160px content area size. Could you increase the icons size? ([Guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md))
image

image


`trime.svg` also seems to have two circles which aren't being used. Mind deleting them?
Thanks

**Comment by mwchiao** [comment]
All the icons miss the mark, right? Not just the two you attached to your comment?

**Comment by mwchiao** [comment]
I went ahead and changed all of them

**Review by Chefski — APPROVED** [review]
Thanks for making the changes

**Pull request merged**
