### PR TITLE
+2 icons

### PR DESCRIPTION
**Pull request by I21b**
# Description
Add 2 apps' icon to Lawnicons.

### Added

Rizline (`com.PigeonGames.Rizline`)
律动轨迹 ~~ Rizline (`com.leiting.ldgj`)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by I21b** [comment]
Sorry for closing and reopening, I thought I made a mistake, but I didn't.
(I'm using a translator, so my grammar may be wrong.)

**Review by I21b — COMMENTED** [review]
### Canvas and sizes
- [ ] 1. Canvas: `192×192px`.
  2. Non-square icons: the long side of the icons should be `160px`.
- [x] 3. Square icons: `154×154px`.

### Color, stroke width and rounding
- [x] 1. Color: black `#000`.
- [x] 2. No fill. Base stroke width: `12px`. `14px`, `10px`, `8px` — depending on the shape of the icons. `6px` — for fine details.
- [x] 3. Rounded ends and joins. 90° corners are rounded by `6-32px`.

### Naming
- [x] 1. Names should match the official app name and contain no additional text.
- [x] 2. If the original name is not in English, then add a localized (or transliterated) one to it using `~~`.
Example: `フールー ~~ Hulu`.
- [x] 3. The names of the drawables should repeat the names of the apps if nothing prevents it.

### Quality
- [x] 1. Ensure that icons are easily recognizable.
- [x] 2. Align icons to [the visual center](https://www.google.com/search?sca_esv=1fcec3f5e0b15e20&q=what+is+visual+center+of+an+icon&tbm=isch&source=lnms).
- [x] 3. Avoid blackness or noticable black spots by reducing the stroke width or simplifying the icons.
- [x] 4. Avoid close distances between strokes. The icons on the phone screen will be smaller, so the small distances between the strokes will stick together.
- [x] 5. Avoid drastic changes in stroke widths. When the strokes next to each other differ in width by 4px or more, the icon will look sloppy.

**Review by x9136 — CHANGES_REQUESTED** [review]
The icons are too small. They are not square, so the size should be larger.

I also suggest making the lightning bolt 2 times larger in the Chinese version so that it does not look like a black dot on the phone. Although lightning bolt is hardly important and you can link both apps to `rizline.svg`.

**Comment by I21b** [comment]
> The icons are too small. They are not square, so the size should be larger.
> 
> I also suggest making the lightning bolt 2 times larger in the Chinese version so that it does not look like a black dot on the phone. Although lightning bolt is hardly important and you can link both apps to `rizline.svg`.

I can't work on this now, and this is my first time making something like this, so I might make a mistake

I might do this in a couple days

**Pull request closed without merging**
