### PR TITLE
Add Clock (AOSP Deskclock)

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Add support for Android Deskclock (AOSP Clock app)

Icon:

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Icon seems to be broken...

**Comment by ThatOneCalculator** [comment]
@patrykmichalik Apologies for the ping, but if you have any clue on how to fix this, I'd greatly appreciate your insight. It just shows up as blank.

**Comment by ThatOneCalculator** [comment]
Nope... :(

**Comment by ThatOneCalculator** [comment]
Fixed!

**Comment by patrykmichalik** [comment]
Thanks for your interest in contributing! The dynamic clock icon that you see when using Lawnicons is part of Lawnchair. The same applies to the dynamic calendar icon. To link the `com.android.deskclock` package to this icon, please open a pull request in the Lawnchair repository. Here’s a link to the relevant file: https://github.com/LawnchairLauncher/lawnchair/blob/12.1-dev/lawnchair/res/xml/grayscale_icon_map.xml. Cheers!

**Comment by ThatOneCalculator** [comment]
Ty. That's actually why I kept this PR as a draft, but I guess I could open a new one ^^;

**Comment by patrykmichalik** [comment]
I closed this PR because itʼs impossible to move a PR from one repository to another. The only solution available here is to open a new PR in the Lawnchair repository, which youʼre more than welcome to do!

**Pull request closed without merging**
