### PR TITLE
+3 icons

### PR DESCRIPTION
**Pull request by Pratham-T**
# Description

Added icons for 3 apps. Contributing icons for first time, let me know if any changes are required.

image

In particular, the following choices were made by me:
 - 3D Calculator corner radius as 12px instead of 6px which made it look more visually consistent with other icons in the examples.
 - HungerBox Cafe shapes above the bowl as filled due to their small size. The filled shapes are drawn a bit smaller than the original logo as when they were made to scale, they made the logo very dense.

### Added

GeoGebra 3D Calculator (org.geogebra.android.g3d/org.geogebra.android.privatelibrary.splashscreen.SplashScreenActivity)
HungerBox Cafe (com.hungerbox.customer.common/com.hungerbox.customer.prelogin.activity.MainActivity)
Entrust Identity (com.entrust.identityGuard.mobile/com.entrust.identityGuard.mobile.MainActivity)

## Contributor's checklist
- [x] I followed [the Lawnicons guidelines](https://github.com/LawnchairLauncher/lawnicons/blob/develop/CONTRIBUTING.md) and will make changes if someone suggests. I will also make sure that Lawnicons builds correctly.

### CODE REVIEW

**Comment by x9136** [comment]
In the screenshot, you can see that only the first icon has the correct size.

Try to make icons without fills and masks. This way they will fully comply with the Lawnicons guidelines. They will be easy to check and change if ever needed.

> HungerBox Cafe shapes above the bowl as filled due to their small size.
 
For example, you can create a 12×12px square with 12px stroke width instead of the square with a fill.

**Comment by Pratham-T** [comment]
Thanks for the feedback. I enlarged the icon in Entrust Identity. And tweaked the HungerBox icon a bit. After enlarging the bowl below, the shapes above it proportionately scaled looked good in strokes of width 10px. Kindly review if it is upto Lawnicons guidelines.

New image for reference:
image


Thanks!

**Comment by Pratham-T** [comment]
As an aside, especially I feel that the shapes in the HungerBox icon look visually different in size due to the negative space inside being different for different shapes. Let me know if I should change them so that the whitespace inside each is uniform.

**Comment by x9136** [comment]
> I feel that the shapes in the HungerBox icon look visually different in size due to the negative space inside being different for different shapes.

You can balance the top part of the icon better if you want.

I would increase the height of the icon to 160px ± 0.05px. It is also worth moving the bottom part slightly to the left so that it is in the center.

**Comment by x9136** [comment]
However, I won't be able to accept icons created with masks because the masks result in jagged edges as far as I can see.
x

**Comment by Pratham-T** [comment]
> However, I won't be able to accept icons created with masks because the masks result in jagged lines as far as I can see.
Interesting since I did not explicitly use masks. Saw the svg code and somehow Figma is making closed path's strokes which are aligned as inside instead of center as a mask. (Sorry not a frequent figma user, if this was a common knowledge)

I re-made 3D calculator icon. Check if the jagged-ness issue is now resolved or not, since no masks in the svg code this time.
If this one is fine, I'll remake the other two over the week when I get time free.

**Comment by x9136** [comment]
> Check if the jagged-ness issue is now resolved or not, since no masks in the svg code this time.

Everything is smooth.

**Comment by x9136** [comment]
Great, thanks!

**Comment by Pratham-T** [comment]
Thanks. I see that you made some tweaks before merging. Would love to hear feedback about what was off, if you're free ofc.

**Pull request merged**
