### PR TITLE
Introduce Yandex Mail and SMARTY icons

### PR DESCRIPTION
**Pull request by 00p513-dev**

### CODE REVIEW

**Comment by paphonb** [comment]
The SMARTY icon looks really complex despite a fairly simple shape. Can you try optimizing it?

**Comment by 00p513-dev** [comment]
> The SMARTY icon looks really complex despite a fairly simple shape. Can you try optimizing it?

I'll give it a go, i had extracted from the official app

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Sorry for keeping you waiting! I’d suggest simplifying the SMARTY icon as per @paphonb’s comment and making the Yandex Mail icon resemble the [official logo](https://yastatic.net/s3/passport-static/core/v0.2.230-12/i/services_icons/mail.svg) more closely.

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
`app/src/main/res/drawable/yandex_mail.svg` seems to have the wrong file extension. It should be an XML file rather than an SVG file. Would you be able to rename it? The content of the file looks good.

**Comment by 00p513-dev** [comment]
> `app/src/main/res/drawable/yandex_mail.svg` seems to have the wrong file extension. It should be an XML file rather than an SVG file. Would you be able to rename it? The content of the file looks good.

done :)

**Review by patrykmichalik — APPROVED** [review]

**Comment by patrykmichalik** [comment]
Thanks for contributing, @00p513-dev!

**Pull request merged**
