### PR TITLE
Added Icons Aliucord, Bible, HBO Max, Moviebase, and RCX.

### PR DESCRIPTION
**Pull request by snthcy**

### CODE REVIEW

**Comment by RikKoedoot** [comment]
try following the CONTRIBUTING.md file: https://github.com/LawnchairLauncher/lawnicons/blob/main-wip/CONTRIBUTING.md
these icons do not follow the guidelines

**Comment by snthcy** [comment]
And how exactly?

**Comment by ZhmieXD** [comment]
> And how exactly?

Um, okay, I supposed you have followed the version of the contributing guide prior to the updated one, Me too, and I might update my icons for my pull request in the future.

So as you may know, the `main-wip` beach version of lawnicons now features a different, uniform style of lines style icons, and apparently, the contributing guide has been updated to make contributors submit their icons in that style.

I might modify my icons to use this new style, but as for you, I think you're fine to just wait for yours to be merged, and let them be updated by the maintainer to the new style in the `main-wip` version since you have only submitted 5 icons. I got 54 icons submitted so I might have to do them all by myself to save time 😂😂😂😂

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Hello, and thanks for your interest in contributing! It appears that you’ve added 5 XML files, but only 2 SVG files. Would you be able to add the 3 missing SVGs to the `svgs` folder? Cheers!

**Comment by Chefski** [comment]
Hiya @snthcy ! Would you still be willing to remake the icons to match the lawnicons style and add the 3 missing svgs?

**Comment by snthcy** [comment]
> Hiya @snthcy ! Would you still be willing to remake the icons to match the lawnicons style and add the 3 missing svgs?

Hey! Sorry, since this PR was created, I've switched to iOS and I don't have Android Studio installed anymore. Apologies.

**Pull request closed without merging**
