### PR TITLE
Add 12 icons

### PR DESCRIPTION
**Pull request by Fxsch**
## Description

Add icon for AL-chan, Aptoide, Lighthouse PM, Arcaea, Monerujo, Cytoid, KartaView, MJ PDF Reader, eufy Clean, Minetest, Subway Surf and Wallpaper Engine

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* AL-chan (`com.zen.alchan`) 
* Aptoide (`cm.aptoide.pt`)
* Lighthouse PM (`com.jeroen1602.lighthouse_pm`)
* Arcaea (`moe.low.arc`)
* Monerujo (`com.m2049r.xmrwallet`)
* Cytoid (`me.tigerhix.cytoid`)
* KartaView (`com.telenav.streetview`)
* MJ PDF Reader (`com.gitlab.mudlej.MjPdfReader`)
* eufy Clean (`com.eufylife.smarthome`)
* Minetest (`net.minetest.minetest`)
* Subway Surf (`com.kiloo.subwaysurf`)
* Wallpaper Engine (`io.wallpaperengine.weclient`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! I've got 3 small changes to ask for:

- Increase size of `eufy_clean` to fit the 160x160px content area
- Increase size of `lighthouse_pm` to fit the 160x160px content area and centre
- ncrease size of `wallpaper_engine` to fit the 144x144px content area

**Comment by Fxsch** [comment]
Shouldn't eufy_clean be 144px since it's a square for the most part?

**Comment by Chefski** [comment]
> Shouldn't eufy_clean be 144px since it's a square for the most part?

Other home shaped icons like `home_assistant`, `ikea_home_smart`, 'google_home` have 160x160px. 160px would be more consistent with the other icons.

**Comment by Fxsch** [comment]
Changed it

**Review by Chefski — APPROVED** [review]
Thanks

**Pull request merged**
