### PR TITLE
Add icon for inDrive

### PR DESCRIPTION
**Pull request by Uni-Rider**
## Description
https://play.google.com/store/apps/details?id=sinet.startup.inDriver

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

### CODE REVIEW

**Comment by Chefski** [comment]
Do you generate the XML drawable file inside Android Studio?

**Review by Chefski — APPROVED** [review]
Icon is fine. Just changed the XML

**Comment by Uni-Rider** [comment]
> Do you generate the XML drawable file inside Android Studio?

No, I converted it online

**Comment by Chefski** [comment]
Next time use Android Studio as when I tried checking if the XML image comes up, it didn't show anything.

**Pull request merged**
