### PR TITLE
3 icons added

### PR DESCRIPTION
**Pull request by Chefski**
## Description

Fixes #(issue) 

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
✅ : Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* Apex Legends Mobile (`com.ea.gp.apexlegendsmobilefps`)
* Franco Kernel Manager (`com.franco.kernel`)
* Tachiyomi (`eu.kanade.tachiyomi`) + (`eu.kanade.tachiyomi.j2k`)

### CODE REVIEW

**Review by Goooler — APPROVED** [review]

**Comment by Goooler** [comment]
@Chefski Can you rebase?

**Comment by Goooler** [comment]
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     app.lawnchair.lawnicons.app-main-[55](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3076518384/jobs/4970725064#step:6:56):/xml/grayscale_icon_map.xml:19: error: resource drawable/apex_legends (aka app.lawnchair.lawnicons:drawable/apex_legends) not found.
     app.lawnchair.lawnicons.app-main-55:/xml/grayscale_icon_map.xml:237: error: resource drawable/franco_kernel_manager (aka app.lawnchair.lawnicons:drawable/franco_kernel_manager) not found.
     app.lawnchair.lawnicons.app-main-55:/xml/grayscale_icon_map.xml:[58](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3076518384/jobs/4970725064#step:6:59)9: error: resource drawable/tachiyomi (aka app.lawnchair.lawnicons:drawable/tachiyomi) not found.
     app.lawnchair.lawnicons.app-main-55:/xml/grayscale_icon_map.xml:[59](https://github.com/LawnchairLauncher/lawnicons/actions/runs/3076518384/jobs/4970725064#step:6:60)0: error: resource drawable/tachiyomi (aka app.lawnchair.lawnicons:drawable/tachiyomi) not found.
     error: failed linking file resources.
```

**Comment by Goooler** [comment]
@Chefski want to invite you join us, have any intrests?

**Comment by Chefski** [comment]
> @Chefski want to invite you join us, have any interest?

Sure gladly :)
You can add me on Discord if you wanna talk more priv: chefski#0865

**Comment by Goooler** [comment]
> > @Chefski want to invite you join us, have any interest?
> 
> Sure gladly :) You can add me on Discord if you wanna talk more priv: chefski#0865

We are using telegram to communicate, dm me @goooler7.

**Pull request merged**
