### PR TITLE
Add 6 Icons, Link 1 Icon, and sort lines alphabetically in `grayscale_icon_map.xml`

### PR DESCRIPTION
**Pull request by flame-0**
- Binary Eye
- LessPass
- Neo Store
- SIM Toolkit
- Twidere
- Wild Rift

### CODE REVIEW

**Comment by flame-0** [comment]
Since there's no progress in pull request: https://github.com/LawnchairLauncher/lawnicons/pull/535, I made an update from scratch that uses the standard design. One thing here that is different is using `stroke width: 18px` to follow the reference logo. Let me know if this pull request needs changes.

image

**Review by patrykmichalik — CHANGES_REQUESTED** [review]
Thanks for the PR! For consistency with the rest of the icons included in Lawnicons, Iʼd suggest reworking `twidere.svg` such that it uses an outlined style. Hereʼs a representation of what I have in mind:

image

**Comment by flame-0** [comment]
> Thanks for the PR! For consistency with the rest of the icons included in Lawnicons, Iʼd suggest reworking `twidere.svg` such that it uses an outlined style. Hereʼs a representation of what I have in mind:
> 
> image

That's much better. I reworked the logo! :)

**Comment by patrykmichalik** [comment]
Cheers! That looks great to me. I think it nicely matches the style of Lawnicons.

Additionally, I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. I hope another team member will handle it. Thank you for your interest in contributing!

**Comment by SuperDragonXD** [comment]
Sorry for the delay, but thanks @flame-0!

**Pull request merged**
