### PR TITLE
15 icons

### PR DESCRIPTION
**Pull request by x9136**
## Type of change
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

## Icons added from icon request form
* Clipeus (`me.lucky.clipeus/me.lucky.clipeus.MainActivity`) 
* Color Picker (`gmikhail.colorpicker/gmikhail.colorpicker.activities.MainActivity`) 
* Crossy Road (`com.yodo1.crossyroad/com.hipsterwhale.hwutils.OverrideUnityActivity`) 
* Device Info (`com.ytheekshana.deviceinfo/com.ytheekshana.deviceinfo.SplashActivity`) 
* MyAnimeList (`net.myanimelist.app/net.myanimelist.presentation.activity.HomeActivity`) 
* Offi Directions (`de.schildbach.oeffi/de.schildbach.oeffi.directions.DirectionsActivity`) 
* Offi Plans (`de.schildbach.oeffi/de.schildbach.oeffi.plans.PlansPickerActivity`) 
* Offi Stations (`de.schildbach.oeffi/de.schildbach.oeffi.stations.StationsActivity`) 
* Otraku (`com.otraku.app/com.otraku.app.MainActivity`) 
* Paisa (`dev.hemanths.paisa/dev.hemanths.paisa.MainActivity`) 
* Swish (`se.bankgirot.swish/se.bankgirot.swish.ui.SplashActivity`) 
* Trendyol (`trendyol.com/com.trendyol.common.splash.impl.ui.SplashActivity`) 
* Upstox (`in.upstox.app/in.upstox.pro.beta.app.UpstoxMainActivity`) 
* Upstox Old (`in.upstox.pro/in.upstox.pro.views.splash.SplashActivity`)
* Moto (`com.motorola.moto/com.motorola.assist.ui.screens.MainActivity`)

### CODE REVIEW

**Review by Chefski — APPROVED** [review]

**Comment by x9136** [comment]
@Chefski What can we do about [Offi](https://play.google.com/store/apps/details?id=de.schildbach.oeffi&hl=en&gl=US)? This tricky app has 3 different components inside of it, so I added 3 icons, but only 1 is used.

themed_icons_off themed_icons_on

**Comment by Chefski** [comment]
How did you download 3 different apps? I can only find the one you linked

**Comment by x9136** [comment]
> How did you download 3 different apps? I can only find the one you linked

I installed it from the Play Store. Ok, I think it's better if I show you videos. Restarting Lawnchair doesn't change anything.

https://github.com/LawnchairLauncher/lawnicons/assets/60105060/b812eefe-3464-46dc-95fb-f934689d5e03


https://github.com/LawnchairLauncher/lawnicons/assets/60105060/2fb414e1-2125-4769-b490-6b3dd6b9c770

**Comment by Chefski** [comment]
Hmm... I'm not sure why it only applies the H... Didn't even know theres apps that install 3 separate ones. 

Maybe @SuperDragonXD know what's wrong.

**Comment by SuperDragonXD** [comment]
It's more of an issue with Lawnchair's current system of applying themed icons.

The current system (taken from A12-12.1) uses only the package name of the app to theme icons. However, the icon pack system uses both package and activity name to determine the right icons. I can't really explain the whole system (there are exceptions, i.e. using icon packs as themed icons and such) since I've yet to fully comprehend the system, but that's the basics.

I think the issue could be fixed with a refactor on how themed icons are applied *in Lawnchair*. Maybe it could happen in LC 13, idk. It will not likely though happen since most of our devs are busy irl.

> Hmm... I'm not sure why it only applies the H... Didn't even know theres apps that install 3 separate ones.

Yeah, you can make multiple activities display in a launcher like Lawnchair.

**Pull request merged**
