### PR TITLE
Add 56 icon and link 9 icon 

### PR DESCRIPTION
**Pull request by KarlRaphel**
### Icons added
* WeWork (`com.tencent.wework`)
* Alook (`alook.browser`)
* Dazhongdianping (`com.dianping.v1`)

### Icons linked
* ticktick (linked `cn.ticktick.task` to `com.ticktick.task`)

### CODE REVIEW

**Comment by KarlRaphel** [comment]
## Icons addition information

### Icons added
* baimiao(`com.uzero.baimiao`)
* baidutieba(`com.baidu.tieba`)
* chunqiuhangkong (`com.china3s.android`)
* xiaohongshu (`com.xingin.xhs`)
* taopiaopiao (`com.taobao.movie.android`)

**Comment by KarlRaphel** [comment]
## Icons addition information

### Icons added
* dida_taxi (`com.didapinche.booking/com.didapinche.booking.home.activity.StartActivity`) 
* tictoc (`com.ss.android.ugc.aweme/com.ss.android.ugc.aweme.splash.SplashActivity`) 
* enyamusic (`com.enya.enyamusic/com.enya.enyamusic.view.activity.start.SplashActivity`) 
* huabancesu (`com.huawei.genexcloud.speedtest/com.huawei.genexcloud.speedtest.ui.SplashActivity`) 
* tmri12123 (`com.tmri.app.main/com.tmri.app.ui.activity.main.TmriNewActivity`) 
* meituan (`com.sankuai.meituan/com.meituan.android.pt.homepage.activity.MainActivity`) 
* miyoushe (`com.mihoyo.hyperion/com.mihoyo.hyperion.splash.SplashActivity`) 
* mixuebingchen (`com.mxbc.mxsa/com.mxbc.mxsa.modules.splash.SplashActivity`) 
* luckincoffe (`com.lucky.luckyclient/com.luckin.client.main.splash.SplashActivity`) 
* magicmagnet (`com.magicmagnet/com.magicmagnet.common.activity.SplashActivity`) 
* tencentmeeting (`com.tencent.wemeet.app/com.tencent.wemeet.app.StartupActivity`) 
* ecloud (`com.cn21.ecloud/com.cn21.ecloud.activity.login.StartActivity`) 
* mipush (`com.xiaomi.xmsf/top.trumeet.mipushframework.wizard.WelcomeActivity`) 
* alibank (`com.mybank.android.phone/com.mybank.android.phone.MainActivity`) 
* xiaomishop (`com.xiaomi.shop/com.xiaomi.shop.activity.MainTabActivity`) 
* mitime (`com.xiaomi.mitime/com.xiaomi.mitime.activity.MakeCallActivity`) 
* ctrip (`ctrip.android.view/ctrip.business.splash.CtripSplashActivity`) 
* starbucks (`com.starbucks.cn/com.starbucks.cn.home.revamp.launch.RevampLaunchActivity`) 
* xingtu (`com.xt.retouch/com.xt.retouch.uilauncher.LaunchActivity`) 
* xunlei (`com.xunlei.downloadprovider/com.xunlei.downloadprovider.launch.LaunchActivity`) 
* youku (`com.youku.phone/com.youku.phone.ActivityWelcome`) 
* chinatelecom (`com.ct.client/com.ct.client.activity.SplashActivity`) 
* jiansheyinghang (`com.chinamworld.main/com.ccb.start.MainActivity`) 
* chinaunion (`com.sinovatech.unicom.ui/com.sinovatech.unicom.basic.ui.activity.WelcomeClient`) 
* jbusdriver (`me.jbusdriver/me.jbusdriver.ui.activity.SplashActivity`) 
* nga (`gov.pianzong.androidnga/gov.pianzong.androidnga.Splash_0`) 
* switchguide (`com.daydream.sn/com.daydream.sn.ui.ShopMainActivity`) 
* tts_server (`com.github.jing332.tts_server_android/com.github.jing332.tts_server_android.ui.MainActivity`) 

### Icons linked
* ppsspp (linked `org.ppsspp.ppssppgold/org.ppsspp.ppsspp.PpssppActivity` to org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity)

**Comment by KarlRaphel** [comment]
## Icons addition information

### Icons added
* byyoung ('com.byyoung.setting/com.byyoung.setting.Welcome')
* douban ('com.douban.frodo/com.douban.frodo.activity.SplashActivity')
* tictoc_helper ('com.rong862.bear/com.rong862.bear.MainActivity')
* feichangzhun ('vz.com/com.feeyo.vz.DefaultAlias')
* pinduoduo ('com.xunmeng.pinduoduo/com.xunmeng.pinduoduo.ui.activity.MainFrameActivity')
* lightstart ('com.wpengapp.lightstart/com.wpengapp.support.activity.LauncherActivity')
* qingzhuo ('com.farplace.qingzhuo/com.farplace.qingzhuo.views.SplashActivity')
* socmark ('com.nasoft.socmark/com.nasoft.socmark.ui.MainActivity')
* sunlogin ('com.oray.sunlogin/com.oray.sunlogin.application.Main')
* xiaoheihe ('com.max.xiaoheihe/com.max.xiaoheihe.SplashActivity')
* xinshang ('me.gkd.xs.ps/me.gkd.xs.ps.ui.activity.WelcomeActivity')
* arp ('cn.arp.app.newarp.releaseAuth2Production/cn.arp.app.newarp.ui.SplashActivity')
* chsiapp ('cn.com.chsi.chsiapp/cn.com.chsi.chsiapp.GuideActivity')
* legado ('io.legado.app.release/io.legado.app.ui.welcome.WelcomeActivity')
* emobile ('com.ecology.view/com.ecology.view.WelcomeActivity')
* momo_test ('io.github.vvb2060.mahoshojo/io.github.vvb2060.mahoshojo.home.HomeActivity')
* zzzfun ('org.daimhim.zzzfun/org.daimhim.zzzfun.ui.SplashActivity')

### Icons linked
* clock (link 'com.motorola.cn.deskclock/com.motorola.cn.deskclock.DeskClock' to 'com.amdroidalarmclock.amdroid/com.amdroidalarmclock.amdroid.MainActivity')
* alpha (link 'io.github.vvb2060.magisk/com.topjohnwu.magisk.ui.MainActivity' to 'ComponentInfo{com.fox2code.mmm/com.fox2code.mmm.MainActivity}')
* cardemulator (link 'com.yuanwofei.cardemulator.pro/com.yuanwofei.cardemulator.MainActivity' to 'com.wakdev.wdnfc/com.wakdev.nfctools.free.views.MainActivityFree')
* smscode (link 'com.github.tianma8023.xposed.smscode/com.github.tianma8023.xposed.smscode.HomeActivityAlias' to 'com.android.mms/com.android.mms.ui.LaunchActivity')

**Comment by KarlRaphel** [comment]
## Icons addition information

### Icons added
* biliroaming (`me.iacn.biliroaming/me.iacn.biliroaming.MainActivityAlias`)
* fontweight (`fontweight.adjustment/fontweight.adjustment.MainActivity`)
* tsbattery (`com.fankes.tsbattery/com.fankes.tsbattery.Home`)

### Icons linked
* bilibili_vip4in1 (link `com.weixiao.bz/com.weixiao.bz.MainActivity` to `me.iacn.biliroaming/me.iacn.biliroaming.MainActivityAlias`)
* gamespace (link `io.chaldeaprjkt.gamespace/io.chaldeaprjkt.gamespace.settings.SettingsActivity` to `io.chaldeaprjkt.gamespace/.settings.SettingsActivity`)
* LSPosed Manager (link `com.android.shell/org.lsposed.manager.ui.activity.MainActivity` to `org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity`)

**Comment by KarlRaphel** [comment]
all the missing icons in my phone have been draw
there may be no more updates
hope to merge them into the main branch soon
^_^

**Review by Chefski — APPROVED** [review]
Thanks! :)

**Comment by x9136** [comment]
@Chefski I don't know how much free time you had, but I was wondering if you'd keep` tictoc.svg` because there's already `tiktok.svg`. And you did. Also, the size of tictoc.svg is also smaller than 160x160. Everything else I didn't check, so maybe that's how lucky I got.

**Comment by KarlRaphel** [comment]
@x9136 Since the package name of the Chinese version of tiktok does not actually contain `tiktok`, so I accidentally spelled it wrong when I was working, and I will pull another request to fix it.

**Comment by KTibow** [comment]
these svgs look unoptimized, they have an `id` for no reason, duplicate paths, using `<style>` instead of attributes, etc

**Comment by KarlRaphel** [comment]
@KTibow I have optimized them now, please check https://github.com/LawnchairLauncher/lawnicons/pull/1395

**Pull request merged**
