### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by Vitaliklidy**
### Icons added
* HIT (`com.lionwood.nitwrap`)
### Icons Linked
* My Vodafone (`ua.vodafone.myvodafone`)

### CODE REVIEW

**Review by Chefski — CHANGES_REQUESTED** [review]
Hey! Thanks for contributing.

The letters in `hit.svg` have a thickness of around 10/11px. Could you make it either 8 or 12px? Could you also round the corners.
image

For `my_vodafone.svg`, I'm wondering if `vodafone.svg` already present in the svgs folder can be used instead. It seems like the same icom

**Comment by Vitaliklidy** [comment]
Yes, the My Vodafone and Vodafone has same icon

**Comment by Chefski** [comment]
why not just link component info to the already existing icon then instead?
vodafone

**Comment by Vitaliklidy** [comment]
Ok I link it

**Comment by Vitaliklidy** [comment]
I change hit icon is it better ?

**Pull request merged**
