### PR TITLE
Add 4 icons, rework S-Invest

### PR DESCRIPTION
**Pull request by peterge1998**
## Description

Fixes #(issue)

## Type of change

:x: Bug fix (non-breaking change which fixes an issue)
:x: Icon addition (non-breaking change that adds/modifies Lawnicons's icons)
:x: General change (non-breaking change that doesn't fit the above categories like copyediting)

### Icons added
* App Name (`package.name`) - added from icon request form
* App Name (`package.name`)
* App Name (`package.name`)

### Icons updated
* App Name (`package.name`)
* App Name (`package.name`)

### Icons linked
* App Name (linked `package.name` to `@drawable/package`)
* App Name (linked `package.name` to `@drawable/package`)

### CODE REVIEW

**Review by Chefski — COMMENTED** [review]
`s_invest` seems to may have been exported wrong. Mind checking it?
image
image

**Comment by peterge1998** [comment]
I have just copied https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/mobiles_bezahlen.svg, deleted the ))) and added the arrow. Nothing else. Then that icon needs a rework too ^

**Comment by Chefski** [comment]
[mobiles_bezahlen](https://github.com/fischer-felix/lawnicons/blob/8b41bd5926cbb6076d8cb7d8f3836bcefd1e882d/svgs/mobiles_bezahlen.svg) should be changed. The S in the bottom is missing. If you would like to fix it you can remove the change to `s_invest` and instead add the S to the bottom right in `mobiles_bazahlen`.

**Comment by peterge1998** [comment]
Honestly i dont know why the s is showing up for you in the pic with the lines. Maybe a conflic between adobe and inkscape idk. Please fix both icons, when i oprn them its just ))) or the arrow...

**Comment by Chefski** [comment]
Why remove the S though? It's in the original icon?

**Comment by peterge1998** [comment]
I did not remove the s, i just copied the file & it does not show up in both svgs for me

**Comment by peterge1998** [comment]
> Why remove the S though? It's in the original icon?

Okay, I reworked all icons with the little s to a 8px shape. let me know if this is fine (i guess it is)

**Review by Chefski — APPROVED** [review]
Looks good thanks

**Pull request merged**
